# Copyright (c) 2026 Manish Shivach
# SPDX-License-Identifier: MIT
"""Two-input arithmetic: say which second file, and repeat what CDO says.

Two separate problems, both about the operators that take two inputs.

The ``*arith`` families do not take two data series. The second input is a
statistics file with one field per day, month, year, hour, day of year, month of
year or season, and every one of the seven modules says so in its documentation
— "Usually infile2 is generated by an operator of the module <X>stat". The GUI
asked for "2 files" and said nothing about which, so two raw series into
``monsub`` produced "Timestep 2 has wrong date!" after the run, and two raw
series into ``ymonsub`` produced no error at all and the wrong numbers.

And the Arith module broadcasts. "One of the input files can contain only one
timestep or one variable", and when that happens CDO announces it on **stdout**,
exits 0, and writes a well-formed file. Measured on CDO 2.6.0.
"""

import pytest

from ncexplorer_toolkit.core.batch import BatchJob
from ncexplorer_toolkit.core.categories import (
    NCExplorerCategory, OPERATOR_SCHEMA, _COMPANION_MODULES, operator_module,
)
from ncexplorer_toolkit.core.model import ERROR
from ncexplorer_toolkit.core.nc_integration import stream_notices


def two_input_arithmetic():
    return sorted(
        name for name, spec in OPERATOR_SCHEMA.items()
        if spec.category is NCExplorerCategory.ARITHMETIC and spec.nin == 2
    )


def companion_operators():
    """The *arithmetic* half of the companion table.

    ``_COMPANION_MODULES`` covers nine modules now, two of them comparison ones
    — the trap belongs to the module, not to arithmetic. This file still asks
    only about the seven it was written for; the other two are covered by
    ``tests/test_comparison_category.py``, and
    ``test_every_companion_module_is_claimed_by_one_of_the_two_files`` below is
    what stops a tenth module being added and tested by neither.
    """
    return sorted(name for name in two_input_arithmetic()
                  if operator_module(name) in _COMPANION_MODULES)


def test_the_two_families_between_them_cover_every_two_input_operator():
    """Every 2-in arithmetic operator is either a ``*arith`` or an Arith one."""
    companions = set(companion_operators())
    arith = {name for name in two_input_arithmetic()
             if operator_module(name) == "Arithmetic on two datasets"}
    assert companions | arith == set(two_input_arithmetic())
    assert not companions & arith


def test_every_companion_module_is_claimed_by_one_of_the_two_files():
    """The table is shared, so neither file may quietly stop covering part of it.

    ``_COMPANION_MODULES`` is keyed by module and spans two of our categories.
    This file parametrises over the arithmetic ones and
    ``test_comparison_category.py`` over the comparison ones; a module added to
    the table and to neither file would be a declaration nothing checks.
    """
    covered_here = {operator_module(name) for name in companion_operators()}
    covered_there = {
        module for module, category in
        [(operator_module(name), OPERATOR_SCHEMA[name].category)
         for name in OPERATOR_SCHEMA]
        if module in _COMPANION_MODULES
        and category is NCExplorerCategory.COMPARISON
    }
    assert covered_here | covered_there == set(_COMPANION_MODULES)


# --- (a) the infile2 contract ----------------------------------------------

@pytest.mark.parametrize("operator", companion_operators())
def test_help_text_names_the_companion_module_and_carries_the_example(operator):
    stat_module, example_operator, _, doc_operator, _purpose = \
        _COMPANION_MODULES[operator_module(operator)]
    description = OPERATOR_SCHEMA[operator].description

    assert stat_module in description
    # The doc's own example command, verbatim in shape.
    assert f"cdo {doc_operator} infile -{example_operator} infile outfile" \
        in description


@pytest.mark.parametrize("operator", companion_operators())
def test_the_second_input_slot_says_what_it_must_hold(operator):
    """``operator_inputs`` is what the model builder captions its slots from."""
    stat_module, example_operator, covers, _doc, _purpose = \
        _COMPANION_MODULES[operator_module(operator)]
    slots = OPERATOR_SCHEMA[operator].inputs

    assert len(slots) == 2
    assert stat_module in slots[1].role
    assert covers in slots[1].field
    assert slots[1].recipe == f"{example_operator} {{in1}}"


@pytest.mark.parametrize("operator", ["add", "sub", "mul", "div", "min", "max",
                                      "atan2", "setmiss"])
def test_the_arith_module_warns_about_broadcasting_instead(operator):
    """Arith's second input really is another dataset, so it gets Arith's caveat."""
    description = OPERATOR_SCHEMA[operator].description
    assert "single timestep or a single variable" in description
    assert "stdout" in description
    # And the doc's other warning, which is the one that silently produces
    # nonsense: cdo add tas.nc pr.nc exits 0 and calls the result "tas".
    assert "order of the variables nor the date is checked" in description


def test_every_surface_shows_the_same_help_text(qapp):
    """One fact, three surfaces. They used to read three different dictionaries."""
    from ncexplorer_toolkit.gui.command_palette import build_entries
    from ncexplorer_toolkit.gui.main_window import NCExplorerOperatorGUI

    entries = {entry.name: entry for entry in build_entries()}
    for operator in two_input_arithmetic():
        schema = OPERATOR_SCHEMA[operator].description       # model builder
        assert NCExplorerOperatorGUI.get_operator_description(operator) == schema
        assert entries[operator].help_text == schema


def test_an_alias_description_is_a_sentence():
    """``anomaly`` is "--> ymonsub" in the catalog, which two surfaces dropped."""
    description = OPERATOR_SCHEMA["anomaly"].description
    assert description.startswith("Another name for ymonsub.")
    assert "Ymonstat" in description


# --- (b) the notice CDO writes to stdout ------------------------------------

@pytest.mark.parametrize("line", [
    "cdo    add: Filling up stream2 >b.nc< by copying the first timestep.",
    "cdo    add: Filling up stream2 >b.nc< by copying the first variable of "
    "each timestep.",
])
def test_the_fill_notice_is_recognised(line):
    """Both forms, as CDO 2.6.0 writes them."""
    assert stream_notices(f"cdo add: Process started\n{line}\n") == [line]


def test_ordinary_output_is_not_a_notice():
    assert stream_notices("cdo add: Processed 1620 values in 0.01s\n") == []
    assert stream_notices("") == []
    assert stream_notices(None) == []


def test_a_repeated_notice_is_reported_once():
    line = "cdo add: Filling up stream2 >b.nc< by copying the first timestep."
    assert stream_notices(f"{line}\n{line}\n") == [line]


def test_the_operator_form_shows_the_notice(qapp, monkeypatch):
    """The toolbar form's console gets it marked, not buried in the bulk output."""
    from PyQt6.QtWidgets import QMessageBox

    from ncexplorer_toolkit import NCExplorerOperatorGUI
    from ncexplorer_toolkit.core.session_log import OperatorRequest

    monkeypatch.setattr(QMessageBox, "warning", staticmethod(lambda *a, **k: None))
    monkeypatch.setattr(QMessageBox, "critical", staticmethod(lambda *a, **k: None))
    window = NCExplorerOperatorGUI()
    try:
        notice = ("cdo add: Filling up stream2 >b.nc< by copying the first "
                  "timestep.")
        result = type("Result", (), {
            "success": True, "stdout": notice + "\n", "stderr": "",
            "execution_time": 0.1, "output_file": "",
        })()
        request = OperatorRequest(operator="add", input_files=("a.nc", "b.nc"),
                                  output_files=("o.nc",), parameters=(),
                                  nin=2, nout=1)

        window.output_console.clear()
        window.handle_operation_finished(request, result)
        console = window.output_console.toPlainText()

        # Marked as a warning and lifted above the bulk output. The name of the
        # engine is rewritten on its way to the console by ``redact_text``, so
        # the assertion is on the part of the line that carries the meaning.
        marked = [line for line in console.splitlines() if line.startswith("⚠️")]
        assert len(marked) == 1
        assert "Filling up stream2 >b.nc< by copying the first timestep." \
            in marked[0]
        assert console.index(marked[0]) < console.index("Output:")
    finally:
        window.close()
        window.deleteLater()


def test_the_batch_report_carries_the_notice():
    """A batch of two hundred files is where nobody reads two hundred stdouts."""
    job = BatchJob(index=1, source="a.nc")
    job.notices.append("add: Filling up stream2 >b.nc< by copying the first "
                       "timestep.")

    row = job.as_row(total_steps=1)
    assert row["message"] == ""          # not folded in until the job settles

    # _finish_job folds them in, and a real failure still wins the field.
    job.message = "" or "; ".join(job.notices)
    assert "Filling up stream2" in job.as_row(total_steps=1)["message"]


def test_a_failure_message_beats_a_notice():
    job = BatchJob(index=1, source="a.nc")
    job.notices.append("add: Filling up stream2 …")
    job.message = "add: Grid size differ" or "; ".join(job.notices)
    assert job.message == "add: Grid size differ"


# --- the model builder's one-click companion --------------------------------

def test_a_single_operator_recipe_is_offered_as_a_button():
    from ncexplorer_toolkit.gui.model_builder import _single_operator_recipe

    assert _single_operator_recipe("ymonavg {in1}") == ("ymonavg", ())

    # A parameterised single operator *is* offered now, and carries its
    # parameters with it. It used to be refused alongside the chains on the
    # grounds that wiring it would be a guess, which it is not: a CDO
    # comma-parameter belongs to the operator token, so there is nothing left to
    # guess at. The conditional-selection family needed this — the only
    # single-operator way to build a mask is a comparison against a constant.
    assert _single_operator_recipe("ydrunmin,5 {in1}") == ("ydrunmin", ("5",))
    assert _single_operator_recipe("gtc,0 {in1}") == ("gtc", ("0",))

    # A chain still is not: wiring it would mean guessing at three nodes.
    assert _single_operator_recipe(
        "ydrunpctl,90,5 {in1} -ydrunmin,5 {in1} -ydrunmax,5 {in1}") == ("", ())
    assert _single_operator_recipe("") == ("", ())
    # A comma with nothing after it would build a node with an empty required
    # field — the node the validator exists to complain about.
    assert _single_operator_recipe("gtc, {in1}") == ("", ())


def test_inserting_the_companion_branches_the_first_input(qapp, tmp_path,
                                                          monkeypatch):
    """``cdo ymonsub infile -ymonavg infile outfile``, drawn as a graph.

    Driven through the real ``insert_companion`` rather than through the graph,
    because re-implementing the wiring in the test would assert that the test
    can wire a graph rather than that the button does.
    """
    import itertools

    from PyQt6.QtWidgets import QMessageBox

    from ncexplorer_toolkit import NCExplorerOperatorGUI
    from ncexplorer_toolkit.core.model import OPERATOR, SOURCE
    from ncexplorer_toolkit.gui.model_builder import ModelBuilderWindow

    monkeypatch.setattr(QMessageBox, "warning", staticmethod(lambda *a, **k: None))
    source_path = tmp_path / "in.nc"
    source_path.write_bytes(b"CDF\x01")

    window = NCExplorerOperatorGUI()
    dock = ModelBuilderWindow(window)
    try:
        graph = dock.graph
        source = graph.add(SOURCE, path=str(source_path))
        node = graph.add(OPERATOR, operator="ymonsub")
        graph.connect(source.id, 0, node.id, 0)
        dock.canvas.rebuild()

        new_id = dock.insert_companion(node.id, "ymonavg")

        assert new_id, "nothing was inserted"
        assert graph.node(new_id).operator == "ymonavg"
        assert len(graph.incoming(node.id)) == 2
        # The same source feeds both branches — that is what makes it the doc's
        # example rather than two unrelated files.
        assert [c.source for c in graph.incoming(new_id)] == [source.id]
        assert not [issue for issue in graph.validate()
                    if issue.severity == ERROR]

        counter = itertools.count(1)
        commands = [request.command_line() for request in
                    graph.compile(lambda suffix: f"/tmp/i{next(counter)}{suffix}")]
        assert commands[0].startswith("cdo ymonavg ")
        assert commands[1].startswith("cdo ymonsub ")
        # The statistics file the first step writes is the second step's infile2.
        assert commands[0].split()[-1] == commands[1].split()[-2]
    finally:
        dock.close()
        dock.deleteLater()
        window.close()
        window.deleteLater()


def test_the_button_is_only_offered_when_it_can_be_wired(qapp, tmp_path):
    """No source upstream means nothing to branch, so nothing is inserted."""
    from PyQt6.QtWidgets import QMessageBox  # noqa: F401  (kept parallel)

    from ncexplorer_toolkit import NCExplorerOperatorGUI
    from ncexplorer_toolkit.core.model import OPERATOR
    from ncexplorer_toolkit.gui.model_builder import ModelBuilderWindow

    window = NCExplorerOperatorGUI()
    dock = ModelBuilderWindow(window)
    try:
        node = dock.graph.add(OPERATOR, operator="ymonsub")
        dock.canvas.rebuild()
        assert dock.insert_companion(node.id, "ymonavg") == ""
        # And nothing was left on the canvas.
        assert [n.operator for n in dock.graph.nodes
                if n.kind == OPERATOR] == ["ymonsub"]
    finally:
        dock.close()
        dock.deleteLater()
        window.close()
        window.deleteLater()
