"""The EOFs section says what it needs, what it returns, and when it failed.

Four problems, and the first one is not about the EOFs section at all.

**No surface above the execution layer could run a two-output operator.**
``parse_parameters`` built output rows for ``nout`` 1 and -1 only, ``execute``
refused anything else with "Unsupported operator signature", ``_output_paths``
returned exactly one path for every ``nout != 0``, ``_validate_node`` had no
branch for 2 so a broken graph reached CDO unchallenged, and ``plan_job`` mapped
every output of the keeper step onto the same destination — so a batched ``eof``
collided its eigenvalues and its eigenvectors on one path. That is eleven
operators, not six: ``trend``, ``mrotuv``, ``complextopol``, ``complextorect``
and ``samplegridicon`` were in the same hole, and they come out of it by the
same generic ``nout >= 2`` change. The tests below check ``trend`` beside ``eof``
wherever the claim is about the shape rather than about EOFs, because an
implementation that special-cased eof names would pass the eof half and fail
those.

**The input is assumed to be anomalies and nothing says so.** Measured on 2.6.3:
``cdo eof,3`` over a raw series exits 0, warns about nothing, and returns a
leading mode that is the climatological mean. There is no diagnostic
distinguishing that run from a correct one.

**eofcoeff's two inputs are the ``ifthen`` mask-swap trap in a new place**, and
worse. Both slots captioned "Input 1"/"Input 2"; the files are an eigenvector
file and an anomaly series with the same name, grid and units. Measured: the
right order wrote one file per eigenvector, the swap exited 0 and wrote one per
timestep of the series — 730 files from the same two inputs.

**A run that returns zeros was reported as a success.** The one-sided jacobi
solver can fail to converge, print "Setting Matrix and Eigenvalues to 0 before
return", exit 0, and write an all-zero file. Both warnings go to stderr, and
``stream_notices`` read stdout only, so no surface showed either. That is the
worst failure shape in the section: it looks exactly like a good run.

Everything asserted here was measured against the installed CDO 2.6.3, not read
off the documentation — which is wrong about the obase width, and is checked on
that point below. The tests marked ``cdo_required`` re-measure it.
"""

import os
import shutil
import subprocess

import pytest

from ncexplorer_toolkit.core.categories import (
    NCExplorerCategory, OPERATOR_SCHEMA, OperatorOutput,
    _EOFCOEFF_OPERATORS, _EOF_OPERATORS, _MODULE_CATEGORY,
    menu_operators, operator_env, operator_inputs, operator_module,
    operator_outputs,
)

cdo_required = pytest.mark.skipif(
    shutil.which("cdo") is None, reason="needs an installed CDO")


#: The CDO 2.6.3 EOFs section, module by module, exactly as the binary reports
#: it. Written out rather than derived from the schema, because a test that asks
#: the schema what the schema contains asserts nothing.
EOF_BY_MODULE = {
    "Empirical Orthogonal Functions": "eof eoftime eofspatial eof3d eof3dtime eof3dspatial",
    "Principal coefficients of EOFs": "eofcoeff eofcoeff3d",
}

EOF_SECTION = sorted(
    name for names in EOF_BY_MODULE.values() for name in names.split())

#: The six that decompose. All (1|2).
EOF = "eof eoftime eofspatial eof3d eof3dtime eof3dspatial".split()

#: The two that project onto an existing decomposition. Both (2|-1).
EOFCOEFF = "eofcoeff eofcoeff3d".split()

#: The sample every measurement in this file was taken against, and the
#: companions the operator lab builds beside it. Regenerated by
#: ``SampleSet.generate`` if absent; the seed is fixed, so the numbers below are
#: reproducible rather than incidental.
SAMPLES = "operator_test_output/_samples"
SERIES = f"{SAMPLES}/sample_climate_tg.nc"
ANOMALIES = f"{SAMPLES}/sample_climate_anomalies.nc"
EOFS = f"{SAMPLES}/sample_climate_eofs.nc"

#: Measured shapes of the sample: 730 daily timesteps, 36x18 = 648 gridpoints.
SERIES_STEPS = 730
GRID_POINTS = 648


def test_the_section_is_eight_operators():
    assert len(EOF_SECTION) == 8
    assert len(set(EOF_SECTION)) == 8


# --- (1) where they live ----------------------------------------------------

@pytest.mark.parametrize("operator", EOF_SECTION)
def test_every_eof_operator_is_filed_under_eof(operator):
    spec = OPERATOR_SCHEMA.get(operator)
    assert spec is not None, f"{operator} is not in the schema at all"
    assert spec.category is NCExplorerCategory.EOF


def test_the_eof_category_holds_nothing_else():
    """The category is exactly the section — no additions, no omissions."""
    filed = {name for name, spec in OPERATOR_SCHEMA.items()
             if spec.category is NCExplorerCategory.EOF}
    assert filed == set(EOF_SECTION)


def test_the_section_was_placed_by_module_and_not_by_prefix():
    """Naming the module is the fix; patching the cascade is the trap.

    A prefix branch would have been the easy change and is the one this file's
    predecessors were written to argue against — ``ymonsub`` and ``ymonmean``
    differ by three letters and belong to different sections. Here the evidence
    is direct: both module titles are in ``_MODULE_CATEGORY`` mapped to EOF, and
    that is the only mechanism that placed them.
    """
    for module in EOF_BY_MODULE:
        assert _MODULE_CATEGORY[module] is NCExplorerCategory.EOF


@pytest.mark.parametrize("module,names", sorted(EOF_BY_MODULE.items()))
def test_module_membership_matches_the_catalog(module, names):
    for name in names.split():
        assert operator_module(name) == module


def test_browsing_reaches_the_whole_section():
    """``menu_operators`` is what the menus are built from; nothing may be lost."""
    curated, rest = menu_operators(NCExplorerCategory.EOF)
    assert set(curated) | set(rest) == set(EOF_SECTION)


def test_the_category_has_an_icon():
    """``CATEGORY_ICONS`` is explicit and exhaustive by design.

    A category missing from it raises KeyError in ``category_icon()`` rather
    than rendering an empty button, so a new category has to bring one.
    """
    from ncexplorer_toolkit.resources.icons import CATEGORY_ICONS

    assert NCExplorerCategory.EOF in CATEGORY_ICONS
    name = CATEGORY_ICONS[NCExplorerCategory.EOF]
    from ncexplorer_toolkit.resources import icons as icons_module
    directory = os.path.join(os.path.dirname(icons_module.__file__), "icons")
    assert os.path.isfile(os.path.join(directory, name))


@cdo_required
@pytest.mark.parametrize("module", sorted(EOF_BY_MODULE))
def test_the_module_titles_still_agree_with_the_installed_binary(module):
    """The category hangs off two exact strings, so re-probe them.

    ``_MODULE_CATEGORY`` is keyed by the title ``cdo --help`` prints. A title
    that changed upstream would not raise — it would silently stop matching, and
    all eight operators would quietly go back to Miscellaneous.
    """
    operator = EOF_BY_MODULE[module].split()[0]
    out = subprocess.run(["cdo", "--help", operator], capture_output=True,
                         text=True, timeout=30)
    assert module in (out.stdout + out.stderr).replace("\n", " ")


# --- (2) the anomaly precondition -------------------------------------------

@pytest.mark.parametrize("operator", EOF)
def test_every_eof_description_states_the_anomaly_precondition(operator):
    """All six, because all six assume it and none of them checks it.

    Three of these operators (``eof3dtime``, ``eof3dspatial``, ``eofcoeff3d``)
    have *no* description in ``cdo --operators`` at all, so without this they
    reached the user as an empty string.
    """
    description = OPERATOR_SCHEMA[operator].description.lower()
    assert "anomalies" in description
    assert "does not check" in description
    # It must not be possible to read this and think CDO will object.
    assert "exits 0" in description


@pytest.mark.parametrize("operator", EOF)
def test_every_eof_description_names_the_two_step_recipe(operator):
    """The CDO manual's own two lines, which is what a user needs next."""
    description = OPERATOR_SCHEMA[operator].description
    assert "cdo sub infile -timmean infile anom_file" in description
    assert "cdo eof,40 anom_file eval_file eof_file" in description


@pytest.mark.parametrize("operator", EOF)
def test_every_eof_description_states_the_missing_value_limitation(operator):
    """From the manual, and flagged as the manual's claim rather than measured."""
    description = OPERATOR_SCHEMA[operator].description
    assert "masks that do not change over time" in description
    assert "replace missing values with 0" in description


@pytest.mark.parametrize("operator", EOF)
def test_the_single_input_slot_says_it_wants_anomalies(operator):
    """"Input 1" next to an operator whose whole subject is a precondition."""
    slots = operator_inputs(operator)
    assert len(slots) == 1
    assert "Anomalies" in slots[0].role
    assert slots[0].key == "anomalies"


# --- (3) what the two output files are --------------------------------------

@pytest.mark.parametrize("operator", EOF)
def test_the_output_slots_say_which_file_is_which(operator):
    slots = operator_outputs(operator)
    assert len(slots) == 2
    assert "Eigenvalues" in slots[0].role
    assert "EOFs" in slots[1].role


@pytest.mark.parametrize("operator", EOF)
def test_the_eigenvalue_file_says_neof_does_not_truncate_it(operator):
    """The measurement that surprises: ``eof,3`` wrote 648 timesteps to it.

    A user who asks for 3 EOFs and finds 648 timesteps in the first file has no
    way to tell whether they mis-typed the parameter.
    """
    spectrum = operator_outputs(operator)[0]
    assert "neof does NOT truncate this file" in spectrum.field
    assert "648" in spectrum.field
    # And on the parameter itself, which is where the number is typed.
    neof = OPERATOR_SCHEMA[operator].params[0]
    assert neof.name == "neof"
    assert "outfile2 only" in neof.help


@pytest.mark.parametrize("operator", EOF)
def test_the_eigenvalue_file_is_declared_undrawable(operator):
    """A 1x1 grid handed to the map canvas draws a single degenerate cell.

    The same trap ``reducegrid`` carries and states, and stated the same way:
    the canvas does not refuse the file, so the warning has to arrive first.
    """
    spectrum, eigenvectors = operator_outputs(operator)
    assert spectrum.drawable is False
    assert eigenvectors.drawable is True
    assert "not a map" in spectrum.field
    assert "plot or statistics panel" in spectrum.field


def test_trend_declares_its_two_outputs_too():
    """The operator that proves the metadata is not an eof special case.

    ``cdo --help trend`` on 2.6.3: "the estimation for a is stored in outfile1
    and that for b is stored in outfile2".
    """
    a, b = operator_outputs("trend")
    assert "intercept" in a.role
    assert "slope" in b.role
    assert a.suffix and b.suffix and a.suffix != b.suffix


@pytest.mark.parametrize("operator", ["timmean", "splitmon", "sinfo"])
def test_operators_that_declare_no_outputs_still_answer(operator):
    """The contract ``operator_inputs`` offers, on the output side.

    A caller indexes slots without asking whether the operator was declared, so
    the fallback has to exist — and has to keep the caption the form has always
    used for a single output.
    """
    spec = OPERATOR_SCHEMA[operator]
    slots = operator_outputs(operator)
    if spec.nout == 0:
        assert slots == ()
    else:
        assert len(slots) == (1 if spec.nout == -1 else spec.nout)
        assert all(slot.role for slot in slots)


# --- (4) eofcoeff's two inputs and the swap trap ----------------------------

@pytest.mark.parametrize("operator", EOFCOEFF)
def test_the_eofcoeff_slots_say_which_file_is_which(operator):
    """Generic "Input 1 / Input 2" is the dangerous kind of true here."""
    slots = operator_inputs(operator)
    assert len(slots) == 2
    assert "EOFs" in slots[0].role
    assert "eigenvector" in slots[0].role
    assert "Anomalies" in slots[1].role
    # The two files are compared directly, so their units have to agree — and
    # the check compares a slot against input 1, so it hangs off slot 1.
    assert slots[1].units == "same_as_input1"


@pytest.mark.parametrize("operator", EOFCOEFF)
def test_the_eofcoeff_slots_declare_no_recipe(operator):
    """The constraint stated rather than worked around.

    ``format_recipe`` builds a single-output command over ``{in1}``, and the
    command that builds slot 0 is ``cdo eof,<neof> {in1} evals eofs`` — two
    outputs, of which this slot wants the second. Nothing in a recipe string can
    say that, and the model builder's one-click companion would wire the new
    node's only port into this slot, silently connecting the *eigenvalues*.
    Slot 1's ``{in1}`` would have to name the raw series, which is not one of
    this operator's inputs, so ``recipe_source`` has no slot to point at.
    """
    for slot in operator_inputs(operator):
        assert slot.recipe == ""


@pytest.mark.parametrize("operator", EOFCOEFF)
def test_the_recipe_is_in_the_field_text_since_it_is_not_in_the_recipe(operator):
    """``ifthenc`` does the same: the command goes in the text it can fit in."""
    slots = operator_inputs(operator)
    assert "cdo eof,<neof> anomfile evalfile eoffile" in slots[0].field
    assert "cdo sub infile -timmean infile anomfile" in slots[1].field


@pytest.mark.parametrize("operator", EOFCOEFF)
def test_the_description_states_the_order_and_what_swapping_does(operator):
    description = OPERATOR_SCHEMA[operator].description
    assert "infile1 is the EOF file and infile2 is the anomaly series" in description
    assert "not the other way round" in description
    # The measured consequence, in numbers, because "wrong answer" understates
    # it: the swap writes one file per timestep of a 730-step series.
    assert "3 files against 730" in description
    assert "exited 0" in description


@pytest.mark.parametrize("operator", EOFCOEFF)
def test_the_description_states_the_five_digit_obase(operator):
    """The documentation says six digits and the installed binary writes five."""
    description = OPERATOR_SCHEMA[operator].description
    assert "five-digit" in description
    assert "pc00000.nc" in description
    # And says so *as* a correction, so nobody re-derives it from the manual.
    assert "documentation" in description


@pytest.mark.parametrize("operator", EOFCOEFF)
def test_the_description_carries_the_whole_recipe(operator):
    description = OPERATOR_SCHEMA[operator].description
    assert "cdo eofcoeff eofs anom pc" in description


# --- (5) the environment variables ------------------------------------------

@pytest.mark.parametrize("operator", EOF)
def test_the_four_solver_variables_are_declared(operator):
    declared = {variable.name for variable in operator_env(operator)}
    assert declared == {"CDO_WEIGHT_MODE", "CDO_SVD_MODE", "MAX_JACOBI_ITER",
                        "FNORM_PRECISION"}


@pytest.mark.parametrize("operator", EOFCOEFF)
def test_eofcoeff_declares_the_weight_mode_and_the_suffix(operator):
    declared = {variable.name for variable in operator_env(operator)}
    assert declared == {"CDO_WEIGHT_MODE", "CDO_FILE_SUFFIX"}


def test_the_weight_mode_default_is_the_measured_one():
    """``off``, and measured rather than read: unset and =off produced
    byte-identical eigenvalue files, unset and =on differed in all 648 fields.

    It matters because the Eofcoeff manual requires a non-weighted dot product,
    so "the default is off" is what makes the default safe.
    """
    weight = next(v for v in operator_env("eof") if v.name == "CDO_WEIGHT_MODE")
    assert weight.default == "off"
    assert weight.choices == ("off", "on")
    assert weight.kind == "select"


def test_the_solver_variable_warns_that_the_alternative_is_silent():
    """Measured: danielson_lanczos returns zeros with no warning at all.

    Switching solvers to escape a non-convergence warning escapes the warning
    and not the failure, and the help has to say so or it reads as a fix.
    """
    solver = next(v for v in operator_env("eof") if v.name == "CDO_SVD_MODE")
    assert "danielson_lanczos" in solver.choices
    assert "silently" in solver.help


def test_no_environment_variable_is_declared_as_a_parameter():
    """They are not arguments and must never reach the ``op,a,b`` token.

    ``params`` is positional — ``missing_required_parameters``,
    ``invalid_parameter_values`` and the GUI's own ``extra_args`` collection all
    index into it — so an env var in that tuple would shift every index after it
    while spelling ``eof,3,off`` at CDO, which is a syntax error.
    """
    for operator in EOF_SECTION:
        spec = OPERATOR_SCHEMA[operator]
        names = {param.name for param in spec.params}
        assert not names & {variable.name for variable in spec.env}
    assert [p.name for p in OPERATOR_SCHEMA["eof"].params] == ["neof"]
    assert OPERATOR_SCHEMA["eofcoeff"].params == ()


def test_operators_outside_the_section_declare_no_environment():
    """Declared per operator, so nothing is offered beside an operator it
    cannot reach."""
    for operator in ("timmean", "trend", "gtc", "ifthen", "timcor"):
        assert operator_env(operator) == ()


def test_the_request_renders_the_environment_as_a_shell_prefix():
    """``NAME=value cdo …`` — what a shell accepts and the manual's own form.

    An exported script that dropped the environment would run the same command
    line and compute different numbers, which is the whole reason it is recorded
    on the request rather than applied and forgotten.
    """
    from ncexplorer_toolkit.core.session_log import OperatorRequest

    request = OperatorRequest(
        operator="eof", input_files=("anom.nc",),
        output_files=("ev.nc", "eo.nc"), parameters=("3",), nin=1, nout=2,
        env=(("CDO_WEIGHT_MODE", "on"),))

    assert request.command_line() == \
        "CDO_WEIGHT_MODE=on cdo eof,3 anom.nc ev.nc eo.nc"
    assert request.environment() == {"CDO_WEIGHT_MODE": "on"}
    # And never in argv: these are not arguments.
    assert "CDO_WEIGHT_MODE=on" not in request.arguments()


def test_the_environment_survives_a_retarget():
    """``with_paths`` is what batching and replay retarget through."""
    from ncexplorer_toolkit.core.session_log import OperatorRequest

    request = OperatorRequest(
        operator="eof", input_files=("a.nc",), output_files=("x.nc", "y.nc"),
        parameters=("3",), nin=1, nout=2, env=(("CDO_WEIGHT_MODE", "on"),))
    moved = request.with_paths(["b.nc"], ["p.nc", "q.nc"])
    assert moved.env == (("CDO_WEIGHT_MODE", "on"),)


def test_a_blank_override_means_leave_cdo_alone():
    """CDO reads ``CDO_WEIGHT_MODE=`` as a value, not as "unset"."""
    from ncexplorer_toolkit.core.nc_integration import run_environment

    assert run_environment(None) is None
    assert run_environment({}) is None
    assert run_environment({"CDO_WEIGHT_MODE": ""}) is None
    assert run_environment({"CDO_WEIGHT_MODE": "   "}) is None

    built = run_environment({"CDO_WEIGHT_MODE": "on"})
    assert built is not None
    assert built["CDO_WEIGHT_MODE"] == "on"
    # Layered over the inherited environment, never replacing it: CDO needs
    # PATH to start at all, and the bundled macOS build needs DYLD_*.
    assert "PATH" in built


def test_the_cross_run_weight_mode_invariant_is_checked_in_the_graph():
    """The one invariant that spans two runs, checked where both runs exist.

    The Eofcoeff manual states that eofcoeff computes a non-weighted dot
    product, so ``CDO_WEIGHT_MODE`` has to agree across the eof run and the
    eofcoeff run. Set on one and not the other, both commands succeed and the
    coefficients are simply not the coefficients of those EOFs. The model
    builder is the only surface where both are objects at once.
    """
    from ncexplorer_toolkit.core.model import (
        ModelGraph, OPERATOR, SOURCE, WARNING)

    graph = ModelGraph()
    source = graph.add(SOURCE, path="/a.nc")
    eof = graph.add(OPERATOR, operator="eof", parameters=("3",),
                    env=(("CDO_WEIGHT_MODE", "on"),))
    coeff = graph.add(OPERATOR, operator="eofcoeff")
    graph.connect(source.id, 0, eof.id, 0)
    graph.connect(eof.id, 0, coeff.id, 0)
    graph.connect(source.id, 0, coeff.id, 1)

    complaints = [issue for issue in graph.validate()
                  if "CDO_WEIGHT_MODE" in issue.message]
    assert len(complaints) == 1
    assert complaints[0].severity == WARNING
    assert "non-weighted dot product" in complaints[0].message

    # Agreed: no complaint. Both explicitly on…
    graph.update_node(coeff.id, env=(("CDO_WEIGHT_MODE", "on"),))
    assert not [i for i in graph.validate() if "CDO_WEIGHT_MODE" in i.message]

    # …and one left unset against one explicitly off, since unset *is* off.
    # That is the measurement, and treating them as different would fire the
    # warning on the commonest correct graph in the section.
    graph.update_node(eof.id, env=())
    graph.update_node(coeff.id, env=(("CDO_WEIGHT_MODE", "off"),))
    assert not [i for i in graph.validate() if "CDO_WEIGHT_MODE" in i.message]


def test_the_environment_round_trips_through_a_saved_model():
    """A model saved with a weighting and reopened without it computes
    different numbers under the same command line."""
    from ncexplorer_toolkit.core.model import ModelNode, OPERATOR

    node = ModelNode(id="n1", kind=OPERATOR, operator="eof",
                     env=(("CDO_WEIGHT_MODE", "on"),))
    assert ModelNode.from_dict(node.to_dict()).env == \
        (("CDO_WEIGHT_MODE", "on"),)
    # A hand-edited project file is likeliest to hold an object; both shapes
    # load, and a half-filled row is dropped rather than re-shown as if set.
    assert ModelNode.from_dict({"id": "n", "kind": OPERATOR,
                                "env": {"CDO_SVD_MODE": "jacobi"}}).env == \
        (("CDO_SVD_MODE", "jacobi"),)
    assert ModelNode.from_dict({"id": "n", "kind": OPERATOR,
                                "env": [["CDO_SVD_MODE", ""]]}).env == ()


# --- (6) the zero return, and the notices that were being swallowed ---------

#: The three lines CDO printed on **stderr** for the run that returned zeros,
#: measured on 2.6.3 against the anomaly companion.
JACOBI_STDERR = (
    "jacobi_1side (Warning): Eigenvalue computation with one-sided jacobi "
    "scheme did not converge properly.\n"
    "                        209628 of 209628 pairs of columns did not achieve "
    "requested orthogonality of 1e-12\n"
    "cdo    eof (Warning): Setting Matrix and Eigenvalues to 0 before return\n"
)


def test_the_zero_return_reaches_the_user():
    """``stream_notices`` read stdout only, so none of this was shown anywhere."""
    from ncexplorer_toolkit.core.nc_integration import stream_notices

    notices = stream_notices("", JACOBI_STDERR)
    assert any("Setting Matrix and Eigenvalues to 0" in line for line in notices)
    assert any("did not converge" in line for line in notices)
    assert any("orthogonality" in line for line in notices)


def test_a_zero_return_is_a_failure_and_not_a_success_with_a_notice():
    """The mirror image of ``yseasgt``, and reported as the failure it is.

    yseasgt exits non-zero and leaves a header-only file; this exits 0 and
    writes a structurally perfect file containing nothing. Called a success, an
    all-zero decomposition flows onward — it draws as a blank map and eofcoeff
    projects onto it and writes plausible zero coefficients. Called a failure,
    the cost is one dismissable error on a run whose output was zeros anyway.
    """
    from ncexplorer_toolkit.core.nc_integration import stderr_indicates_failure

    assert stderr_indicates_failure(JACOBI_STDERR) is True


def test_non_convergence_alone_is_not_a_failure():
    """The distinction the patterns have to draw, and it is measured.

    On the *raw* sample the same solver reported 96653 of 209628 pairs
    unconverged and still returned real eigenvalues — leading value 48654900.
    Only the zeroing line means the file is empty, so warning and failure are
    two different sets.
    """
    from ncexplorer_toolkit.core.nc_integration import (
        stderr_indicates_failure, stream_notices)

    partial = ("jacobi_1side (Warning): Eigenvalue computation with one-sided "
               "jacobi scheme did not converge properly.\n"
               "                        96653 of 209628 pairs of columns did "
               "not achieve requested orthogonality of 1e-12\n")
    assert stderr_indicates_failure(partial) is False
    assert stream_notices("", partial), "the warning must still be shown"


def test_the_stderr_patterns_are_not_eof_specific():
    """Four more operators were in the same hole, and are fixed by the same net.

    Measured on 2.6.3 over the same sample: each exits 0, warns only on stderr,
    and writes a byte-for-byte copy of the input under the transformed name — so
    the only evidence no transformation happened was the swallowed warning.
    """
    from ncexplorer_toolkit.core.nc_integration import stream_notices

    for line in ("cdo    dv2uv (Warning): Divergence not found!",
                 "cdo    uv2dv (Warning): U-wind not found!",
                 "cdo    sp2gp (Warning): No spectral data found!",
                 "cdo    gp2sp (Warning): No data on regular Gaussian grid found!"):
        assert stream_notices("", line) == [line]


def test_the_stdout_notices_still_work_and_the_old_call_shape_still_compiles():
    """``stderr`` is optional, so every existing caller keeps working."""
    from ncexplorer_toolkit.core.nc_integration import stream_notices

    filling = "cdo    sub: Filling up stream2 >b.nc< by copying the first timestep."
    assert stream_notices(filling) == [filling]
    assert stream_notices(filling, None) == [filling]
    # And an ordinary run reports nothing, which is the common case.
    assert stream_notices("cdo sinfon: Processed 1 variable",
                          "cdo timmean: Processed 730 timesteps") == []


def test_all_three_reporting_surfaces_pass_stderr():
    """The shape was right — one shared function — so it was extended, not
    duplicated. This asserts none of the three was left behind."""
    import inspect

    from ncexplorer_toolkit.core import batch, model_runner
    from ncexplorer_toolkit.gui import main_window

    for module in (batch, model_runner, main_window):
        source = inspect.getsource(module)
        assert "stream_notices(result.stdout, result.stderr)" in source, \
            f"{module.__name__} still reads stdout only"


# --- (7) the generic nout >= 2 path -----------------------------------------

@pytest.mark.parametrize("operator", EOF + ["trend"])
def test_the_form_builds_one_output_row_per_output(operator):
    """``parse_parameters`` had no ``nout >= 2`` branch, so these drew none.

    ``trend`` is parametrised beside the six on purpose: an implementation that
    special-cased eof names would pass the eof half of this and fail here.
    """
    from ncexplorer_toolkit.gui.main_window import NCExplorerOperatorGUI

    rows = NCExplorerOperatorGUI.parse_parameters(operator, "")
    outputs = [row for row in rows
               if row[0] == "file" and row[1].startswith("Output")]
    assert len(outputs) == 2


@pytest.mark.parametrize("operator", EOF + ["trend"])
def test_the_output_rows_are_captioned_from_the_schema(operator):
    """Not "Output File 1"/"Output File 2".

    Those two rows are a spectrum on a 1x1 grid and a stack of maps on the data
    grid; a user who cannot tell which is which from the form has to run the
    operator to find out. The number stays because the *order* is what CDO
    reads.
    """
    from ncexplorer_toolkit.gui.main_window import NCExplorerOperatorGUI

    rows = NCExplorerOperatorGUI.parse_parameters(operator, "")
    captions = [row[1] for row in rows
                if row[0] == "file" and row[1].startswith("Output")]
    declared = operator_outputs(operator)
    assert captions == [f"Output {i + 1}: {slot.role}"
                        for i, slot in enumerate(declared)]


def test_the_form_and_the_executor_agree_about_the_output_labels():
    """A disagreement is a run refused for a field the user can see they filled.

    ``parse_parameters`` creates the row under a label and ``execute_operation``
    looks the widget up by it, so the two read one function.
    """
    from ncexplorer_toolkit.gui.main_window import (
        NCExplorerOperatorGUI, _output_field_label)

    for operator in EOF + ["trend"]:
        rows = NCExplorerOperatorGUI.parse_parameters(operator, "")
        captions = [row[1] for row in rows
                    if row[0] == "file" and row[1].startswith("Output")]
        assert captions == [_output_field_label(operator, i, 2)
                            for i in range(2)]


def test_the_form_offers_the_environment_as_ordinary_widget_kinds():
    """No new widget kind was invented: a select is a select.

    And the env rows are labelled apart from the parameter rows, which is what
    stops ``CDO_WEIGHT_MODE=off`` being collected into ``extra_args`` and spelled
    at CDO as ``eof,3,off``.
    """
    from ncexplorer_toolkit.gui.main_window import (
        ENV_LABEL_PREFIX, NCExplorerOperatorGUI)

    rows = NCExplorerOperatorGUI.parse_parameters("eof", "")
    env_rows = [row for row in rows if row[1].startswith(ENV_LABEL_PREFIX)]
    assert len(env_rows) == 4
    assert {row[0] for row in env_rows} <= {"select", "integer", "float", "string"}
    # The two selects carry a blank first choice: an untouched form must submit
    # nothing rather than pinning CDO's default as if it had been chosen.
    for row in env_rows:
        if row[0] == "select":
            assert row[3][0] == ""


@pytest.mark.parametrize("operator,expected", [
    ("eof", (1, 2)), ("trend", (1, 2)), ("eofcoeff", (2, -1)),
    ("timmean", (1, 1)), ("splitmon", (1, -1)), ("sinfo", (-1, 0)),
    ("mergetime", (-1, 1)),
])
def test_the_audit_reads_the_forms_arity_from_its_rows(operator, expected):
    """``audit_operator_surfaces.py`` is what gates all of this, so it has to
    be able to see a two-output form.

    It counts the rows ``parse_parameters`` emits — deliberately, so a fix is
    never compared against itself — and it counted them by matching the literal
    caption "Output File". Captioning the multi-output rows from the schema made
    that count zero, and the audit reported all seven (n|2) operators as
    disagreeing with the schema they had just been built from. The count is now
    "a file row captioned Output…", which is still the rows and no longer one
    exact spelling.
    """
    from ncexplorer_toolkit.gui.main_window import NCExplorerOperatorGUI
    from operator_lab.surfaces import _form_input_rows

    assert _form_input_rows(operator, NCExplorerOperatorGUI) == expected


def test_the_audit_does_not_count_environment_rows_as_outputs():
    """The rows the EOFs section adds are not files and must not be counted."""
    from ncexplorer_toolkit.gui.main_window import NCExplorerOperatorGUI
    from operator_lab.surfaces import _form_input_rows

    # eof has four env rows; if any were counted, nout would not be 2.
    assert _form_input_rows("eof", NCExplorerOperatorGUI)[1] == 2
    # eofcoeff has two env rows and a prefix, so nout is -1 regardless.
    assert _form_input_rows("eofcoeff", NCExplorerOperatorGUI)[1] == -1


@pytest.mark.parametrize("operator", ["eof", "trend"])
def test_the_builder_compiles_a_two_output_node_to_two_distinct_paths(operator):
    """``_output_paths`` returned exactly one path for every ``nout != 0``.

    Two outputs mapped onto one path is either "Outputfile already exists" or
    one file overwriting the other, and nothing said which.
    """
    import itertools

    from ncexplorer_toolkit.core.model import ModelGraph, OPERATOR, SOURCE

    graph = ModelGraph()
    source = graph.add(SOURCE, path="/data/in.nc")
    node = graph.add(OPERATOR, operator=operator,
                     parameters=("3",) if operator == "eof" else ())
    graph.connect(source.id, 0, node.id, 0)

    counter = itertools.count(1)
    requests = graph.compile(lambda suffix: f"/tmp/t{next(counter)}{suffix}")
    assert len(requests) == 1
    outputs = requests[0].output_files
    assert len(outputs) == 2
    assert outputs[0] != outputs[1]


@pytest.mark.parametrize("operator", ["eof", "trend"])
def test_a_wired_sink_names_the_first_output_and_the_sibling_follows_it(operator):
    """What a sink means for a node with two outputs, which had no answer.

    It names output 1, and the rest are written beside it using the schema's
    per-slot suffix — so both are files the user can find, in the folder they
    chose, and neither collides with the other.
    """
    import itertools

    from ncexplorer_toolkit.core.model import (
        ModelGraph, OPERATOR, SINK, SOURCE)

    graph = ModelGraph()
    source = graph.add(SOURCE, path="/data/in.nc")
    node = graph.add(OPERATOR, operator=operator,
                     parameters=("3",) if operator == "eof" else ())
    sink = graph.add(SINK, path="/data/result.nc")
    graph.connect(source.id, 0, node.id, 0)
    graph.connect(node.id, 0, sink.id, 0)

    counter = itertools.count(1)
    first, second = graph.compile(
        lambda suffix: f"/tmp/t{next(counter)}{suffix}")[0].output_files
    assert first == "/data/result.nc"
    assert second == f"/data/result{operator_outputs(operator)[1].suffix}.nc"


def test_the_builder_refuses_a_wire_out_of_a_two_output_node():
    """``_validate_node`` had branches for 0, 1 and -1 and none for 2.

    A wire out of such a node cannot say which file it carries — ports are
    numbered on the input side only — so ``compile`` would publish output 1
    downstream by a rule nobody was told about, and for every operator in this
    shape the interesting file is output 2.
    """
    from ncexplorer_toolkit.core.model import (
        ERROR, ModelGraph, OPERATOR, SOURCE)

    graph = ModelGraph()
    source = graph.add(SOURCE, path="/data/in.nc")
    node = graph.add(OPERATOR, operator="eof", parameters=("3",))
    downstream = graph.add(OPERATOR, operator="timmean")
    graph.connect(source.id, 0, node.id, 0)
    graph.connect(node.id, 0, downstream.id, 0)

    errors = [issue.message for issue in graph.validate()
              if issue.severity == ERROR and issue.node == node.id]
    assert any("writes 2 different files" in message for message in errors)
    # Phrased the way the nout == -1 refusal is phrased: what it produces, why
    # nothing can read it, and what to do instead.
    assert any("Disconnect what follows it" in message for message in errors)


def test_a_two_output_node_that_keeps_nothing_is_still_warned_about():
    """An ``eof`` node is the end of its branch by construction.

    Nothing downstream may read from it, so if no sink names its first output
    and ``keep_output`` is unset, both files go to scratch and the branch really
    does leave nothing behind — which is exactly what this warning is for.
    """
    from ncexplorer_toolkit.core.model import (
        ModelGraph, OPERATOR, SOURCE, WARNING)

    graph = ModelGraph()
    source = graph.add(SOURCE, path="/data/in.nc")
    node = graph.add(OPERATOR, operator="eof", parameters=("3",))
    graph.connect(source.id, 0, node.id, 0)

    assert any(issue.severity == WARNING and "leaves no file behind" in issue.message
               for issue in graph.validate())


def test_a_batched_two_output_step_does_not_collide_on_the_destination():
    """``plan_job`` mapped *every* output of the keeper step to ``destination``.

    Right for the (n|1) shape every pipeline had when it was written, and
    silently wrong for the eleven (n|2) operators: an ``eof`` keeper sent both
    files to one path, so every job in the batch collided. Nothing said so — the
    job reported the failure of a step whose command line looked right.
    """
    import itertools

    from ncexplorer_toolkit.core.batch import plan_job
    from ncexplorer_toolkit.core.session_log import OperatorRequest

    counter = itertools.count(1)
    pipeline = [OperatorRequest(
        operator="eof", input_files=("/a/in.nc",),
        output_files=("/a/ev.nc", "/a/eofs.nc"), parameters=("3",),
        nin=1, nout=2)]

    planned = plan_job(pipeline, "/src/x.nc", "/out/x_eof.nc",
                       lambda suffix: f"/tmp/s{next(counter)}{suffix}")
    first, second = planned[0].output_files
    assert first == "/out/x_eof.nc"
    assert second == "/out/x_eof_eofs.nc"
    assert first != second


def test_a_batched_single_output_step_is_unchanged():
    """The (n|1) shape is what every existing pipeline is, and it must not move."""
    import itertools

    from ncexplorer_toolkit.core.batch import plan_job
    from ncexplorer_toolkit.core.session_log import OperatorRequest

    counter = itertools.count(1)
    pipeline = [OperatorRequest(
        operator="timmean", input_files=("/a/in.nc",),
        output_files=("/a/m.nc",), nin=1, nout=1)]
    planned = plan_job(pipeline, "/src/x.nc", "/out/x_mean.nc",
                       lambda suffix: f"/tmp/s{next(counter)}{suffix}")
    assert planned[0].output_files == ("/out/x_mean.nc",)


def test_the_request_emits_two_outputs_in_order():
    """``OperatorRequest.arguments`` already did this and needed nothing.

    Recorded as a test rather than as a comment because "needed no change" is
    only trustworthy if something checks it.
    """
    from ncexplorer_toolkit.core.session_log import OperatorRequest

    request = OperatorRequest(
        operator="eof", input_files=("anom.nc",),
        output_files=("ev.nc", "eo.nc"), parameters=("3",), nin=1, nout=2)
    assert request.arguments() == ["eof,3", "anom.nc", "ev.nc", "eo.nc"]
    assert request.command_line() == "cdo eof,3 anom.nc ev.nc eo.nc"


# --- (8) the operator lab ---------------------------------------------------

def test_eofspatial_is_no_longer_excused():
    """The entry was measurably wrong; see the profile comment for the numbers.

    It read "superseded by eof/eoftime", and on 2.6.3 the operator runs and
    returns byte-identical output to ``cdo eof``. What the note measured was the
    *arity* — given one output file it aborts with "Missing inputs", which is a
    statement about how it was called.
    """
    from operator_lab.profiles import UNTESTABLE

    assert "eofspatial" not in UNTESTABLE


def test_eof3dspatial_is_excused_for_the_reason_the_binary_gives():
    from operator_lab.profiles import UNTESTABLE

    assert "eof3dspatial" in UNTESTABLE
    assert "Operator not Implemented - use eof3d or eof3dtime instead" in \
        UNTESTABLE["eof3dspatial"]


def test_no_other_eof_operator_is_excused():
    from operator_lab.profiles import UNTESTABLE

    assert {name for name in EOF_SECTION if name in UNTESTABLE} == {"eof3dspatial"}


# --- the claims above, re-measured against the installed binary -------------

@pytest.fixture(scope="module")
def samples(tmp_path_factory):
    """The generated sample set, built if it is not already there.

    Deterministic: one fixed seed and one fixed recipe, so the exact numbers
    asserted below are reproducible rather than incidental.
    """
    from pathlib import Path

    from operator_lab.samples import SampleSet

    directory = Path(SAMPLES)
    if not (directory / "sample_climate_tg.nc").is_file():
        directory.mkdir(parents=True, exist_ok=True)
        SampleSet.generate(directory, "cdo", reuse=True)
    return {
        "series": str(directory / "sample_climate_tg.nc"),
        "anomalies": str(directory / "sample_climate_anomalies.nc"),
        "eofs": str(directory / "sample_climate_eofs.nc"),
    }


@cdo_required
def test_the_sample_is_the_one_these_numbers_were_measured_against(samples):
    """730 timesteps over 648 gridpoints. Every count below depends on both."""
    out = subprocess.run(["cdo", "-s", "sinfon", samples["series"]],
                         capture_output=True, text=True, timeout=120)
    assert f"points={GRID_POINTS}" in out.stdout
    assert f"time : {SERIES_STEPS} steps" in out.stdout


@cdo_required
def test_eof_writes_two_files_with_the_measured_shapes(samples, tmp_path):
    """outfile1 is the whole spectrum on a 1x1 grid; outfile2 is neof maps.

    The claim ``neof`` sizes outfile2 only, measured rather than asserted: 2 was
    asked for and 648 eigenvalues came back.
    """
    spectrum = tmp_path / "ev.nc"
    eigenvectors = tmp_path / "eo.nc"
    out = subprocess.run(
        ["cdo", "eof,2", samples["series"], str(spectrum), str(eigenvectors)],
        capture_output=True, text=True, timeout=300)
    assert out.returncode == 0, out.stderr

    def ntime(path):
        result = subprocess.run(["cdo", "-s", "ntime", str(path)],
                                capture_output=True, text=True, timeout=120)
        return int(result.stdout.strip())

    assert ntime(spectrum) == GRID_POINTS
    assert ntime(eigenvectors) == 2

    grid = subprocess.run(["cdo", "-s", "griddes", str(spectrum)],
                          capture_output=True, text=True, timeout=120)
    assert "gridsize  = 1" in grid.stdout
    data_grid = subprocess.run(["cdo", "-s", "griddes", str(eigenvectors)],
                               capture_output=True, text=True, timeout=120)
    assert f"gridsize  = {GRID_POINTS}" in data_grid.stdout


@cdo_required
def test_cdo_does_not_object_to_a_raw_series(samples, tmp_path):
    """The precondition every eof description states, measured.

    If this ever starts failing, CDO has learned to check — and six descriptions
    can drop the warning. That is a deliberate act, which is the point of
    failing here rather than going on warning about something fixed upstream.
    """
    out = subprocess.run(
        ["cdo", "eof,2", samples["series"], str(tmp_path / "a.nc"),
         str(tmp_path / "b.nc")], capture_output=True, text=True, timeout=300)
    assert out.returncode == 0
    combined = out.stdout + out.stderr
    assert "anomal" not in combined.lower(), \
        "CDO now says something about anomalies; re-read the descriptions"


@cdo_required
def test_the_zero_return_really_happens_and_is_caught(tmp_path):
    """The worst failure in the section, re-measured end to end.

    Exit 0, a well-formed file, an all-zero spectrum, and the only evidence on
    stderr. This is what ``stderr_indicates_failure`` exists for, so the
    measurement and the check are asserted together.

    The degenerate input is built **here** rather than taken from the shared
    sample set, and that is the point of this version of the test. It used to
    read ``samples["anomalies"]`` and pass — because the generated series was
    ``-duplicate,730`` of a single random field and so had no variation over
    time at all, which made its anomalies identically zero. The test was
    therefore asserting that CDO fails to decompose a zero matrix while
    appearing to measure something about the solver, and it went green for the
    wrong reason for as long as the sample was broken.

    So the zero matrix is now constructed on purpose, by the same route that
    produced it accidentally, and the shared sample is asserted to be *unlike*
    it in the test below.
    """
    from ncexplorer_toolkit.core.nc_integration import (
        stderr_indicates_failure, stream_notices)

    # A series with spatial variation and none over time: one random field
    # repeated. Its anomalies are exactly zero, by construction.
    constant = tmp_path / "constant.nc"
    subprocess.run(
        ["cdo", "-f", "nc", "-settaxis,2000-01-01,00:00:00,1day",
         "-duplicate,120", "-random,r36x18,1", str(constant)],
        capture_output=True, text=True, timeout=300, check=True)
    anomalies = tmp_path / "anom.nc"
    subprocess.run(
        ["cdo", "sub", str(constant), "-timmean", str(constant), str(anomalies)],
        capture_output=True, text=True, timeout=300, check=True)

    spectrum = tmp_path / "ev.nc"
    out = subprocess.run(
        ["cdo", "eof,2", str(anomalies), str(spectrum), str(tmp_path / "eo.nc")],
        capture_output=True, text=True, timeout=300)

    assert out.returncode == 0, "the trap is that this exits 0"
    assert "Setting Matrix and Eigenvalues to 0 before return" in out.stderr
    assert "Setting Matrix and Eigenvalues to 0" not in out.stdout, \
        "it moved to stdout; the notice patterns can be narrowed"

    maximum = subprocess.run(
        ["cdo", "-s", "output", "-timmax", "-abs", str(spectrum)],
        capture_output=True, text=True, timeout=120)
    assert float(maximum.stdout.strip()) == 0.0

    # And the app calls it what it is.
    assert stderr_indicates_failure(out.stderr) is True
    assert stream_notices(out.stdout, out.stderr)


@cdo_required
def test_the_generated_sample_actually_decomposes(samples, tmp_path):
    """The sample varies over time, so ``eof`` over its anomalies is real work.

    The guard on the bug the test above used to hide. Two claims, because
    either one alone can be satisfied by a broken sample: the anomalies are not
    all zero, and the decomposition of them does not zero itself out.
    """
    spread = subprocess.run(
        ["cdo", "-s", "output", "-timmax", "-abs", samples["anomalies"]],
        capture_output=True, text=True, timeout=120)
    assert float(spread.stdout.split()[0]) > 0.0, \
        "the anomaly companion is identically zero — the series has no " \
        "variation over time, so there is nothing for eof to decompose"

    out = subprocess.run(
        ["cdo", "eof,2", samples["anomalies"], str(tmp_path / "ev.nc"),
         str(tmp_path / "eo.nc")], capture_output=True, text=True, timeout=300)
    assert out.returncode == 0
    assert "Setting Matrix and Eigenvalues to 0 before return" not in out.stderr
    maximum = subprocess.run(
        ["cdo", "-s", "output", "-timmax", "-abs", str(tmp_path / "ev.nc")],
        capture_output=True, text=True, timeout=120)
    assert float(maximum.stdout.strip()) > 0.0


@cdo_required
def test_eofcoeff_writes_five_digits_not_the_documented_six(samples, tmp_path):
    """The documentation says ``obase000000`` and the binary writes ``pc00000``.

    Asserted as a width rather than as a filename so it fails loudly if CDO ever
    adopts its own documentation, which is the version of this that has to be
    noticed.
    """
    obase = tmp_path / "pc"
    out = subprocess.run(
        ["cdo", "eofcoeff", samples["eofs"], samples["anomalies"], str(obase)],
        capture_output=True, text=True, timeout=300)
    assert out.returncode == 0, out.stderr

    written = sorted(p.name for p in tmp_path.iterdir() if p.name.startswith("pc"))
    assert written, "eofcoeff wrote nothing"
    for name in written:
        digits = name[len("pc"):-len(".nc")]
        assert digits.isdigit()
        assert len(digits) == 5, (
            f"{name} has {len(digits)} digits; the CDO documentation claims 6 "
            f"and 2.6.3 was measured at 5")
    assert written[0] == "pc00000.nc"


@cdo_required
def test_eofcoeff_writes_one_file_per_timestep_of_infile1(samples, tmp_path):
    """Which is what makes the argument order matter so much."""
    def ntime(path):
        result = subprocess.run(["cdo", "-s", "ntime", str(path)],
                                capture_output=True, text=True, timeout=120)
        return int(result.stdout.strip())

    obase = tmp_path / "pc"
    subprocess.run(
        ["cdo", "eofcoeff", samples["eofs"], samples["anomalies"], str(obase)],
        capture_output=True, text=True, timeout=300, check=True)

    written = [p for p in tmp_path.iterdir() if p.name.startswith("pc")]
    assert len(written) == ntime(samples["eofs"])


@cdo_required
def test_the_swap_is_guarding_something_real(samples, tmp_path):
    """730 files rather than a wrong-looking one, and exit 0 either way.

    This is why the slot captions and the description matter more here than for
    ``ifthen``: the mistake is not a bad answer, it is a full disk.
    """
    obase = tmp_path / "bad"
    out = subprocess.run(
        ["cdo", "eofcoeff", samples["anomalies"], samples["eofs"], str(obase)],
        capture_output=True, text=True, timeout=600)

    assert out.returncode == 0, "the trap is that the swap does not fail"
    written = [p for p in tmp_path.iterdir() if p.name.startswith("bad")]
    assert len(written) == SERIES_STEPS


@cdo_required
def test_eofspatial_runs_and_agrees_with_eof_on_this_sample(samples, tmp_path):
    """The measurement that retired the UNTESTABLE entry.

    ``eof`` picks the cheaper of the two algorithms and does not say which; on
    this sample the grid (648) is smaller than the time axis (730), so it takes
    the spatial path. Identical output is what makes "eofspatial works" a claim
    rather than "it did not crash".
    """
    plain = (tmp_path / "e1.nc", tmp_path / "e2.nc")
    spatial = (tmp_path / "s1.nc", tmp_path / "s2.nc")
    for operator, targets in (("eof,2", plain), ("eofspatial,2", spatial)):
        out = subprocess.run(
            ["cdo", operator, samples["series"], str(targets[0]), str(targets[1])],
            capture_output=True, text=True, timeout=300)
        assert out.returncode == 0, f"{operator}: {out.stderr}"

    for left, right in zip(plain, spatial):
        diff = subprocess.run(["cdo", "-s", "diffn", str(left), str(right)],
                              capture_output=True, text=True, timeout=300)
        assert diff.stdout.strip() == "", diff.stdout


@cdo_required
def test_eof3dspatial_still_aborts_with_the_message_the_profile_claims(tmp_path):
    """A version-specific excuse outliving its version is a lie with a date."""
    from operator_lab.profiles import UNTESTABLE

    levels = tmp_path / "levels.nc"
    subprocess.run(
        ["cdo", "-f", "nc", "-settaxis,2000-01-01,12:00,1day",
         "-duplicate,6", "-random,r18x9,3", str(levels)],
        capture_output=True, timeout=300, check=True)

    out = subprocess.run(
        ["cdo", "eof3dspatial,2", str(levels), str(tmp_path / "a.nc"),
         str(tmp_path / "b.nc")], capture_output=True, text=True, timeout=300)

    assert out.returncode != 0
    assert "Operator not Implemented - use eof3d or eof3dtime instead" in out.stderr
    # The profile quotes the binary, so the two cannot drift.
    assert "Operator not Implemented - use eof3d or eof3dtime instead" in \
        UNTESTABLE["eof3dspatial"]


@cdo_required
def test_the_weight_mode_default_is_off_measured_not_read(samples, tmp_path):
    """Unset == off, and both differ from on. The basis of the whole env entry.

    Three runs and two ``diffn``s, because "the default is off" is the claim the
    cross-run invariant and the eofcoeff advice both rest on.
    """
    def run(env_value, stem):
        first, second = tmp_path / f"{stem}1.nc", tmp_path / f"{stem}2.nc"
        environment = dict(os.environ)
        if env_value is not None:
            environment["CDO_WEIGHT_MODE"] = env_value
        else:
            environment.pop("CDO_WEIGHT_MODE", None)
        out = subprocess.run(
            ["cdo", "eof,2", samples["series"], str(first), str(second)],
            capture_output=True, text=True, timeout=300, env=environment)
        assert out.returncode == 0, out.stderr
        return first

    unset, off, on = run(None, "u"), run("off", "f"), run("on", "n")

    def differing(left, right):
        out = subprocess.run(["cdo", "-s", "diffn", str(left), str(right)],
                             capture_output=True, text=True, timeout=300)
        return out.stdout.strip()

    assert differing(unset, off) == "", "unset is no longer the same as off"
    assert differing(unset, on) != "", "on no longer changes the answer"
