# Copyright (c) 2026 Manish Shivach
# SPDX-License-Identifier: MIT
"""The Comparison section is what CDO says it is, and says what it returns.

Three separate problems, all in the same four modules.

**Where they live.** CDO's Comparison section is four modules and twenty-four
operators. Twelve of them were filed under Statistical values: ``_MODULE_CATEGORY``
named no comparison module, so ``_infer_category`` fell through to the prefix
cascade, where the ("ymon","yseas") branch is tested before any comparison name
and cannot tell ``ymoneq`` from ``ymonmean``. This is the trap that cost the
Arithmetic section thirty-two operators, in the same place, fixed the same way:
name the module, do not patch the cascade.

**What they return.** ``eq``'s description was "Equal." and ``gtc``'s was
"Greater than constant." Neither said the output is a 0/1 mask, and neither said
what happens to missing values — which is the whole content of the formula CDO
prints for each of them, and exactly what distinguishes ``gtc,273.15`` from the
``expr`` a user might write instead. ``expr`` returns 0 where the input is
missing; ``gtc`` returns missing.

**What the second file is.** Ymoncomp and Yseascomp take a *statistics* file as
infile2, not a second series — "Usually infile2 is generated by an operator of
the module Ymonstat" — the same sentence the seven ``*arith`` modules carry, and
the same silent-wrong-answer if it is ignored.

Everything asserted here was measured against the installed CDO 2.6.0, not read
off the documentation; the tests marked ``cdo_required`` re-measure it.
"""

import shutil
import subprocess

import pytest

from ncexplorer_toolkit.core.categories import (
    COMPARISON_OPERATORS, NCExplorerCategory, OPERATOR_CATEGORIES,
    OPERATOR_SCHEMA, _COMPANION_MODULES, _YSEASCOMP_BROKEN_IN,
    menu_operators, operator_inputs, operator_module,
)

cdo_required = pytest.mark.skipif(
    shutil.which("cdo") is None, reason="needs an installed CDO")


#: The CDO 2.6.0 Comparison section, module by module, exactly as the binary
#: reports it. Written out rather than derived from the schema, because a test
#: that asks the schema what the schema contains asserts nothing.
COMPARISON_BY_MODULE = {
    "Comparison of two fields":              "eq ne le lt ge gt",
    "Comparison of a field with a constant": "eqc nec lec ltc gec gtc",
    "Multi-year monthly comparison":         "ymoneq ymonne ymonle ymonlt ymonge ymongt",
    "Multi-year seasonal comparison":        "yseaseq yseasne yseasle yseaslt yseasge yseasgt",
}

COMPARISON = sorted(
    name for names in COMPARISON_BY_MODULE.values() for name in names.split()
)

#: The two modules whose infile2 is a statistics file rather than a series.
COMPANION_COMPARISON = sorted(
    "ymoneq ymonne ymonle ymonlt ymonge ymongt "
    "yseaseq yseasne yseasle yseaslt yseasge yseasgt".split()
)

#: The two-input module that broadcasts. Compc takes one file and the ymon/yseas
#: modules pair fields by month or season, so neither broadcasts.
COMP = "eq ne le lt ge gt".split()

COMPC = "eqc nec lec ltc gec gtc".split()

#: Broken on CDO 2.6.0 — see ``_YSEASCOMP_ABORTS`` in core/categories.py.
YSEASCOMP = "yseaseq yseasne yseasle yseaslt yseasge yseasgt".split()


def test_the_section_is_twenty_four_operators():
    assert len(COMPARISON) == 24
    assert len(set(COMPARISON)) == 24


# --- (1) where they live ----------------------------------------------------

@pytest.mark.parametrize("operator", COMPARISON)
def test_every_comparison_operator_is_filed_under_comparison(operator):
    spec = OPERATOR_SCHEMA.get(operator)
    assert spec is not None, f"{operator} is not in the schema at all"
    assert spec.category is NCExplorerCategory.COMPARISON


def test_comparison_holds_nothing_else():
    """The category is exactly the section — no additions, no omissions."""
    filed = {name for name, spec in OPERATOR_SCHEMA.items()
             if spec.category is NCExplorerCategory.COMPARISON}
    assert filed == set(COMPARISON)


def test_the_two_tables_cannot_disagree():
    """There is one list of the twenty-four, and both tables are built from it.

    The curated menu list held twelve names and a second copy lived inside
    ``_infer_category`` holding fourteen — the twelve plus ``maxc``/``minc``.
    Two lists of one thing disagree eventually, and those two already had.
    """
    assert sorted(COMPARISON_OPERATORS) == COMPARISON
    assert OPERATOR_CATEGORIES[NCExplorerCategory.COMPARISON] == \
        list(COMPARISON_OPERATORS)


@pytest.mark.parametrize("operator", ["maxc", "minc"])
def test_maxc_and_minc_are_arithmetic_in_both_tables(operator):
    """They read like comparisons; CDO files them under Arithc.

    ``maxc`` returns a *value*, the twenty-four return a 0/1 mask, and that is
    the distinction worth keeping. The name set that used to claim them for
    Comparison could never have placed them — the module lookup ran first and
    returned Arithmetic — so the two tables disagreed on paper about an operator
    neither of them decided.
    """
    assert OPERATOR_SCHEMA[operator].category is NCExplorerCategory.ARITHMETIC
    assert operator not in COMPARISON_OPERATORS
    assert operator_module(operator) == "Arithmetic with a constant"


def test_browsing_reaches_the_whole_section():
    """``menu_operators`` is what the menus are built from; nothing may be lost."""
    curated, rest = menu_operators(NCExplorerCategory.COMPARISON)
    assert set(curated) | set(rest) == set(COMPARISON)


@pytest.mark.parametrize("module,names", sorted(COMPARISON_BY_MODULE.items()))
def test_module_membership_matches_the_catalog(module, names):
    for name in names.split():
        assert operator_module(name) == module


@cdo_required
@pytest.mark.parametrize("module", sorted(COMPARISON_BY_MODULE))
def test_the_module_titles_still_agree_with_the_installed_binary(module):
    """The category hangs off four exact strings, so re-probe them.

    ``_MODULE_CATEGORY`` is keyed by the title ``cdo --help`` prints. A title
    that changed upstream would not raise — it would silently stop matching, and
    twelve operators would quietly go back to Statistical values. The catalog
    these titles are read from is generated, and a generated file nobody
    re-checks is a hand-written file with extra steps.
    """
    operator = COMPARISON_BY_MODULE[module].split()[0]
    out = subprocess.run(["cdo", "--help", operator], capture_output=True,
                         text=True, timeout=30)
    assert module in (out.stdout + out.stderr).replace("\n", " ")


# --- (2) what they return ---------------------------------------------------

@pytest.mark.parametrize("operator", COMPARISON)
def test_every_description_states_the_mask_and_the_missing_value_rule(operator):
    """Both halves, for all twenty-four — the mask is useless without the second.

    A user who believes missing becomes 0 will sum the mask and get a count of
    "cells where the comparison failed" that silently includes every cell where
    it could not be asked.
    """
    description = OPERATOR_SCHEMA[operator].description.lower()
    assert "mask" in description
    assert "1 where the comparison holds" in description
    assert "0 where it does not" in description
    # The missing-value branch, in whatever words: it must not be possible to
    # read this description and think missing becomes zero.
    assert "missing" in description
    assert "missing rather than 0" in description


@pytest.mark.parametrize("operator", COMP)
def test_the_comp_module_warns_about_broadcasting(operator):
    """Comp documents the broadcast rule in the same words Arith does.

    The note was gated on ``_MODULE_CATEGORY[module] is ARITHMETIC``, which
    asked whether the operator was arithmetic rather than whether its module
    broadcasts, so these six never showed it.
    """
    description = OPERATOR_SCHEMA[operator].description
    assert "only a single timestep or a single variable" in description
    # The other half of Comp's sentence, which Arith's help does not carry.
    assert "inherits its metadata from infile1 or infile2" in description


@pytest.mark.parametrize("operator", COMPC + COMPANION_COMPARISON)
def test_operators_that_do_not_broadcast_do_not_claim_to(operator):
    """Compc takes one file; ymon/yseas pair fields by month or season."""
    assert "only a single timestep or a single variable" not in \
        OPERATOR_SCHEMA[operator].description


# --- (3) what the second file is -------------------------------------------

@pytest.mark.parametrize("operator", COMPANION_COMPARISON)
def test_the_second_input_slot_says_what_it_must_hold(operator):
    """``operator_inputs`` is what the model builder captions its slots from.

    Generic "Input 1 / Input 2" is the dangerous kind of true here: two raw
    series into ``ymoneq`` do not fail, they compare the wrong fields.
    """
    stat_module, example_operator, covers, _doc, _purpose = \
        _COMPANION_MODULES[operator_module(operator)]
    slots = operator_inputs(operator)

    assert len(slots) == 2
    assert slots[0].role == "Time series"
    assert stat_module in slots[1].role
    assert covers in slots[1].field
    assert slots[1].recipe == f"{example_operator} {{in1}}"
    # The two files are compared directly, so their units have to agree.
    assert slots[1].units == "same_as_input1"


@pytest.mark.parametrize("operator", COMPANION_COMPARISON)
def test_the_description_names_the_companion_module_and_the_example(operator):
    stat_module, example_operator, _covers, doc_operator, _purpose = \
        _COMPANION_MODULES[operator_module(operator)]
    description = OPERATOR_SCHEMA[operator].description

    assert stat_module in description
    assert f"cdo {doc_operator} infile -{example_operator} infile outfile" \
        in description


@pytest.mark.parametrize("operator", COMPANION_COMPARISON)
def test_the_companion_recipe_is_one_the_builder_can_wire(operator):
    """A single operator over input 1 is what earns the one-click button.

    The button already existed for ``ymonsub``; declaring the recipe is the
    whole of what these twelve needed to get it. See
    ``test_two_input_arithmetic.py`` for the insertion itself.
    """
    from ncexplorer_toolkit.gui.model_builder import _single_operator_recipe

    slots = operator_inputs(operator)
    expected = "ymonavg" if operator.startswith("ymon") else "yseasavg"
    # ``(operator, parameters)`` since the parser learned to carry parameters
    # for the conditional family; these twelve recipes take none.
    assert _single_operator_recipe(slots[1].recipe) == (expected, ())


def test_the_builder_can_actually_build_the_companion(qapp, tmp_path,
                                                      monkeypatch):
    """``cdo ymoneq infile -ymonavg infile outfile``, drawn as a graph.

    The one-click companion was built for the ``*arith`` operators and is
    entirely generic — it reads ``slot.recipe`` and asks
    ``_single_operator_recipe`` whether it is one operator over input 1. So
    declaring the recipe is the whole of what the twelve comparison operators
    needed; this asserts that rather than assuming it, driven through the real
    ``insert_companion`` so it is the button being tested and not the test's own
    idea of how to wire a graph.
    """
    import itertools

    from PyQt6.QtWidgets import QMessageBox

    from ncexplorer_toolkit import NCExplorerOperatorGUI
    from ncexplorer_toolkit.core.model import ERROR, OPERATOR, SOURCE
    from ncexplorer_toolkit.gui.model_builder import ModelBuilderWindow

    monkeypatch.setattr(QMessageBox, "warning", staticmethod(lambda *a, **k: None))
    source_path = tmp_path / "in.nc"
    source_path.write_bytes(b"CDF\x01")

    window = NCExplorerOperatorGUI()
    dock = ModelBuilderWindow(window)
    try:
        graph = dock.graph
        source = graph.add(SOURCE, path=str(source_path))
        node = graph.add(OPERATOR, operator="ymoneq")
        graph.connect(source.id, 0, node.id, 0)
        dock.canvas.rebuild()

        new_id = dock.insert_companion(node.id, "ymonavg")

        assert new_id, "nothing was inserted"
        assert graph.node(new_id).operator == "ymonavg"
        assert len(graph.incoming(node.id)) == 2
        # One source feeding both branches is what makes this the documented
        # idiom rather than two unrelated files.
        assert [c.source for c in graph.incoming(new_id)] == [source.id]
        assert not [issue for issue in graph.validate()
                    if issue.severity == ERROR]

        counter = itertools.count(1)
        commands = [request.command_line() for request in
                    graph.compile(lambda suffix: f"/tmp/i{next(counter)}{suffix}")]
        assert commands[0].startswith("cdo ymonavg ")
        assert commands[1].startswith("cdo ymoneq ")
        # The climatology the first step writes is the second step's infile2.
        assert commands[0].split()[-1] == commands[1].split()[-2]
    finally:
        dock.close()
        dock.deleteLater()
        window.close()
        window.deleteLater()


# --- the Compc constant -----------------------------------------------------

@pytest.mark.parametrize("operator", COMPC)
def test_the_constant_is_required_and_declared_a_float(operator):
    """``cdo gtc infile outfile`` prompts on stdin forever; it must not be run.

    A blank comma-parameter is a frozen window rather than an error message —
    see ``missing_required_parameters`` for the measurement.
    """
    params = OPERATOR_SCHEMA[operator].params
    assert len(params) == 1
    assert params[0].name == "c"
    assert params[0].optional is False
    assert params[0].kind == "float"


@pytest.mark.parametrize("operator", COMPC)
def test_the_constant_says_it_carries_the_fields_units(operator):
    """CDO's own example is ``gtc,273.15`` — Kelvin, against an unchecked field.

    The units check cannot reach a constant: every ``UNIT_FAMILIES`` entry is
    matched against a *file's* units attribute, and a typed number has none. So
    the fact goes where the number is typed, in the help both surfaces render.
    """
    param = OPERATOR_SCHEMA[operator].params[0]
    assert "units of the input field" in param.help
    assert "converts neither" in param.help
    # And in the placeholder too, which is visible without hovering.
    assert "units" in param.placeholder


# --- the broken module ------------------------------------------------------

@pytest.mark.parametrize("operator", YSEASCOMP)
def test_the_broken_seasonal_module_says_so_before_it_is_run(operator):
    """Only the test harness knew. A user must be told before pressing Run."""
    description = OPERATOR_SCHEMA[operator].description
    assert "Season MAM already allocated!" in description
    for version in _YSEASCOMP_BROKEN_IN:
        assert version in description
    # And it names the controlled comparison, so the claim is checkable.
    assert "yseasadd" in description
    # yseasrange is *not* a control — it takes one input, so two files fail it
    # for a reason that has nothing to do with the season table.
    assert "yseasrange" not in description


@pytest.mark.parametrize("operator", "ymoneq ymonne ymonle ymonlt ymonge ymongt".split())
def test_the_working_monthly_module_carries_no_such_warning(operator):
    """The caveat is about six operators, not about the ymon/yseas shape."""
    assert "Broken in CDO" not in OPERATOR_SCHEMA[operator].description


# --- the claims above, re-measured against the installed binary -------------

def installed_cdo_version() -> str:
    """The version string of the CDO on PATH — the one the app will run.

    Read from the first line rather than by splitting on "version", because
    ``cdo --version`` goes on to print a compiler version and a library version
    too, and a naive split picks up whichever came first.
    """
    out = subprocess.run(["cdo", "--version"], capture_output=True, text=True,
                         timeout=30)
    first = (out.stdout + out.stderr).splitlines()[0]
    return first.split("version")[1].split()[0]


@cdo_required
def test_the_installed_cdo_is_one_the_caveat_was_measured_against():
    """A version-specific warning outliving its version is a lie with a date.

    If this fails, CDO has moved. Re-run the exit-code checks below: either the
    module is still broken, in which case add the new version to
    ``_YSEASCOMP_BROKEN_IN``, or it was fixed and the caveat must come out.
    Both are deliberate acts, which is the point of failing here rather than
    quietly going on warning about a version nobody is running.
    """
    version = installed_cdo_version()
    assert version in _YSEASCOMP_BROKEN_IN, (
        f"installed CDO is {version}, but the Yseascomp caveat was measured "
        f"against {', '.join(_YSEASCOMP_BROKEN_IN)}; re-verify before trusting it")


@pytest.fixture(scope="module")
def series(tmp_path_factory):
    """A 730-day daily series and its monthly and seasonal climatologies."""
    directory = tmp_path_factory.mktemp("comparison")
    paths = {
        "series": directory / "series.nc",
        "ymon": directory / "ymonmean.nc",
        "yseas": directory / "yseasmean.nc",
    }
    subprocess.run(
        ["cdo", "-f", "nc", "-settaxis,2000-01-01,12:00,1day", "-for,1,730",
         str(paths["series"])], capture_output=True, timeout=120, check=True)
    for key, operator in (("ymon", "ymonmean"), ("yseas", "yseasmean")):
        subprocess.run(["cdo", operator, str(paths["series"]), str(paths[key])],
                       capture_output=True, timeout=120, check=True)
    return paths


@cdo_required
@pytest.mark.parametrize("operator,second", [
    ("gt", "series"), ("ymongt", "ymon"),
])
def test_the_working_modules_exit_zero(operator, second, series, tmp_path):
    """Comp and Ymoncomp write a file and exit 0, so the default rule fits them.

    ``_determine_command_success`` sends everything but the Diff module to
    ``returncode == 0``. That is correct here, and the comment that used to
    claim the branch handled "comparison" operators is what was wrong.
    """
    out = subprocess.run(
        ["cdo", operator, str(series["series"]), str(series[second]),
         str(tmp_path / f"{operator}.nc")],
        capture_output=True, text=True, timeout=120)
    assert out.returncode == 0, out.stderr
    assert (tmp_path / f"{operator}.nc").exists()


@cdo_required
def test_compc_exits_zero(series, tmp_path):
    out = subprocess.run(
        ["cdo", "gtc,100", str(series["series"]), str(tmp_path / "gtc.nc")],
        capture_output=True, text=True, timeout=120)
    assert out.returncode == 0, out.stderr


@cdo_required
@pytest.mark.parametrize("operator", YSEASCOMP)
def test_the_seasonal_module_really_does_abort(operator, series, tmp_path):
    """The caveat is a measurement, and this is the measurement.

    A non-zero exit from a comparison operator is a real failure, which is why
    these must never be added to the exit-code-tolerant branch ``diff`` uses.
    The exit code is also the *only* signal: the abort leaves a header-only file
    behind, so "did an output file appear?" answers yes for a run that produced
    nothing usable. CDO will not reopen what it just wrote.
    """
    output = tmp_path / f"{operator}.nc"
    out = subprocess.run(
        ["cdo", operator, str(series["series"]), str(series["yseas"]),
         str(output)], capture_output=True, text=True, timeout=120)

    assert out.returncode != 0
    assert "Season MAM already allocated!" in out.stderr

    # The trap this makes concrete: the file exists, and is not data.
    assert output.exists(), "no longer leaves a file — re-word the caveat"
    reopened = subprocess.run(["cdo", "sinfon", str(output)],
                              capture_output=True, text=True, timeout=120)
    assert reopened.returncode != 0
    assert "No data arrays found" in reopened.stdout + reopened.stderr


@cdo_required
@pytest.mark.parametrize("operator", ["yseasadd", "yseassub"])
def test_the_controlled_comparison_still_holds(operator, series, tmp_path):
    """The same two files through the arithmetic half of the same family.

    This is what makes "the module is broken" a claim rather than a guess: if
    these ever start failing too, the inputs are what changed and the caveat
    needs re-deriving before it is trusted.
    """
    out = subprocess.run(
        ["cdo", operator, str(series["series"]), str(series["yseas"]),
         str(tmp_path / f"{operator}.nc")],
        capture_output=True, text=True, timeout=120)
    assert out.returncode == 0, out.stderr


@cdo_required
def test_a_comparison_returns_a_mask_and_propagates_missing(series, tmp_path):
    """The claim in every one of the twenty-four descriptions, measured once.

    Values in exactly {0, 1}, and missing in exactly the cells the input had
    missing — not zero there.
    """
    xr = pytest.importorskip("xarray")
    numpy = pytest.importorskip("numpy")

    holes = tmp_path / "holes.nc"
    mask = tmp_path / "mask.nc"
    subprocess.run(["cdo", "setrtomiss,300,400", str(series["series"]),
                    str(holes)], capture_output=True, timeout=120, check=True)
    subprocess.run(["cdo", "gtc,100", str(holes), str(mask)],
                   capture_output=True, timeout=120, check=True)

    with xr.open_dataset(holes, decode_times=False) as source, \
            xr.open_dataset(mask, decode_times=False) as result:
        values = result[list(result.data_vars)[0]].values
        original = source[list(source.data_vars)[0]].values

    assert numpy.isnan(original).any(), "the fixture stopped making holes"
    assert set(numpy.unique(values[~numpy.isnan(values)])) <= {0.0, 1.0}
    # Missing propagates; it does not become 0.
    assert numpy.array_equal(numpy.isnan(values), numpy.isnan(original))


# --- the parameter check that stands between a typed value and argv ---------

@pytest.mark.parametrize("value", ["abc", "273.15K", "", " "])
def test_a_constant_that_is_not_a_number_is_refused_before_argv(value):
    """In the app's words about the field, not CDO's about its command line."""
    from ncexplorer_toolkit.core.nc_integration import NCExplorerIntegration

    with pytest.raises(ValueError) as caught:
        NCExplorerIntegration._require_parameters("gtc", [value])
    assert "gtc" in str(caught.value)


@pytest.mark.parametrize("value", ["273.15", "-5", "+5", "1e-3", "-2.5E+10",
                                   "0"])
def test_the_constants_cdo_accepts_keep_working(value):
    """Negatives and scientific notation are ordinary thresholds, not typos."""
    from ncexplorer_toolkit.core.nc_integration import NCExplorerIntegration

    assert NCExplorerIntegration._require_parameters("gtc", [value]) == [value]
