from dataclasses import dataclass, field
from enum import Enum
from typing import Dict, Literal, Tuple

ParamKind = Literal["int", "float", "string", "file", "grid", "select"]


@dataclass(frozen=True)
class OperatorParam:
    """Canonical description of a single trailing parameter of a CDO operator.

    ``kind`` is a widget hint used by the GUI:

    * ``int``/``float`` – numeric field
    * ``string``        – free-text line edit (default)
    * ``file``          – existing file path (browse button)
    * ``grid``          – grid descriptor: file path or CDO preset (``t63grid``, ``r360x180``)
    * ``select``        – one of ``choices``
    """

    name: str
    kind: ParamKind = "string"
    label: str = ""
    placeholder: str = ""
    optional: bool = False
    choices: Tuple[str, ...] = ()
    help: str = ""


@dataclass(frozen=True)
class OperatorSpec:
    """Full metadata for one CDO operator, assembled from the Reference Card."""

    name: str
    nin: int
    nout: int
    category: "NCExplorerCategory"
    params: Tuple[OperatorParam, ...] = ()
    description: str = ""


class NCExplorerCategory(Enum):
    """Categories for cdo operators based on the reference card"""
    INFORMATION = "Information"
    FILE_OPERATIONS = "File operations"
    SELECTION = "Selection"
    CONDITIONAL_SELECTION = "Conditional selection"
    COMPARISON = "Comparison"
    MODIFICATION = "Modification"
    ARITHMETIC = "Arithmetic"
    STATISTICAL_VALUES = "Statistical values"
    REGRESSION = "Regression"
    INTERPOLATION = "Interpolation"
    TRANSFORMATION = "Transformation"
    FORMATTED_IO = "Formatted I/O"
    MISCELLANEOUS = "Miscellaneous"
    ECA_INDICES = "ECA indices"

OPERATOR_SIGNATURES = {
    # op_name: (nin, nout)

    # Information operators (output to stdout, no file output)
    "info": (-1, 0),
    "infoc": (-1, 0),
    "infon": (-1, 0),
    "infop": (-1, 0),
    "infov": (-1, 0),
    "sinfo": (-1, 0),
    "sinfoc": (-1, 0),
    "sinfon": (-1, 0),
    "sinfop": (-1, 0),
    "sinfov": (-1, 0),
    "map": (-1, 0),
    "diff": (2, 0),
    "diffc": (2, 0),
    "diffn": (2, 0),
    "diffp": (2, 0),
    "diffv": (2, 0),
    "ncode": (1, 0),
    "ndate": (1, 0),
    "ngridpoints": (1, 0),
    "ngrids": (1, 0),
    "nlevel": (1, 0),
    "nmon": (1, 0),
    "npar": (1, 0),
    "ntime": (1, 0),
    "nvar": (1, 0),
    "nyear": (1, 0),
    "showattribute": (1, 0),
    "showatts": (1, 0),
    "showattsglob": (1, 0),
    "showattsvar": (1, 0),
    "showcode": (1, 0),
    "showdate": (1, 0),
    "showformat": (1, 0),
    "showgrid": (1, 0),
    "showlevel": (1, 0),
    "showltype": (1, 0),
    "showmon": (1, 0),
    "showname": (1, 0),
    "showparam": (1, 0),
    "showstdname": (1, 0),
    "showtime": (1, 0),
    "showtimestamp": (1, 0),
    "showunit": (1, 0),
    "showvar": (1, 0),
    "showyear": (1, 0),
    "gradsdes": (1, 0),
    "griddes": (1, 0),
    "griddes2": (1, 0),
    "gridcellindex": (1, 0),
    "gmtcells": (1, 0),
    "gmtxyz": (1, 0),
    "outputbounds": (1, 0),
    "outputboundscpt": (1, 0),
    "outputcenter": (1, 0),
    "outputcenter2": (1, 0),
    "outputcentercpt": (1, 0),
    "outputkml": (1, 0),
    "outputtri": (1, 0),
    "codetab": (1, 0),
    "filedes": (1, 0),
    "linfo": (1, 0),
    "spartab": (1, 0),
    "dumpmap": (1, 0),
    "cdiread": (1, 0),
    "pardes": (1, 0),
    "vct": (1, 0),
    "output": (-1, 0),
    "outputarr": (-1, 0),
    "outputext": (-1, 0),
    "outputf": (-1, 0),
    "outputfld": (-1, 0),
    "outputint": (-1, 0),
    "outputkey": (-1, 0),
    "outputsrv": (-1, 0),
    "outputtab": (-1, 0),
    "outputts": (-1, 0),
    "seinfo": (-1, 0),
    "seinfoc": (-1, 0),
    "seinfon": (-1, 0),
    "seinfop": (-1, 0),

    # No input, special operators
    "dcw": (0, 0),
    "conv_cmor_table": (0, 0),
    "dump_cmor_table": (0, 0),
    "specinfo": (0, 0),

    # No input, one output
    "const": (0, 1),
    "coshill": (0, 1),
    "input": (0, 1),
    "inputext": (0, 1),
    "inputsrv": (0, 1),
    "mask": (0, 1),
    "seq": (0, 1),
    "for": (0, 1),
    "cdiwrite": (0, 1),
    "sincos": (0, 1),

    # One input, one output (standard processing)
    "abs": (1, 1),
    "acos": (1, 1),
    "adipot": (1, 1),
    "adisit": (1, 1),
    "aexpr": (1, 1),
    "aexprf": (1, 1),
    "ap2hl": (1, 1),
    "ap2hlx": (1, 1),
    "ap2pl": (1, 1),
    "ap2plx": (1, 1),
    "arg": (1, 1),
    "asin": (1, 1),
    "atan": (1, 1),
    "bandpass": (1, 1),
    "bitrounding": (1, 1),
    "bottomvalue": (1, 1),
    "boxavg": (1, 1),
    "changemulti": (1, 1),
    "chcode": (1, 1),
    "chlevel": (1, 1),
    "chlevelc": (1, 1),
    "chlevelv": (1, 1),
    "chltype": (1, 1),
    "chname": (1, 1),
    "chparam": (1, 1),
    "chtabnum": (1, 1),
    "chunit": (1, 1),
    "chvar": (1, 1),
    "cloudlayer": (1, 1),
    "cmorlite": (1, 1),
    "conj": (1, 1),
    "consecsum": (1, 1),
    "consects": (1, 1),
    "contour": (1, 1),
    "cos": (1, 1),
    "dayavg": (1, 1),
    "daycount": (1, 1),
    "daymax": (1, 1),
    "daymean": (1, 1),
    "daymin": (1, 1),
    "dayrange": (1, 1),
    "daystd": (1, 1),
    "daystd1": (1, 1),
    "daysum": (1, 1),
    "dayvar": (1, 1),
    "dayvar1": (1, 1),
    "del29feb": (1, 1),
    "delcode": (1, 1),
    "delday": (1, 1),
    "delgridcell": (1, 1),
    "delmulti": (1, 1),
    "delname": (1, 1),
    "delparam": (1, 1),
    "delta_pressure": (1, 1),
    "deltat": (1, 1),
    "delvar": (1, 1),
    "detrend": (1, 1),
    "dhouravg": (1, 1),
    "dhourmax": (1, 1),
    "dhourmean": (1, 1),
    "dhourmin": (1, 1),
    "dhourrange": (1, 1),
    "dhourstd": (1, 1),
    "dhourstd1": (1, 1),
    "dhoursum": (1, 1),
    "dhourvar": (1, 1),
    "dhourvar1": (1, 1),
    "dminuteavg": (1, 1),
    "dminutemax": (1, 1),
    "dminutemean": (1, 1),
    "dminutemin": (1, 1),
    "dminuterange": (1, 1),
    "dminutestd": (1, 1),
    "dminutestd1": (1, 1),
    "dminutesum": (1, 1),
    "dminutevar": (1, 1),
    "dminutevar1": (1, 1),
    "duplicate": (1, 1),
    "dv2ps": (1, 1),
    "dv2uv": (1, 1),
    "dv2uvl": (1, 1),
    "eca_cdd": (1, 1),
    "eca_cfd": (1, 1),
    "eca_csu": (1, 1),
    "eca_cwd": (1, 1),
    "eca_fd": (1, 1),
    "eca_hd": (1, 1),
    "eca_id": (1, 1),
    "eca_pd": (1, 1),
    "eca_r10mm": (1, 1),
    "eca_r1mm": (1, 1),
    "eca_r20mm": (1, 1),
    "eca_rr1": (1, 1),
    "eca_rx1day": (1, 1),
    "eca_rx5day": (1, 1),
    "eca_sdii": (1, 1),
    "eca_su": (1, 1),
    "eca_tr": (1, 1),
    "enlarge": (1, 1),
    "etccdi_cdd": (1, 1),
    "etccdi_cwd": (1, 1),
    "etccdi_fd": (1, 1),
    "etccdi_hd": (1, 1),
    "etccdi_id": (1, 1),
    "etccdi_r10mm": (1, 1),
    "etccdi_r1mm": (1, 1),
    "etccdi_r20mm": (1, 1),
    "etccdi_rx1day": (1, 1),
    "etccdi_rx1daymon": (1, 1),
    "etccdi_rx5day": (1, 1),
    "etccdi_rx5daymon": (1, 1),
    "etccdi_sdii": (1, 1),
    "etccdi_su": (1, 1),
    "etccdi_tr": (1, 1),
    "exp": (1, 1),
    "export_e5ml": (1, 1),
    "expr": (1, 1),
    "exprf": (1, 1),
    "fc2gp": (1, 1),
    "fc2sp": (1, 1),
    "fillmiss": (1, 1),
    "fillmiss2": (1, 1),
    "fldavg": (1, 1),
    "fldcount": (1, 1),
    "fldint": (1, 1),
    "fldkurt": (1, 1),
    "fldmax": (1, 1),
    "fldmean": (1, 1),
    "fldmedian": (1, 1),
    "fldmin": (1, 1),
    "fldpctl": (1, 1),
    "fldrange": (1, 1),
    "fldskew": (1, 1),
    "fldstd": (1, 1),
    "fldstd1": (1, 1),
    "fldsum": (1, 1),
    "fldvar": (1, 1),
    "fldvar1": (1, 1),
    "fourier": (1, 1),
    "fourier2grid": (1, 1),
    "genbic": (1, 1),
    "genbil": (1, 1),
    "gencon": (1, 1),
    "gendis": (1, 1),
    "genlaf": (1, 1),
    "genlevelbounds": (1, 1),
    "gennn": (1, 1),
    "genscon": (1, 1),
    "genscon2": (1, 1),
    "genycon": (1, 1),
    "genycon2test": (1, 1),
    "gh2hl": (1, 1),
    "gh2hlx": (1, 1),
    "gheight": (1, 1),
    "gheight_full": (1, 1),
    "gheight_half": (1, 1),
    "gheighthalf": (1, 1),
    "globavg": (1, 1),
    "gp2fc": (1, 1),
    "gp2sp": (1, 1),
    "gp2spl": (1, 1),
    "grfill": (1, 1),
    "grid2fourier": (1, 1),
    "gridarea": (1, 1),
    "gridboxavg": (1, 1),
    "gridboxkurt": (1, 1),
    "gridboxmax": (1, 1),
    "gridboxmean": (1, 1),
    "gridboxmedian": (1, 1),
    "gridboxmin": (1, 1),
    "gridboxrange": (1, 1),
    "gridboxskew": (1, 1),
    "gridboxstd": (1, 1),
    "gridboxstd1": (1, 1),
    "gridboxsum": (1, 1),
    "gridboxvar": (1, 1),
    "gridboxvar1": (1, 1),
    "gridcellidx": (1, 1),
    "griddx": (1, 1),
    "griddy": (1, 1),
    "gridmask": (1, 1),
    "gridweights": (1, 1),
    "harmonic": (1, 1),
    "highpass": (1, 1),
    "histcount": (1, 1),
    "histfreq": (1, 1),
    "histmean": (1, 1),
    "histsum": (1, 1),
    "houravg": (1, 1),
    "hourcount": (1, 1),
    "hourmax": (1, 1),
    "hourmean": (1, 1),
    "hourmin": (1, 1),
    "hourrange": (1, 1),
    "hourstd": (1, 1),
    "hourstd1": (1, 1),
    "hoursum": (1, 1),
    "hourvar": (1, 1),
    "hourvar1": (1, 1),
    "hpdegrade": (1, 1),
    "hpupgrade": (1, 1),
    "hurr": (1, 1),
    "im": (1, 1),
    "import_amsr": (1, 1),
    "import_binary": (1, 1),
    "import_cmsaf": (1, 1),
    "import_e5ml": (1, 1),
    "import_fv3grid": (1, 1),
    "import_grads": (1, 1),
    "import_obs": (1, 1),
    "imtocomplex": (1, 1),
    "int": (1, 1),
    "interpolate": (1, 1),
    "intgrid": (1, 1),
    "intgridbil": (1, 1),
    "intgriddis": (1, 1),
    "intgridnn": (1, 1),
    "intgridtraj": (1, 1),
    "intlevel": (1, 1),
    "intlevelx": (1, 1),
    "intntime": (1, 1),
    "inttime": (1, 1),
    "invertlat": (1, 1),
    "invertlatdata": (1, 1),
    "invertlatdes": (1, 1),
    "invertlev": (1, 1),
    "invertlon": (1, 1),
    "invertlondata": (1, 1),
    "invertlondes": (1, 1),
    "isosurface": (1, 1),
    "lic": (1, 1),
    "ln": (1, 1),
    "log": (1, 1),
    "log10": (1, 1),
    "lowpass": (1, 1),
    "maskcircle": (1, 1),
    "maskindexbox": (1, 1),
    "masklonlatbox": (1, 1),
    "maskregion": (1, 1),
    "mastrfu": (1, 1),
    "meravg": (1, 1),
    "merkurt": (1, 1),
    "mermax": (1, 1),
    "mermean": (1, 1),
    "mermedian": (1, 1),
    "mermin": (1, 1),
    "merpctl": (1, 1),
    "merrange": (1, 1),
    "merskew": (1, 1),
    "merstd": (1, 1),
    "merstd1": (1, 1),
    "mersum": (1, 1),
    "mervar": (1, 1),
    "mervar1": (1, 1),
    "ml2hl": (1, 1),
    "ml2hlx": (1, 1),
    "ml2pl": (1, 1),
    "ml2plx": (1, 1),
    "mod": (1, 1),
    "monavg": (1, 1),
    "moncount": (1, 1),
    "monmax": (1, 1),
    "monmean": (1, 1),
    "monmin": (1, 1),
    "monrange": (1, 1),
    "monstd": (1, 1),
    "monstd1": (1, 1),
    "monsum": (1, 1),
    "monvar": (1, 1),
    "monvar1": (1, 1),
    "muldoy": (1, 1),
    "muldpm": (1, 1),
    "muldpy": (1, 1),
    "ncopy": (1, 1),
    "nint": (1, 1),
    "not": (1, 1),
    "selcircle": (1, 1),
    "selcode": (1, 1),
    "seldate": (1, 1),
    "selday": (1, 1),
    "selgrid": (1, 1),
    "selgridcell": (1, 1),
    "selgridname": (1, 1),
    "selhour": (1, 1),
    "selindexbox": (1, 1),
    "sellevel": (1, 1),
    "sellevidx": (1, 1),
    "sellonlatbox": (1, 1),
    "selltype": (1, 1),
    "selmon": (1, 1),
    "selmonth": (1, 1),
    "selmulti": (1, 1),
    "selname": (1, 1),
    "seloperator": (1, 1),
    "selparam": (1, 1),
    "selrec": (1, 1),
    "selregion": (1, 1),
    "selseas": (1, 1),
    "selseason": (1, 1),
    "selsmon": (1, 1),
    "selstdname": (1, 1),
    "seltabnum": (1, 1),
    "seltime": (1, 1),
    "seltimestep": (1, 1),
    "selvar": (1, 1),
    "selyear": (1, 1),
    "selzaxis": (1, 1),
    "selzaxisname": (1, 1),
    "setattribute": (1, 1),
    "setcalendar": (1, 1),
    "setcindexbox": (1, 1),
    "setclonlatbox": (1, 1),
    "setcode": (1, 1),
    "setcodetab": (1, 1),
    "setctomiss": (1, 1),
    "setdate": (1, 1),
    "setday": (1, 1),
    "setgrid": (1, 1),
    "setgridarea": (1, 1),
    "setgridcell": (1, 1),
    "setgridmask": (1, 1),
    "setgridnumber": (1, 1),
    "setgridtype": (1, 1),
    "setgriduri": (1, 1),
    "sethalo": (1, 1),
    "setlevel": (1, 1),
    "setltype": (1, 1),
    "setmaxsteps": (1, 1),
    "setmisstoc": (1, 1),
    "setmisstodis": (1, 1),
    "setmisstonn": (1, 1),
    "setmissval": (1, 1),
    "setmon": (1, 1),
    "setname": (1, 1),
    "setparam": (1, 1),
    "setpartab": (1, 1),
    "setpartabc": (1, 1),
    "setpartabn": (1, 1),
    "setpartabp": (1, 1),
    "setpartabv": (1, 1),
    "setprojparams": (1, 1),
    "setrcaname": (1, 1),
    "setreftime": (1, 1),
    "setrtoc": (1, 1),
    "setrtoc2": (1, 1),
    "setrtomiss": (1, 1),
    "settabnum": (1, 1),
    "settaxis": (1, 1),
    "settbounds": (1, 1),
    "settime": (1, 1),
    "settunits": (1, 1),
    "setunit": (1, 1),
    "setvals": (1, 1),
    "setvar": (1, 1),
    "setvrange": (1, 1),
    "setyear": (1, 1),
    "setzaxis": (1, 1),
    "shaded": (1, 1),
    "shifttime": (1, 1),
    "shiftx": (1, 1),
    "shifty": (1, 1),
    "sin": (1, 1),
    "smooth": (1, 1),
    "smooth9": (1, 1),
    "sortcode": (1, 1),
    "sortlevel": (1, 1),
    "sortname": (1, 1),
    "sortparam": (1, 1),
    "sortvar": (1, 1),
    "sp2fc": (1, 1),
    "sp2gp": (1, 1),
    "sp2gpl": (1, 1),
    "sp2sp": (1, 1),
    "spcut": (1, 1),
    "spectrum": (1, 1),
    "sqr": (1, 1),
    "sqrt": (1, 1),
    "tan": (1, 1),
    "timmean": (1, 1),
    "timavg": (1, 1),
    "timmax": (1, 1),
    "timmin": (1, 1),
    "timstd": (1, 1),
    "timstd1": (1, 1),
    "timsum": (1, 1),
    "timvar": (1, 1),
    "timvar1": (1, 1),
    "timsort": (1, 1),
    "topvalue": (1, 1),
    "trend": (1, 2),
    "uv2dv": (1, 1),
    "uv2dvl": (1, 1),
    "vert2fld": (1, 1),
    "vertavg": (1, 1),
    "vertkurt": (1, 1),
    "vertmax": (1, 1),
    "vertmean": (1, 1),
    "vertmin": (1, 1),
    "vertrange": (1, 1),
    "vertskew": (1, 1),
    "vertstd": (1, 1),
    "vertstd1": (1, 1),
    "vertsum": (1, 1),
    "vertvar": (1, 1),
    "vertvar1": (1, 1),
    "yaddc": (1, 1),
    "ydivc": (1, 1),
    "ymulc": (1, 1),
    "ysubc": (1, 1),
    "zonmean": (1, 1),
    "zonavg": (1, 1),
    "zonkurt": (1, 1),
    "zonmax": (1, 1),
    "zonmin": (1, 1),
    "zonrange": (1, 1),
    "zonskew": (1, 1),
    "zonstd": (1, 1),
    "zonstd1": (1, 1),
    "zonsum": (1, 1),
    "zonvar": (1, 1),
    "zonvar1": (1, 1),
    "addc": (1, 1),
    "subc": (1, 1),
    "mulc": (1, 1),
    "divc": (1, 1),
    "eqc": (1, 1),
    "nec": (1, 1),
    "lec": (1, 1),
    "ltc": (1, 1),
    "gec": (1, 1),
    "gtc": (1, 1),
    "maxc": (1, 1),
    "minc": (1, 1),
    "ifthenc": (1, 1),
    "ifnotthenc": (1, 1),
    "mulcoslat": (1, 1),
    "divcoslat": (1, 1),
    "cmor": (1, 0),

    # One input, two outputs
    "complextopol": (1, 2),
    "complextorect": (1, 2),
    "eof": (1, 2),
    "eof3d": (1, 2),
    "eof3dspatial": (1, 2),
    "eof3dtime": (1, 2),
    "eofspatial": (1, 2),
    "eoftime": (1, 2),

    # One input, multiple outputs (split operations)
    "distgrid": (1, -1),
    "splitcode": (1, -1),
    "splitdate": (1, -1),
    "splitdatetime": (1, -1),
    "splitday": (1, -1),
    "splitgrid": (1, -1),
    "splithour": (1, -1),
    "splitlevel": (1, -1),
    "splitmon": (1, -1),
    "splitname": (1, -1),
    "splitparam": (1, -1),
    "splitrec": (1, -1),
    "splitseas": (1, -1),
    "splitsel": (1, -1),
    "splittabnum": (1, -1),
    "splittime": (1, -1),
    "splityear": (1, -1),
    "splitzaxis": (1, -1),

    # Two inputs, one output
    "add": (2, 1),
    "atan2": (2, 1),
    "dayadd": (2, 1),
    "daydiv": (2, 1),
    "daymul": (2, 1),
    "daysub": (2, 1),
    "div": (2, 1),
    "eq": (2, 1),
    "fdns": (2, 1),
    "fldcor": (2, 1),
    "fldcovar": (2, 1),
    "fldrms": (2, 1),
    "ge": (2, 1),
    "gengrid": (2, 1),
    "gt": (2, 1),
    "ifnotthen": (2, 1),
    "ifthen": (2, 1),
    "intlevel3d": (2, 1),
    "intlevelx3d": (2, 1),
    "le": (2, 1),
    "lt": (2, 1),
    "max": (2, 1),
    "meandiff2test": (2, 1),
    "mergegrid": (2, 1),
    "min": (2, 1),
    "monadd": (2, 1),
    "mondiv": (2, 1),
    "monmul": (2, 1),
    "monsub": (2, 1),
    "mrotuvb": (2, 1),
    "mul": (2, 1),
    "ne": (2, 1),
    "seltimeidx": (2, 1),
    "selyearidx": (2, 1),
    "setmiss": (2, 1),
    "sub": (2, 1),
    "anomaly": (2, 1),
    "ymonsub": (2, 1),
    "ymonadd": (2, 1),
    "ymondiv": (2, 1),
    "ymonmul": (2, 1),
    "eca_cwdi": (2, 1),
    "eca_cwfi": (2, 1),
    "eca_etr": (2, 1),
    "eca_gsl": (2, 1),
    "eca_hwdi": (2, 1),
    "eca_hwfi": (2, 1),
    "eca_r75p": (2, 1),
    "eca_r75ptot": (2, 1),
    "eca_r90p": (2, 1),
    "eca_r90ptot": (2, 1),
    "eca_r95p": (2, 1),
    "eca_r95ptot": (2, 1),
    "eca_r99p": (2, 1),
    "eca_r99ptot": (2, 1),
    "eca_tg10p": (2, 1),
    "eca_tg90p": (2, 1),
    "eca_tn10p": (2, 1),
    "eca_tn90p": (2, 1),
    "eca_tx10p": (2, 1),
    "eca_tx90p": (2, 1),
    "etccdi_csdi": (2, 1),
    "etccdi_gsl": (2, 1),
    "etccdi_wsdi": (2, 1),
    "intyear": (2, -1),

    # Two inputs, multiple outputs
    "eofcoeff": (2, -1),
    "eofcoeff3d": (2, -1),
    "mrotuv": (1, 2),

    # Three inputs, one output
    "addtrend": (3, 1),
    "daypctl": (3, 1),
    "etccdi": (3, 1),
    "etccdi_r95p": (3, 1),
    "etccdi_r99p": (3, 1),
    "etccdi_tn10p": (3, 1),
    "etccdi_tn90p": (3, 1),
    "etccdi_tx10p": (3, 1),
    "etccdi_tx90p": (3, 1),
    "hi": (3, 1),
    "hourpctl": (3, 1),
    "ifthenelse": (3, 1),
    "monpctl": (3, 1),
    "runpctl": (1, 1),
    "timpctl": (3, 1),
    "timselmax": (1, 1),
    "timselmin": (1, 1),
    "timselmean": (1, 1),
    "ydaypctl": (3, 1),
    "ymonpctl": (3, 1),
    "ydrunpctl": (3, 1),
    "yseaspctl": (3, 1),
    "seasavg": (1, 1),
    "seasmax": (1, 1),
    "seasmin": (1, 1),
    "seasstd": (1, 1),
    "seasstd1": (1, 1),
    "seassum": (1, 1),
    "seasvar": (1, 1),
    "seasvar1": (1, 1),
    "seaspctl": (3, 1),
    "yearavg": (1, 1),
    "yearmax": (1, 1),
    "yearmin": (1, 1),
    "yearstd": (1, 1),
    "yearstd1": (1, 1),
    "yearsum": (1, 1),
    "yearvar": (1, 1),
    "yearvar1": (1, 1),
    "yearpctl": (3, 1),

    # Variable inputs, one output
    "after": (-1, 1),
    "afterburner": (-1, 1),
    "cat": (-1, 1),
    "clone": (-1, 1),
    "collgrid": (-1, 1),
    "copy": (-1, 1),
    "delete": (-1, 1),
    "ensavg": (-1, 1),
    "enskurt": (-1, 1),
    "ensmax": (-1, 1),
    "ensmean": (-1, 1),
    "ensmedian": (-1, 1),
    "ensmin": (-1, 1),
    "enspctl": (-1, 1),
    "ensrange": (-1, 1),
    "ensrkhistspace": (-1, 1),
    "ensrkhisttime": (-1, 1),
    "ensroc": (-1, 1),
    "ensskew": (-1, 1),
    "ensstd": (-1, 1),
    "ensstd1": (-1, 1),
    "enssum": (-1, 1),
    "ensvar": (-1, 1),
    "ensvar1": (-1, 1),
    "graph": (-1, 1),
    "merge": (-1, 1),
    "mergetime": (-1, 1),
    "select": (-1, 1),
    "sorttaxis": (-1, 1),
    "sorttimestamp": (-1, 1),

    # Variable inputs, multiple outputs
    "ensbrs": (-1, -1),
    "enscrps": (-1, -1),
}

# Reference-card operators missing from the historical catalog. Registered
# here rather than inline to keep the edit surgical. Each entry has a
# corresponding _PARAM_SPECS entry where non-trivial parameters apply.
_EXTRA_OPERATOR_SIGNATURES = {
    "remap": (1, 1),
    "remapbil": (1, 1),
    "remapbic": (1, 1),
    "remapnn": (1, 1),
    "remapdis": (1, 1),
    "remapcon": (1, 1),
    "remapcon2": (1, 1),
    "remaplaf": (1, 1),
    "remapsum": (1, 1),
    "remapycon": (1, 1),
    "remapeta": (1, 1),
    "genbil": (1, 1),
    "genbic": (1, 1),
    "gennn": (1, 1),
    "gendis": (1, 1),
    "gencon": (1, 1),
    "gencon2": (1, 1),
    "genlaf": (1, 1),
    "genycon": (1, 1),
    "timselpctl": (3, 1),
    "intyear": (2, -1),
    "interpolate": (1, 1),
    "intgridbil": (1, 1),
    "intgridcon": (1, 1),
    "intgriddis": (1, 1),
    "intgridnn": (1, 1),
    "intlevel": (1, 1),
    "intlevelx": (1, 1),
    "inttime": (1, 1),
    "inttimes": (1, 1),
    "setgatts": (1, 1),
    "setpartab": (1, 1),
    "setpartabn": (1, 1),
    "setpartabp": (1, 1),
    "setpartabv": (1, 1),
    "ml2pl": (1, 1),
    "ml2hl": (1, 1),
    "pl2ml": (1, 1),
    "hl2ml": (1, 1),
    "exprf": (1, 1),
    "aexprf": (1, 1),
    "histcount": (1, 1),
    "histsum": (1, 1),
    "histmean": (1, 1),
    "histfreq": (1, 1),
}
for _k, _v in _EXTRA_OPERATOR_SIGNATURES.items():
    OPERATOR_SIGNATURES.setdefault(_k, _v)


# Complete operator mapping
OPERATOR_CATEGORIES = {
    NCExplorerCategory.INFORMATION: [
        'info', 'infov', 'map', 'sinfo', 'sinfov', 'diff', 'diffv', 'npar',
        'nlevel', 'nyear', 'nmon', 'ndate', 'ntime', 'showformat', 'showcode',
        'showname', 'showstdname', 'showlevel', 'showltype', 'showyear',
        'showmon', 'showdate', 'showtime', 'pardes', 'griddes', 'vct'
    ],
    NCExplorerCategory.FILE_OPERATIONS: [
        'copy', 'cat', 'replace', 'merge', 'mergetime', 'splitcode',
        'splitname', 'splitlevel', 'splitgrid', 'splitzaxis', 'splithour',
        'splitday', 'splitmon', 'splitseas', 'splityear', 'splitsel'
    ],
    NCExplorerCategory.SELECTION: [
        'selcode', 'delcode', 'selname', 'delname', 'selstdname', 'sellevel',
        'selgrid', 'selgridname', 'selzaxis', 'selzaxisname', 'selltype',
        'seltabnum', 'seltimestep', 'seltime', 'selhour', 'selday', 'selmon',
        'selyear', 'selseas', 'seldate', 'selsmon', 'sellonlatbox', 'selindexbox'
    ],
    NCExplorerCategory.CONDITIONAL_SELECTION: [
        'ifthen', 'ifnotthen', 'ifthenelse', 'ifthenc', 'ifnotthenc'
    ],
    NCExplorerCategory.COMPARISON: [
        'eq', 'ne', 'le', 'lt', 'ge', 'gt', 'eqc', 'nec', 'lec', 'ltc', 'gec', 'gtc'
    ],
    NCExplorerCategory.MODIFICATION: [
        'setpartab', 'setcode', 'setname', 'setlevel', 'setltype', 'setdate',
        'settime', 'setday', 'setmon', 'setyear', 'settunits', 'settaxis',
        'setreftime', 'setcalendar', 'shifttime', 'chcode', 'chname',
        'chlevel', 'chlevelc', 'chlevelv', 'setgrid', 'setgridtype',
        'setzaxis', 'setgatt', 'setgatts', 'invertlat', 'invertlon',
        'invertlatdes', 'invertlondes', 'invertlatdata', 'invertlondata',
        'maskregion', 'masklonlatbox', 'maskindexbox', 'setclonlatbox',
        'setcindexbox', 'enlarge', 'setmissval', 'setctomiss', 'setmisstoc',
        'setrtomiss'
    ],
    NCExplorerCategory.ARITHMETIC: [
        'expr', 'exprf', 'abs', 'int', 'nint', 'sqr', 'sqrt', 'exp', 'ln',
        'log10', 'sin', 'cos', 'tan', 'asin', 'acos', 'atan', 'addc', 'subc',
        'mulc', 'divc', 'add', 'sub', 'mul', 'div', 'min', 'max', 'atan2',
        'ymonadd', 'ymonsub', 'ymonmul', 'ymondiv', 'muldpm', 'divdpm',
        'muldpy', 'divdpy'
    ],
    NCExplorerCategory.STATISTICAL_VALUES: [
        'ensmin', 'ensmax', 'enssum', 'ensmean', 'ensavg', 'ensvar', 'ensstd',
        'enspctl', 'fldmin', 'fldmax', 'fldsum', 'fldmean', 'fldavg',
        'fldvar', 'fldstd', 'fldpctl', 'zonmin', 'zonmax', 'zonsum',
        'zonmean', 'zonavg', 'zonvar', 'zonstd', 'zonpctl', 'mermin',
        'mermax', 'mersum', 'mermean', 'meravg', 'mervar', 'merstd',
        'merpctl', 'vertmin', 'vertmax', 'vertsum', 'vertmean', 'vertavg',
        'vertvar', 'vertstd', 'timselmin', 'timselmax', 'timselsum',
        'timselmean', 'timselavg', 'timselvar', 'timselstd', 'timselpctl',
        'runmin', 'runmax', 'runsum', 'runmean', 'runavg', 'runvar',
        'runstd', 'runpctl', 'timmin', 'timmax', 'timsum', 'timmean',
        'timavg', 'timvar', 'timstd', 'timpctl', 'hourmin', 'hourmax',
        'hoursum', 'hourmean', 'houravg', 'hourvar', 'hourstd', 'hourpctl',
        'daymin', 'daymax', 'daysum', 'daymean', 'dayavg', 'dayvar',
        'daystd', 'daypctl', 'monmin', 'monmax', 'monsum', 'monmean',
        'monavg', 'monvar', 'monstd', 'monpctl', 'yearmin', 'yearmax',
        'yearsum', 'yearmean', 'yearavg', 'yearvar', 'yearstd', 'yearpctl',
        'seasmin', 'seasmax', 'seassum', 'seasmean', 'seasavg', 'seasvar',
        'seasstd', 'seaspctl', 'ydaymin', 'ydaymax', 'ydaysum', 'ydaymean',
        'ydayavg', 'ydayvar', 'ydaystd', 'ydaypctl', 'ymonmin', 'ymonmax',
        'ymonsum', 'ymonmean', 'ymonavg', 'ymonvar', 'ymonstd', 'ymonpctl',
        'yseasmin', 'yseasmax', 'yseassum', 'yseasmean', 'yseasavg',
        'yseasvar', 'yseasstd', 'yseaspctl', 'ydrunmin', 'ydrunmax',
        'ydrunsum', 'ydrunmean', 'ydrunavg', 'ydrunvar', 'ydrunstd',
        'ydrunpctl'
    ],
    NCExplorerCategory.REGRESSION: [
        'detrend', 'trend', 'subtrend'
    ],
    NCExplorerCategory.INTERPOLATION: [
        'remapbil', 'remapbic', 'remapcon', 'remapdis', 'genbil', 'genbic',
        'gencon', 'gendis', 'remap', 'interpolate', 'intgridbil', 'remapeta',
        'ml2pl', 'ml2hl', 'inttime', 'intntime', 'intyear'
    ],
    NCExplorerCategory.TRANSFORMATION: [
        'sp2gp', 'sp2gpl', 'gp2sp', 'gp2spl', 'sp2sp', 'spcut', 'dv2uv',
        'dv2uvl', 'uv2dv', 'uv2dvl'
    ],
    NCExplorerCategory.FORMATTED_IO: [
        'input', 'inputsrv', 'inputext', 'output', 'outputf', 'outputint',
        'outputsrv', 'outputext'
    ],
    NCExplorerCategory.MISCELLANEOUS: [
        'gradsdes1', 'gradsdes2', 'smooth9', 'setrtoc', 'setrtoc2', 'timsort',
        'const', 'random', 'rotuvb', 'mastrfu', 'histcount', 'histsum',
        'histmean', 'histfreq', 'wct', 'fdns', 'strwin', 'strbre', 'strgal',
        'hurr'
    ],
    NCExplorerCategory.ECA_INDICES: [
        'eca_cdd', 'eca_cfd', 'eca_csu', 'eca_cwd', 'eca_cwdi', 'eca_cwfi',
        'eca_etr', 'eca_fd', 'eca_gsl', 'eca_hd', 'eca_hwdi', 'eca_hwfi',
        'eca_id', 'eca_r10mm', 'eca_r20mm', 'eca_r75p', 'eca_r75ptot',
        'eca_r90p', 'eca_r90ptot', 'eca_r95p', 'eca_r95ptot', 'eca_r99p',
        'eca_r99ptot', 'eca_rr1', 'eca_rx1day', 'eca_rx5day', 'eca_sdii',
        'eca_su', 'eca_tg10p', 'eca_tg90p', 'eca_tn10p', 'eca_tn90p',
        'eca_tr', 'eca_tx10p', 'eca_tx90p'
    ]
}

# Reverse mapping for a quick lookup
CATEGORY_FOR_OPERATOR = {}
for category, operators in OPERATOR_CATEGORIES.items():
    for op in operators:
        CATEGORY_FOR_OPERATOR[op] = category


# ---------------------------------------------------------------------------
# Unified operator schema (single source of truth for GUI + execution layer)
#
# ``_PARAM_SPECS`` lists the trailing, non-file parameters every operator
# accepts, matched against the CDO Reference Card (v1.0.8, June 2007) and
# cross-checked with the User's Guide.  Optional parameters are flagged so the
# GUI can label them and the integration layer can strip trailing empty values
# before building the ``cdo op,a,b,,`` token.
# ---------------------------------------------------------------------------

# Grid descriptor presets understood by CDO (subset – enough for quick picks).
GRID_PRESETS: Tuple[str, ...] = (
    "t21grid", "t31grid", "t42grid", "t63grid", "t85grid", "t106grid",
    "t159grid", "t255grid", "r72x36", "r180x90", "r360x180", "r720x360",
    "r1440x720", "global_1", "global_0.5",
)

_INT = "int"
_FLOAT = "float"
_STR = "string"
_FILE = "file"
_GRID = "grid"


def _p(name: str,
       kind: ParamKind = _STR,
       label: str = "",
       placeholder: str = "",
       optional: bool = False,
       choices: Tuple[str, ...] = (),
       help: str = "") -> OperatorParam:
    return OperatorParam(
        name=name,
        kind=kind,
        label=label or name,
        placeholder=placeholder,
        optional=optional,
        choices=choices,
        help=help,
    )


_PARAM_SPECS: Dict[str, Tuple[OperatorParam, ...]] = {
    # ---------- Selection ----------
    "selcode":     (_p("codes", _STR, "codes", "e.g. 130,131"),),
    "delcode":     (_p("codes", _STR, "codes", "e.g. 130,131"),),
    "selname":     (_p("vars", _STR, "variables", "comma-separated variable names"),),
    "delname":     (_p("vars", _STR, "variables", "comma-separated variable names"),),
    "selstdname":  (_p("stdnames", _STR, "standard names", "comma-separated standard names"),),
    "sellevel":    (_p("levels", _STR, "levels", "e.g. 1000,850"),),
    "sellevidx":   (_p("levidx", _STR, "level indices", "comma-separated level indices"),),
    "selgrid":     (_p("grids", _STR, "grids", "grid IDs or names"),),
    "selgridname": (_p("gridnames", _STR, "gridnames", "grid names"),),
    "selzaxis":    (_p("zaxes", _STR, "zaxes", "z-axis IDs"),),
    "selzaxisname":(_p("zaxisnames", _STR, "zaxisnames", "z-axis names"),),
    "selltype":    (_p("ltypes", _STR, "ltypes", "GRIB level types"),),
    "seltabnum":   (_p("tabnums", _STR, "tabnums", "table numbers"),),
    "seltimestep": (_p("timesteps", _STR, "timesteps", "comma-separated time steps"),),
    "seltime":     (_p("times", _STR, "times", "e.g. 12:00,18:00"),),
    "selhour":     (_p("hours", _STR, "hours", "e.g. 0,6,12,18"),),
    "selday":      (_p("days", _STR, "days"),),
    "selmon":      (_p("months", _STR, "months", "e.g. 1,2,12"),),
    "selyear":     (_p("years", _STR, "years", "e.g. 1981/2010"),),
    "selseas":     (_p("seasons", _STR, "seasons", "e.g. DJF,MAM",
                       choices=("DJF", "MAM", "JJA", "SON")),),
    "seldate":     (
        _p("date1", _STR, "date1", "first date (YYYY-MM-DD)"),
        _p("date2", _STR, "date2", "second date (optional)", optional=True),
    ),
    "selsmon":     (
        _p("month", _INT, "month", "1–12"),
        _p("nts1", _INT, "nts1", "optional", optional=True),
        _p("nts2", _INT, "nts2", "optional", optional=True),
    ),
    "sellonlatbox":(
        _p("lon1", _FLOAT, "lon1"),
        _p("lon2", _FLOAT, "lon2"),
        _p("lat1", _FLOAT, "lat1"),
        _p("lat2", _FLOAT, "lat2"),
    ),
    "selindexbox": (
        _p("idx1", _INT, "idx1"),
        _p("idx2", _INT, "idx2"),
        _p("idy1", _INT, "idy1"),
        _p("idy2", _INT, "idy2"),
    ),
    "selparam":    (_p("params", _STR, "params", "parameter identifiers"),),
    "selmonth":    (_p("months", _STR, "months", "e.g. 1,2,12"),),
    "selseason":   (_p("seasons", _STR, "seasons", "e.g. DJF,MAM",
                       choices=("DJF", "MAM", "JJA", "SON")),),
    "selvar":      (_p("vars", _STR, "variables", "comma-separated variable names"),),
    "selregion":   (_p("regions", _STR, "regions", "region IDs"),),
    "selrec":      (_p("records", _STR, "records", "record numbers"),),
    "selgridcell": (_p("cells", _STR, "cells", "grid cell indices"),),
    "selmulti":    (_p("params", _STR, "params", "parameter identifiers"),),
    "seloperator": (_p("params", _STR, "params", "operator parameter selectors"),),
    "delvar":      (_p("vars", _STR, "variables", "comma-separated variable names"),),
    "delparam":    (_p("params", _STR, "params", "parameter identifiers"),),
    "delmulti":    (_p("params", _STR, "params", "parameter identifiers"),),
    "delgridcell": (_p("cells", _STR, "cells", "grid cell indices"),),
    "changemulti": (_p("params", _STR, "params", "old,new parameter mapping"),),
    "setcodetab":  (_p("table", _FILE, "table", "parameter code table file"),),
    "settabnum":   (_p("tabnum", _INT, "tabnum", "table number"),),
    "setgridcell": (_p("cells", _STR, "cells", "grid cell indices"),),
    "setgridnumber": (_p("number", _INT, "gridnumber", "grid reference number"),),
    "setgriduri":  (_p("uri", _STR, "gridURI", "grid URI"),),
    "setprojparams": (_p("params", _STR, "proj4 params", "PROJ.4 parameter string"),),
    "setrcaname":  (),
    "mod":         (_p("c", _FLOAT, "c (divisor)"),),
    "smooth":      (_p("params", _STR, "smoothing params",
                       "optional nsmooth=N,radius=R,form=FORM",
                       optional=True),),
    "distgrid":    (_p("nx", _INT, "nx"), _p("ny", _INT, "ny")),
    "ensbrs":      (_p("x", _FLOAT, "x (threshold)"),),
    "ensroc":      (_p("x", _FLOAT, "x (threshold)"),),
    "eof":         (_p("neof", _INT, "neof", "number of EOFs"),),
    "eof3d":       (_p("neof", _INT, "neof"),),
    "eof3dspatial":(_p("neof", _INT, "neof"),),
    "eof3dtime":   (_p("neof", _INT, "neof"),),
    "eofspatial":  (_p("neof", _INT, "neof"),),
    "eoftime":     (_p("neof", _INT, "neof"),),
    "fourier":     (_p("sign", _INT, "sign", "-1 or 1"),),
    "harmonic":    (_p("nwaves", _INT, "nwaves"), _p("end", _INT, "end")),
    "gh2hl":       (_p("levels", _STR, "levels", "comma-separated target heights"),),
    "gh2hlx":      (_p("levels", _STR, "levels", "comma-separated target heights"),),
    "intlevel3d":  (_p("zdes", _FILE, "z-axis description file"),),
    "intlevelx3d": (_p("zdes", _FILE, "z-axis description file"),),
    "isosurface":  (_p("value", _FLOAT, "isovalue"),),
    "import_obs":  (_p("grid", _GRID, "grid", choices=GRID_PRESETS),),
    "cmorlite":    (_p("table", _FILE, "CMOR table"),),
    "genscon2":    (_p("grid", _GRID, "grid", choices=GRID_PRESETS),),
    "genycon2test":(_p("grid", _GRID, "grid", choices=GRID_PRESETS),),
    "meandiff2test":(),
    "gridboxmedian":(_p("nx", _INT, "nx"), _p("ny", _INT, "ny")),
    "gridboxkurt": (_p("nx", _INT, "nx"), _p("ny", _INT, "ny")),
    "gridboxskew": (_p("nx", _INT, "nx"), _p("ny", _INT, "ny")),
    "gridboxstd1": (_p("nx", _INT, "nx"), _p("ny", _INT, "ny")),
    "gridboxvar1": (_p("nx", _INT, "nx"), _p("ny", _INT, "ny")),
    # ---------- Operators that print "Too few arguments" without a param ----------
    "delday":      (_p("day", _INT, "day", "1–31"),),
    "etccdi":      (_p("mode", _STR, "mode", "index mode"),),
    "etccdi_r95p": (),
    "etccdi_r99p": (),
    "etccdi_tn10p":(),
    "etccdi_tn90p":(),
    "etccdi_tx10p":(),
    "etccdi_tx90p":(),
    "lic":         (_p("cpt", _FILE, "cpt palette file"),),
    "outputkml":   (_p("cpt", _FILE, "cpt palette file"),),
    "outputboundscpt": (_p("cpt", _FILE, "cpt palette file"),),
    "outputcentercpt": (_p("cpt", _FILE, "cpt palette file"),),
    "selcircle":   (
        _p("lon0", _FLOAT, "lon0"),
        _p("lat0", _FLOAT, "lat0"),
        _p("r", _FLOAT, "radius (deg)"),
    ),
    "delete":      (_p("selection", _STR, "selection", "e.g. name=tas"),),
    "select":      (_p("selection", _STR, "selection", "e.g. name=tas,level=850"),),

    # ---------- Conditional selection ----------
    "ifthenc":     (_p("c", _FLOAT, "c", "constant"),),
    "ifnotthenc":  (_p("c", _FLOAT, "c", "constant"),),

    # ---------- Comparison (constants) ----------
    "eqc":         (_p("c", _FLOAT, "c", "constant"),),
    "nec":         (_p("c", _FLOAT, "c", "constant"),),
    "lec":         (_p("c", _FLOAT, "c", "constant"),),
    "ltc":         (_p("c", _FLOAT, "c", "constant"),),
    "gec":         (_p("c", _FLOAT, "c", "constant"),),
    "gtc":         (_p("c", _FLOAT, "c", "constant"),),
    "maxc":        (_p("c", _FLOAT, "c", "constant"),),
    "minc":        (_p("c", _FLOAT, "c", "constant"),),

    # ---------- Modification ----------
    "setpartab":   (_p("table", _FILE, "table", "parameter table name or file"),),
    "setpartabc":  (_p("table", _FILE, "table", "parameter table (code)"),),
    "setpartabn":  (_p("table", _FILE, "table", "parameter table (name)"),),
    "setpartabp":  (_p("table", _FILE, "table", "parameter table (param)"),),
    "setpartabv":  (_p("table", _FILE, "table", "parameter table (variable)"),),
    "setcode":     (_p("code", _INT, "code", "GRIB code number"),),
    "setparam":    (_p("param", _STR, "param", "parameter identifier"),),
    "setname":     (_p("name", _STR, "name", "new variable name"),),
    "setvar":      (_p("name", _STR, "name", "new variable name"),),
    "setunit":     (_p("unit", _STR, "unit", "e.g. K, mm/day"),),
    "setlevel":    (_p("level", _STR, "level"),),
    "setltype":    (_p("ltype", _INT, "ltype", "GRIB level type"),),
    "setdate":     (_p("date", _STR, "date", "YYYY-MM-DD"),),
    "settime":     (_p("time", _STR, "time", "HH:MM"),),
    "setday":      (_p("day", _INT, "day", "1–31"),),
    "setmon":      (_p("month", _INT, "month", "1–12"),),
    "setyear":     (_p("year", _INT, "year"),),
    "settunits":   (_p("units", _STR, "units", "e.g. days, hours"),),
    "settaxis":    (
        _p("date", _STR, "date", "start date (YYYY-MM-DD)"),
        _p("time", _STR, "time", "HH:MM"),
        _p("inc", _STR, "inc", "e.g. 6hour (optional)", optional=True),
    ),
    "settbounds":  (_p("frequency", _STR, "frequency",
                       "hour/day/month/year",
                       choices=("hour", "day", "month", "year")),),
    "setreftime":  (
        _p("date", _STR, "date", "reference date (YYYY-MM-DD)"),
        _p("time", _STR, "time", "reference time (HH:MM)"),
        _p("units", _STR, "units", "optional", optional=True),
    ),
    "setcalendar": (_p("calendar", _STR, "calendar",
                       choices=("standard", "proleptic_gregorian", "gregorian",
                                "360_day", "365_day", "366_day")),),
    "setmaxsteps": (_p("nsteps", _INT, "nsteps"),),
    "setmissval":  (_p("miss", _FLOAT, "miss", "missing value"),),
    "setctomiss":  (_p("c", _FLOAT, "c", "constant"),),
    "setmisstoc":  (_p("c", _FLOAT, "c", "constant"),),
    "setrtomiss":  (
        _p("rmin", _FLOAT, "rmin"),
        _p("rmax", _FLOAT, "rmax"),
    ),
    "setvals":     (_p("pairs", _STR, "pairs", "oldval,newval,..."),),
    "setvrange":   (
        _p("rmin", _FLOAT, "rmin"),
        _p("rmax", _FLOAT, "rmax"),
    ),
    "setattribute":(_p("attrs", _STR, "attrs", "e.g. name@units=K"),),
    "shifttime":   (_p("sval", _STR, "sval", "e.g. 1day, -6hour"),),
    "shiftx":      (_p("nshift", _INT, "nshift", optional=True),),
    "shifty":      (_p("nshift", _INT, "nshift", optional=True),),
    "chcode":      (_p("pairs", _STR, "oldcode,newcode,...",
                       "comma-separated old/new code pairs"),),
    "chname":      (_p("pairs", _STR, "ovar,nvar,...",
                       "comma-separated old/new variable name pairs"),),
    "chvar":       (_p("pairs", _STR, "ovar,nvar,..."),),
    "chunit":      (_p("pairs", _STR, "oldunit,newunit,..."),),
    "chparam":     (_p("pairs", _STR, "oldparam,newparam,..."),),
    "chlevel":     (_p("pairs", _STR, "oldlev,newlev,..."),),
    "chlevelc":    (
        _p("code", _INT, "code"),
        _p("oldlev", _STR, "oldlev"),
        _p("newlev", _STR, "newlev"),
    ),
    "chlevelv":    (
        _p("var", _STR, "var"),
        _p("oldlev", _STR, "oldlev"),
        _p("newlev", _STR, "newlev"),
    ),
    "chltype":     (
        _p("oldtype", _INT, "oldtype"),
        _p("newtype", _INT, "newtype"),
    ),
    "chtabnum":    (
        _p("oldtab", _INT, "oldtab"),
        _p("newtab", _INT, "newtab"),
    ),
    "setgrid":     (_p("grid", _GRID, "grid", "preset or grid file",
                       choices=GRID_PRESETS),),
    "setgridtype": (_p("gridtype", _STR, "gridtype",
                       choices=("curvilinear", "unstructured",
                                "regular", "regularnn", "lonlat",
                                "dereference", "cell")),),
    "setgridarea": (_p("grid", _GRID, "grid (area file)"),),
    "setgridmask": (_p("grid", _GRID, "grid (mask file)"),),
    "setzaxis":    (_p("zaxis", _FILE, "zaxis", "z-axis description file"),),
    "setgatt":     (
        _p("attname", _STR, "attname"),
        _p("attstring", _STR, "attstring"),
    ),
    "setgatts":    (_p("attfile", _FILE, "attfile", "attribute file"),),
    "sethalo":     (
        _p("lhalo", _INT, "lhalo"),
        _p("rhalo", _INT, "rhalo"),
    ),
    "maskregion":  (_p("regions", _FILE, "regions", "ASCII region file"),),
    "masklonlatbox":(
        _p("lon1", _FLOAT, "lon1"),
        _p("lon2", _FLOAT, "lon2"),
        _p("lat1", _FLOAT, "lat1"),
        _p("lat2", _FLOAT, "lat2"),
    ),
    "maskindexbox":(
        _p("idx1", _INT, "idx1"),
        _p("idx2", _INT, "idx2"),
        _p("idy1", _INT, "idy1"),
        _p("idy2", _INT, "idy2"),
    ),
    "maskcircle":  (
        _p("lon0", _FLOAT, "lon0"),
        _p("lat0", _FLOAT, "lat0"),
        _p("r", _FLOAT, "radius"),
    ),
    "setclonlatbox":(
        _p("c", _FLOAT, "c", "constant"),
        _p("lon1", _FLOAT, "lon1"),
        _p("lon2", _FLOAT, "lon2"),
        _p("lat1", _FLOAT, "lat1"),
        _p("lat2", _FLOAT, "lat2"),
    ),
    "setcindexbox":(
        _p("c", _FLOAT, "c", "constant"),
        _p("idx1", _INT, "idx1"),
        _p("idx2", _INT, "idx2"),
        _p("idy1", _INT, "idy1"),
        _p("idy2", _INT, "idy2"),
    ),
    "enlarge":     (_p("grid", _GRID, "grid", choices=GRID_PRESETS),),
    "ncopy":       (),

    # ---------- Arithmetic ----------
    "expr":        (_p("instr", _STR, "instr", "e.g. tas=var*2"),),
    "exprf":       (_p("filename", _FILE, "filename", "expression script file"),),
    "aexpr":       (_p("instr", _STR, "instr"),),
    "aexprf":      (_p("filename", _FILE, "filename"),),
    "addc":        (_p("c", _FLOAT, "c (constant)"),),
    "subc":        (_p("c", _FLOAT, "c (constant)"),),
    "mulc":        (_p("c", _FLOAT, "c (constant)"),),
    "divc":        (_p("c", _FLOAT, "c (constant)"),),

    # ---------- Statistical: percentile / running / time-range ----------
    "fldpctl":     (_p("p", _FLOAT, "p (percentile)", "0–100"),),
    "zonpctl":     (_p("p", _FLOAT, "p (percentile)"),),
    "merpctl":     (_p("p", _FLOAT, "p (percentile)"),),
    "enspctl":     (_p("p", _FLOAT, "p (percentile)"),),
    "timpctl":     (_p("p", _FLOAT, "p (percentile)"),),
    "monpctl":     (_p("p", _FLOAT, "p (percentile)"),),
    "yearpctl":    (_p("p", _FLOAT, "p (percentile)"),),
    "seaspctl":    (_p("p", _FLOAT, "p (percentile)"),),
    "daypctl":     (_p("p", _FLOAT, "p (percentile)"),),
    "hourpctl":    (_p("p", _FLOAT, "p (percentile)"),),
    "ydaypctl":    (_p("p", _FLOAT, "p (percentile)"),),
    "ymonpctl":    (_p("p", _FLOAT, "p (percentile)"),),
    "yseaspctl":   (_p("p", _FLOAT, "p (percentile)"),),
    "ydrunpctl":   (
        _p("p", _FLOAT, "p (percentile)"),
        _p("nts", _INT, "nts", "window length"),
    ),
    "timselpctl":  (
        _p("p", _FLOAT, "p (percentile)"),
        _p("nsets", _INT, "nsets"),
        _p("noffset", _INT, "noffset", optional=True),
        _p("nskip", _INT, "nskip", optional=True),
    ),
    "runpctl":     (
        _p("p", _FLOAT, "p (percentile)"),
        _p("nts", _INT, "nts", "window length"),
    ),
    "timselmin":   (_p("nsets", _INT, "nsets"),
                    _p("noffset", _INT, "noffset", optional=True),
                    _p("nskip", _INT, "nskip", optional=True)),
    "timselmax":   (_p("nsets", _INT, "nsets"),
                    _p("noffset", _INT, "noffset", optional=True),
                    _p("nskip", _INT, "nskip", optional=True)),
    "timselsum":   (_p("nsets", _INT, "nsets"),
                    _p("noffset", _INT, "noffset", optional=True),
                    _p("nskip", _INT, "nskip", optional=True)),
    "timselmean":  (_p("nsets", _INT, "nsets"),
                    _p("noffset", _INT, "noffset", optional=True),
                    _p("nskip", _INT, "nskip", optional=True)),
    "timselavg":   (_p("nsets", _INT, "nsets"),
                    _p("noffset", _INT, "noffset", optional=True),
                    _p("nskip", _INT, "nskip", optional=True)),
    "timselvar":   (_p("nsets", _INT, "nsets"),
                    _p("noffset", _INT, "noffset", optional=True),
                    _p("nskip", _INT, "nskip", optional=True)),
    "timselstd":   (_p("nsets", _INT, "nsets"),
                    _p("noffset", _INT, "noffset", optional=True),
                    _p("nskip", _INT, "nskip", optional=True)),
    "timselrange":(_p("nsets", _INT, "nsets"),
                    _p("noffset", _INT, "noffset", optional=True),
                    _p("nskip", _INT, "nskip", optional=True)),
    "runmin":      (_p("nts", _INT, "nts", "window length"),),
    "runmax":      (_p("nts", _INT, "nts", "window length"),),
    "runsum":      (_p("nts", _INT, "nts", "window length"),),
    "runmean":     (_p("nts", _INT, "nts", "window length"),),
    "runavg":      (_p("nts", _INT, "nts", "window length"),),
    "runvar":      (_p("nts", _INT, "nts", "window length"),),
    "runstd":      (_p("nts", _INT, "nts", "window length"),),
    "runrange":    (_p("nts", _INT, "nts", "window length"),),
    "ydrunmin":    (_p("nts", _INT, "nts", "window length"),),
    "ydrunmax":    (_p("nts", _INT, "nts", "window length"),),
    "ydrunsum":    (_p("nts", _INT, "nts", "window length"),),
    "ydrunmean":   (_p("nts", _INT, "nts", "window length"),),
    "ydrunavg":    (_p("nts", _INT, "nts", "window length"),),
    "ydrunvar":    (_p("nts", _INT, "nts", "window length"),),
    "ydrunstd":    (_p("nts", _INT, "nts", "window length"),),
    "gridboxmin":  (_p("nx", _INT, "nx"), _p("ny", _INT, "ny")),
    "gridboxmax":  (_p("nx", _INT, "nx"), _p("ny", _INT, "ny")),
    "gridboxsum":  (_p("nx", _INT, "nx"), _p("ny", _INT, "ny")),
    "gridboxmean": (_p("nx", _INT, "nx"), _p("ny", _INT, "ny")),
    "gridboxavg":  (_p("nx", _INT, "nx"), _p("ny", _INT, "ny")),
    "gridboxstd":  (_p("nx", _INT, "nx"), _p("ny", _INT, "ny")),
    "gridboxvar":  (_p("nx", _INT, "nx"), _p("ny", _INT, "ny")),
    "gridboxrange":(_p("nx", _INT, "nx"), _p("ny", _INT, "ny")),
    "boxavg":      (_p("nx", _INT, "nx"), _p("ny", _INT, "ny")),

    # ---------- Interpolation ----------
    "remapbil":    (_p("grid", _GRID, "grid", choices=GRID_PRESETS),),
    "remapbic":    (_p("grid", _GRID, "grid", choices=GRID_PRESETS),),
    "remapcon":    (_p("grid", _GRID, "grid", choices=GRID_PRESETS),),
    "remapcon2":   (_p("grid", _GRID, "grid", choices=GRID_PRESETS),),
    "remapdis":    (_p("grid", _GRID, "grid", choices=GRID_PRESETS),),
    "remapnn":     (_p("grid", _GRID, "grid", choices=GRID_PRESETS),),
    "remaplaf":    (_p("grid", _GRID, "grid", choices=GRID_PRESETS),),
    "remapycon":   (_p("grid", _GRID, "grid", choices=GRID_PRESETS),),
    "remapsum":    (_p("grid", _GRID, "grid", choices=GRID_PRESETS),),
    "genbil":      (_p("grid", _GRID, "grid", choices=GRID_PRESETS),),
    "genbic":      (_p("grid", _GRID, "grid", choices=GRID_PRESETS),),
    "gencon":      (_p("grid", _GRID, "grid", choices=GRID_PRESETS),),
    "gencon2":     (_p("grid", _GRID, "grid", choices=GRID_PRESETS),),
    "gendis":      (_p("grid", _GRID, "grid", choices=GRID_PRESETS),),
    "genlaf":      (_p("grid", _GRID, "grid", choices=GRID_PRESETS),),
    "gennn":       (_p("grid", _GRID, "grid", choices=GRID_PRESETS),),
    "genycon":     (_p("grid", _GRID, "grid", choices=GRID_PRESETS),),
    "genscon":     (_p("grid", _GRID, "grid", choices=GRID_PRESETS),),
    "remap":       (
        _p("grid", _GRID, "grid", choices=GRID_PRESETS),
        _p("weights", _FILE, "weights", "pre-computed weight file"),
    ),
    "interpolate": (_p("grid", _GRID, "grid", choices=GRID_PRESETS),),
    "intgridbil":  (_p("grid", _GRID, "grid", choices=GRID_PRESETS),),
    "intgriddis":  (_p("grid", _GRID, "grid", choices=GRID_PRESETS),),
    "intgridnn":   (_p("grid", _GRID, "grid", choices=GRID_PRESETS),),
    "intgrid":     (_p("grid", _GRID, "grid", choices=GRID_PRESETS),),
    "intgridtraj":(_p("grid", _GRID, "grid"),),
    "remapeta":    (
        _p("vct", _FILE, "vct", "vertical coordinate table"),
        _p("oro", _FILE, "oro", "orography (optional)", optional=True),
    ),
    "intlevel":    (_p("levels", _STR, "levels", "comma-separated levels"),),
    "intlevelx":   (_p("levels", _STR, "levels", "comma-separated levels"),),
    "ml2pl":       (_p("plevels", _STR, "plevels", "pressure levels (Pa)"),),
    "ml2plx":      (_p("plevels", _STR, "plevels"),),
    "ml2hl":       (_p("hlevels", _STR, "hlevels", "height levels (m)"),),
    "ml2hlx":      (_p("hlevels", _STR, "hlevels"),),
    "ap2pl":       (_p("plevels", _STR, "plevels"),),
    "ap2plx":      (_p("plevels", _STR, "plevels"),),
    "ap2hl":       (_p("hlevels", _STR, "hlevels"),),
    "ap2hlx":      (_p("hlevels", _STR, "hlevels"),),
    "inttime":     (
        _p("date", _STR, "date", "start date (YYYY-MM-DD)"),
        _p("time", _STR, "time", "HH:MM"),
        _p("inc", _STR, "inc", "e.g. 6hour (optional)", optional=True),
    ),
    "intntime":    (_p("n", _INT, "n", "number of timesteps"),),
    "intyear":     (_p("years", _STR, "years", "e.g. 1981/2010"),),

    # ---------- Transformation ----------
    "sp2sp":       (_p("trunc", _INT, "trunc", "truncation"),),
    "spcut":       (_p("wnums", _STR, "wnums", "wave numbers"),),

    # ---------- Split / formatted ----------
    "splitsel":    (
        _p("nsets", _INT, "nsets"),
        _p("noffset", _INT, "noffset", optional=True),
        _p("nskip", _INT, "nskip", optional=True),
    ),
    "splittabnum": (_p("tabnums", _STR, "tabnums", optional=True),),
    "input":       (_p("grid", _GRID, "grid", choices=GRID_PRESETS),),
    "outputf":     (
        _p("format", _STR, "format", "C-style format"),
        _p("nelem", _INT, "nelem", "elements per record"),
    ),
    "outputtab":   (_p("keys", _STR, "keys", "comma-separated keys"),),
    "outputkey":   (_p("keys", _STR, "keys", "comma-separated keys"),),

    # ---------- Miscellaneous ----------
    "setrtoc":     (
        _p("rmin", _FLOAT, "rmin"),
        _p("rmax", _FLOAT, "rmax"),
        _p("c", _FLOAT, "c"),
    ),
    "setrtoc2":    (
        _p("rmin", _FLOAT, "rmin"),
        _p("rmax", _FLOAT, "rmax"),
        _p("c", _FLOAT, "c"),
        _p("c2", _FLOAT, "c2"),
    ),
    "const":       (
        _p("const", _FLOAT, "constant"),
        _p("grid", _GRID, "grid", choices=GRID_PRESETS),
    ),
    "random":      (
        _p("grid", _GRID, "grid", choices=GRID_PRESETS),
        _p("seed", _INT, "seed", optional=True),
    ),
    "for":         (
        _p("start", _FLOAT, "start"),
        _p("stop", _FLOAT, "stop"),
        _p("step", _FLOAT, "step", optional=True),
    ),
    "seq":         (
        _p("start", _FLOAT, "start"),
        _p("stop", _FLOAT, "stop"),
        _p("step", _FLOAT, "step", optional=True),
    ),
    "mask":        (_p("grid", _GRID, "grid", choices=GRID_PRESETS),),
    "rotuvb":      (_p("pairs", _STR, "u,v,...", "comma-separated U,V variable names"),),
    "mrotuvb":     (_p("pairs", _STR, "u,v,...", "comma-separated U,V variable names"),),
    "mrotuv":      (_p("pairs", _STR, "u,v,...", "comma-separated U,V variable names"),),
    "strwin":      (_p("v", _FLOAT, "v", "wind threshold", optional=True),),
    "histcount":   (_p("bins", _STR, "bins", "comma-separated bin edges"),),
    "histsum":     (_p("bins", _STR, "bins", "comma-separated bin edges"),),
    "histmean":    (_p("bins", _STR, "bins", "comma-separated bin edges"),),
    "histfreq":    (_p("bins", _STR, "bins", "comma-separated bin edges"),),
    "smooth":      (_p("options", _STR, "options", "e.g. nsmooth=3", optional=True),),
    "bandpass":    (_p("fmin", _FLOAT, "fmin"), _p("fmax", _FLOAT, "fmax")),
    "lowpass":     (_p("fcut", _FLOAT, "fcut"),),
    "highpass":    (_p("fcut", _FLOAT, "fcut"),),
    "import_binary":(_p("ctlfile", _FILE, "ctlfile", "GrADS descriptor"),),
    "import_cmsaf":(),
    "import_amsr": (),

    # ---------- ECA indices ----------
    "eca_csu":     (_p("T", _FLOAT, "T", "temperature threshold", optional=True),),
    "eca_su":      (_p("T", _FLOAT, "T", "temperature threshold", optional=True),),
    "eca_tr":      (_p("T", _FLOAT, "T", "temperature threshold", optional=True),),
    "eca_gsl":     (
        _p("nday", _INT, "nday", "minimal duration", optional=True),
        _p("T", _FLOAT, "T", "threshold", optional=True),
    ),
    "eca_hd":      (
        _p("T1", _FLOAT, "T1", "lower threshold", optional=True),
        _p("T2", _FLOAT, "T2", "upper threshold", optional=True),
    ),
    "eca_cwdi":    (
        _p("nday", _INT, "nday", "minimal duration", optional=True),
        _p("T", _FLOAT, "T", "threshold", optional=True),
    ),
    "eca_cwfi":    (_p("nday", _INT, "nday", optional=True),),
    "eca_hwdi":    (
        _p("nday", _INT, "nday", "minimal duration", optional=True),
        _p("T", _FLOAT, "T", "threshold", optional=True),
    ),
    "eca_hwfi":    (_p("nday", _INT, "nday", optional=True),),
    "eca_rx1day":  (_p("mode", _STR, "mode",
                       choices=("m", "monthly"), optional=True),),
    "eca_rx5day":  (_p("x", _FLOAT, "x", "threshold", optional=True),),
    "eca_pd":      (_p("x", _FLOAT, "x", "threshold"),),
}


def _infer_category(op: str, nin: int, nout: int) -> "NCExplorerCategory":
    """Fallback category assignment for operators not in the curated menu list."""
    if op in CATEGORY_FOR_OPERATOR:
        return CATEGORY_FOR_OPERATOR[op]
    if nout == 0:
        return NCExplorerCategory.INFORMATION
    if op.startswith("eca_") or op.startswith("etccdi"):
        return NCExplorerCategory.ECA_INDICES
    if op.startswith("split") or op in {"copy", "cat", "merge", "mergetime",
                                         "replace", "delete"}:
        return NCExplorerCategory.FILE_OPERATIONS
    if op.startswith("sel") or op.startswith("del"):
        return NCExplorerCategory.SELECTION
    if op.startswith(("remap", "gen", "intgrid", "intlevel", "intntime",
                      "inttime", "intyear", "ml2", "ap2")):
        return NCExplorerCategory.INTERPOLATION
    if op.startswith(("sp2", "gp2", "uv2", "dv2", "fc2", "fourier",
                      "grid2fourier")):
        return NCExplorerCategory.TRANSFORMATION
    if op.startswith("set") or op.startswith("ch") or op.startswith("invert") \
            or op.startswith("mask") or op.startswith("shift") \
            or op in {"enlarge", "sethalo"}:
        return NCExplorerCategory.MODIFICATION
    if op.startswith(("fld", "zon", "mer", "vert", "ens", "tim", "run",
                      "hour", "day", "mon", "year", "seas", "yday",
                      "ymon", "yseas", "ydrun", "gridbox", "hist")):
        return NCExplorerCategory.STATISTICAL_VALUES
    if op.startswith("if") or op in {"ifthen", "ifnotthen", "ifthenelse"}:
        return NCExplorerCategory.CONDITIONAL_SELECTION
    if op in {"eq", "ne", "le", "lt", "ge", "gt", "eqc", "nec", "lec",
              "ltc", "gec", "gtc", "maxc", "minc"}:
        return NCExplorerCategory.COMPARISON
    if op in {"detrend", "trend", "subtrend", "addtrend", "regres"}:
        return NCExplorerCategory.REGRESSION
    if op in {"expr", "exprf", "aexpr", "aexprf"} or op.endswith("c") or \
            op in {"abs", "int", "nint", "sqr", "sqrt", "exp", "ln",
                   "log", "log10", "sin", "cos", "tan", "asin", "acos",
                   "atan", "atan2", "add", "sub", "mul", "div", "min",
                   "max", "muldpm", "divdpm", "muldpy", "divdpy", "muldoy"}:
        return NCExplorerCategory.ARITHMETIC
    if op.startswith("output") or op.startswith("input"):
        return NCExplorerCategory.FORMATTED_IO
    return NCExplorerCategory.MISCELLANEOUS


def _build_operator_schema() -> Dict[str, OperatorSpec]:
    """Build OPERATOR_SCHEMA from the CDO 2.6.0 catalog.

    Signatures and descriptions come from ``cdo --operators`` (via
    ``cdo_operator_catalog.CDO_OPERATORS``). Hand-curated ``OPERATOR_SIGNATURES``
    is merged in for compatibility, but the catalog wins on signature
    conflicts so the schema cannot diverge from the installed CDO binary.
    Operators present only in the catalog (not historically in the schema)
    are added; operators in ``OPERATOR_SIGNATURES`` but not in the catalog
    (dropped upstream) are skipped.
    """
    from .cdo_operator_catalog import CDO_OPERATORS

    schema: Dict[str, OperatorSpec] = {}
    for op, (nin, nout, desc) in CDO_OPERATORS.items():
        params = _PARAM_SPECS.get(op, ())
        schema[op] = OperatorSpec(
            name=op,
            nin=nin,
            nout=nout,
            category=_infer_category(op, nin, nout),
            params=params,
            description=desc,
        )
    return schema


OPERATOR_SCHEMA: Dict[str, OperatorSpec] = _build_operator_schema()


def get_operator_spec(name: str) -> "OperatorSpec | None":
    """Return the canonical spec for ``name`` or ``None`` if unknown."""
    return OPERATOR_SCHEMA.get(name)


# Schema-derived convenience tables.  These replace the hand-maintained
# ``EXTRA_PARAM_COUNTS`` in ``nc_integration.py`` and the ``extra_map`` in
# ``main_window.py``.

def operator_required_param_count(name: str) -> int:
    spec = OPERATOR_SCHEMA.get(name)
    if spec is None:
        return 0
    return sum(1 for p in spec.params if not p.optional)


def operator_total_param_count(name: str) -> int:
    spec = OPERATOR_SCHEMA.get(name)
    if spec is None:
        return 0
    return len(spec.params)