"""Auto-generated CDO 2.6.0 operator catalog with descriptions.

Signatures come from ``cdo --operators``.
Descriptions merged from the CDO User Guide PDF (cdo.pdf, Release 2.6.0):
  1. "Name" section headings (``op1, op2, ... - description``)
  2. Per-operator entries inside "Operators" blocks
  3. Fallback to the short description from ``cdo --operators``
"""

from __future__ import annotations

CDO_OPERATORS: dict[str, tuple[int, int, str]] = {
    "abs": (1, 1, "Mathematical functions"),
    "acos": (1, 1, "Mathematical functions"),
    "add": (2, 1, "Arithmetic on two datasets"),
    "addc": (1, 1, "Arithmetic with a constant"),
    "addtrend": (3, 1, "Add or subtract a trend"),
    "adipot": (1, 1, "Potential temperature to in-situ temperature and vice versa"),
    "adisit": (1, 1, "Potential temperature to in-situ temperature and vice versa"),
    "aexpr": (1, 1, "Evaluate expressions"),
    "aexprf": (1, 1, "Evaluate expressions"),
    "after": (-1, 1, "ECHAM standard post processor"),
    "afterburner": (-1, 1, "--> after"),
    "air_density": (1, 1, "Derived model parameters"),
    "anomaly": (2, 1, "--> ymonsub"),
    "ap2hl": (1, 1, ""),
    "ap2hlx": (1, 1, ""),
    "ap2pl": (1, 1, "Vertical pressure interpolation"),
    "ap2plx": (1, 1, ""),
    "arg": (1, 1, ""),
    "asin": (1, 1, "Mathematical functions"),
    "atan": (1, 1, "Mathematical functions"),
    "atan2": (2, 1, "Arithmetic on two datasets"),
    "bandpass": (1, 1, "Time series filtering"),
    "bitrounding": (1, 1, "Bit rounding"),
    "bottomvalue": (1, 1, "Extract surface"),
    "boxavg": (1, 1, ""),
    "cat": (-1, 1, "Copy datasets"),
    "cdiread": (1, 0, ""),
    "cdiwrite": (0, 1, ""),
    "changemulti": (1, 1, "Select multiple fields via GRIB1 parameters"),
    "chcode": (1, 1, "Change field header"),
    "chlevel": (1, 1, "Change field header"),
    "chlevelc": (1, 1, "Change field header"),
    "chlevelv": (1, 1, "Change field header"),
    "chltype": (1, 1, ""),
    "chname": (1, 1, "Change field header"),
    "chparam": (1, 1, "Change field header"),
    "chtabnum": (1, 1, ""),
    "chunit": (1, 1, "Change field header"),
    "chvar": (1, 1, "--> chname"),
    "cinfo": (-1, 0, "Information and simple statistics"),
    "clone": (-1, 1, "Copy datasets"),
    "cloudlayer": (1, 1, ""),
    "cmor": (1, 0, "Climate Model Output Rewriting to produce CMIP-compliant data"),
    "cmorlite": (1, 1, "CMOR lite"),
    "codetab": (1, 0, "Dataset description"),
    "collgrid": (-1, 1, "Collect horizontal grid"),
    "complextopol": (1, 2, ""),
    "complextorect": (1, 2, ""),
    "conj": (1, 1, ""),
    "consecsum": (1, 1, "Consecute timestep periods"),
    "consects": (1, 1, "Consecute timestep periods"),
    "const": (0, 1, "Generate a field"),
    "contour": (1, 1, "Lon/Lat plot"),
    "conv_cmor_table": (0, 0, ""),
    "copy": (-1, 1, "Copy datasets"),
    "cos": (1, 1, "Mathematical functions"),
    "coshill": (0, 1, ""),
    "dayadd": (2, 1, "Daily arithmetic"),
    "dayavg": (1, 1, "Daily statistics"),
    "daycount": (1, 1, ""),
    "daydiv": (2, 1, "Daily arithmetic"),
    "daymax": (1, 1, "Daily statistics"),
    "daymean": (1, 1, "Daily statistics"),
    "daymin": (1, 1, "Daily statistics"),
    "daymul": (2, 1, "Daily arithmetic"),
    "daypctl": (3, 1, "Daily percentile"),
    "dayrange": (1, 1, "Daily statistics"),
    "daystd": (1, 1, "Daily statistics"),
    "daystd1": (1, 1, "Daily statistics"),
    "daysub": (2, 1, "Daily arithmetic"),
    "daysum": (1, 1, "Daily statistics"),
    "dayvar": (1, 1, "Daily statistics"),
    "dayvar1": (1, 1, "Daily statistics"),
    "dcw": (0, 0, ""),
    "del29feb": (1, 1, ""),
    "delattribute": (1, 1, "Set attributes"),
    "delcode": (1, 1, "Delete parameters by code number"),
    "delday": (1, 1, ""),
    "delete": (-1, 1, "Select fields"),
    "delgridcell": (1, 1, "Select grid cells"),
    "delmulti": (1, 1, "Select multiple fields via GRIB1 parameters"),
    "delname": (1, 1, "Delete parameters by name"),
    "delparam": (1, 1, "Delete parameters by identifier"),
    "delta_pressure": (1, 1, "Pressure on model levels"),
    "deltat": (1, 1, "Difference between timesteps"),
    "delvar": (1, 1, "--> delname"),
    "detrend": (1, 1, "Detrend time series"),
    "dhouravg": (1, 1, "Multi-day hourly average"),
    "dhourmax": (1, 1, "Multi-day hourly maximum"),
    "dhourmean": (1, 1, "Multi-day hourly mean"),
    "dhourmin": (1, 1, "Multi-day hourly minimum"),
    "dhourrange": (1, 1, "Multi-day hourly range"),
    "dhourstd": (1, 1, ""),
    "dhourstd1": (1, 1, ""),
    "dhoursum": (1, 1, "Multi-day hourly sum"),
    "dhourvar": (1, 1, ""),
    "dhourvar1": (1, 1, ""),
    "diff": (2, 0, "Compare two datasets field by field"),
    "diffc": (2, 0, ""),
    "diffn": (2, 0, "Compare two datasets field by field"),
    "diffp": (2, 0, ""),
    "difftest": (2, 0, ""),
    "diffv": (2, 0, "--> diffn"),
    "distgrid": (1, -1, "Distribute horizontal grid"),
    "div": (2, 1, "Arithmetic on two datasets"),
    "divc": (1, 1, "Arithmetic with a constant"),
    "divcoslat": (1, 1, "Arithmetic with latitude"),
    "divdpm": (1, 1, "Arithmetic with days"),
    "divdpy": (1, 1, "Arithmetic with days"),
    "dminuteavg": (1, 1, "Multi-day by the minute average"),
    "dminutemax": (1, 1, "Multi-day by the minute maximum"),
    "dminutemean": (1, 1, "Multi-day by the minute mean"),
    "dminutemin": (1, 1, "Multi-day by the minute minimum"),
    "dminuterange": (1, 1, "Multi-day by the minute range"),
    "dminutestd": (1, 1, ""),
    "dminutestd1": (1, 1, ""),
    "dminutesum": (1, 1, "Multi-day by the minute sum"),
    "dminutevar": (1, 1, ""),
    "dminutevar1": (1, 1, ""),
    "dump_cmor_table": (0, 0, ""),
    "dumpmap": (1, 0, ""),
    "duplicate": (1, 1, "Duplicates a dataset"),
    "dv2ps": (1, 1, "D and V to vel"),
    "dv2uv": (1, 1, "Wind transformation"),
    "dv2uvl": (1, 1, ""),
    "eca_cdd": (1, 1, "Consecutive dry days index per time period"),
    "eca_cfd": (1, 1, "Consecutive frost days index per time period"),
    "eca_csu": (1, 1, "Consecutive summer days index per time period"),
    "eca_cwd": (1, 1, "Consecutive wet days index per time period"),
    "eca_cwdi": (2, 1, "Cold wave duration index wrt mean of reference period"),
    "eca_cwfi": (2, 1, "Cold-spell days index wrt 10th percentile of reference period"),
    "eca_etr": (2, 1, "Intra-period extreme temperature range"),
    "eca_fd": (1, 1, "Frost days index per time period"),
    "eca_gsl": (2, 1, "Thermal Growing season length index"),
    "eca_hd": (1, 1, "Heating degree days per time period"),
    "eca_hwdi": (2, 1, "Heat wave duration index wrt mean of reference period"),
    "eca_hwfi": (2, 1, "Warm spell index"),
    "eca_id": (1, 1, "Ice days index per time period"),
    "eca_pd": (1, 1, "Precipitation days index per time period"),
    "eca_r10mm": (1, 1, "Precipitation days index per time period"),
    "eca_r1mm": (1, 1, "--> eca_rr1"),
    "eca_r20mm": (1, 1, "Precipitation days index per time period"),
    "eca_r75p": (2, 1, "Moderate wet days wrt 75th percentile of reference period"),
    "eca_r75ptot": (2, 1, "Precipitation percent due to R75p days"),
    "eca_r90p": (2, 1, "Wet days wrt 90th percentile of reference period"),
    "eca_r90ptot": (2, 1, "Precipitation percent due to R90p days"),
    "eca_r95p": (2, 1, "Very wet days wrt 95th percentile of reference period"),
    "eca_r95ptot": (2, 1, "Precipitation percent due to R95p days"),
    "eca_r99p": (2, 1, "Extremely wet days wrt 99th percentile of reference period"),
    "eca_r99ptot": (2, 1, "Precipitation percent due to R99p days"),
    "eca_rr1": (1, 1, "Wet days index per time period"),
    "eca_rx1day": (1, 1, "Highest one day precipitation amount per time period"),
    "eca_rx5day": (1, 1, "Highest five-day precipitation amount per time period"),
    "eca_sdii": (1, 1, "Simple daily intensity index per time period"),
    "eca_su": (1, 1, "Summer days index per time period"),
    "eca_tg10p": (2, 1, "Cold days percent wrt 10th percentile of reference period"),
    "eca_tg90p": (2, 1, "Warm days percent wrt 90th percentile of reference period"),
    "eca_tn10p": (2, 1, "Cold nights percent wrt 10th percentile of reference period"),
    "eca_tn90p": (2, 1, "Warm nights percent wrt 90th percentile of reference period"),
    "eca_tr": (1, 1, "Tropical nights index per time period"),
    "eca_tx10p": (2, 1, "Very cold days percent wrt 10th percentile of reference period"),
    "eca_tx90p": (2, 1, "Very warm days percent wrt 90th percentile of reference period"),
    "enlarge": (1, 1, "Enlarge fields"),
    "ensavg": (-1, 1, "Ensemble average"),
    "ensbrs": (-1, -1, "Ensemble validation tools"),
    "enscrps": (-1, -1, "Ensemble validation tools"),
    "enskurt": (-1, 1, ""),
    "ensmax": (-1, 1, "Ensemble maximum"),
    "ensmean": (-1, 1, "Ensemble mean"),
    "ensmedian": (-1, 1, ""),
    "ensmin": (-1, 1, "Ensemble minimum"),
    "enspctl": (-1, 1, ""),
    "ensrange": (-1, 1, "Ensemble range"),
    "ensrkhistspace": (-1, 1, "Statistical values over an ensemble"),
    "ensrkhisttime": (-1, 1, "Statistical values over an ensemble"),
    "ensroc": (-1, 1, "Statistical values over an ensemble"),
    "ensskew": (-1, 1, ""),
    "ensstd": (-1, 1, "Ensemble standard deviation"),
    "ensstd1": (-1, 1, "Ensemble standard deviation (n-1)"),
    "enssum": (-1, 1, "Ensemble sum"),
    "ensvar": (-1, 1, "Ensemble variance"),
    "ensvar1": (-1, 1, ""),
    "eof": (1, 2, "Empirical Orthogonal Functions"),
    "eof3d": (1, 2, "Empirical Orthogonal Functions"),
    "eof3dspatial": (1, 2, ""),
    "eof3dtime": (1, 2, ""),
    "eofcoeff": (2, -1, "Principal coefficients of EOFs"),
    "eofcoeff3d": (2, -1, ""),
    "eofspatial": (1, 2, "Empirical Orthogonal Functions"),
    "eoftime": (1, 2, "Empirical Orthogonal Functions"),
    "eq": (2, 1, "Comparison of two fields"),
    "eqc": (1, 1, "Comparison of a field with a constant"),
    "etccdi": (3, 1, ""),
    "etccdi_cdd": (1, 1, "Consecutive dry days index per time period"),
    "etccdi_csdi": (2, 1, "Cold-spell days index wrt 10th percentile of reference period"),
    "etccdi_cwd": (1, 1, "Consecutive wet days index per time period"),
    "etccdi_fd": (1, 1, "Frost days index per time period"),
    "etccdi_gsl": (2, 1, ""),
    "etccdi_hd": (1, 1, ""),
    "etccdi_id": (1, 1, "Ice days index per time period"),
    "etccdi_r10mm": (1, 1, ""),
    "etccdi_r1mm": (1, 1, "Precipitation days index per time period"),
    "etccdi_r20mm": (1, 1, ""),
    "etccdi_r95p": (3, 1, "ETCCDI conform index for a"),
    "etccdi_r99p": (3, 1, "ETCCDI conform index for a"),
    "etccdi_rx1day": (1, 1, "Highest one day precipitation amount per time period"),
    "etccdi_rx1daymon": (1, 1, ""),
    "etccdi_rx5day": (1, 1, "Highest five-day precipitation amount per time period"),
    "etccdi_rx5daymon": (1, 1, ""),
    "etccdi_sdii": (1, 1, ""),
    "etccdi_su": (1, 1, "Summer days index per time period"),
    "etccdi_tn10p": (3, 1, "ETCCDI conform index for a"),
    "etccdi_tn90p": (3, 1, "ETCCDI conform index for a"),
    "etccdi_tr": (1, 1, "Tropical nights index per time period"),
    "etccdi_tx10p": (3, 1, "ETCCDI conform index for a"),
    "etccdi_tx90p": (3, 1, "ETCCDI conform index for a"),
    "etccdi_wsdi": (2, 1, "Warm spell index"),
    "exp": (1, 1, "Mathematical functions"),
    "export_e5ml": (1, 1, ""),
    "expr": (1, 1, "Evaluate expressions"),
    "exprf": (1, 1, "Evaluate expressions"),
    "fc2gp": (1, 1, ""),
    "fc2sp": (1, 1, ""),
    "fdns": (2, 1, "Frost days where no snow index per time period"),
    "filedes": (1, 0, ""),
    "fillmiss": (1, 1, ""),
    "fillmiss2": (1, 1, ""),
    "fldavg": (1, 1, "Field average"),
    "fldcor": (2, 1, "Correlation in grid space"),
    "fldcount": (1, 1, ""),
    "fldcovar": (2, 1, "Covariance in grid space"),
    "fldint": (1, 1, "Field integral"),
    "fldkurt": (1, 1, ""),
    "fldmax": (1, 1, "Field maximum"),
    "fldmean": (1, 1, "Field mean"),
    "fldmedian": (1, 1, ""),
    "fldmin": (1, 1, "Field minimum"),
    "fldpctl": (1, 1, ""),
    "fldrange": (1, 1, "Field range"),
    "fldrms": (2, 1, ""),
    "fldskew": (1, 1, ""),
    "fldstd": (1, 1, "Field standard deviation"),
    "fldstd1": (1, 1, ""),
    "fldsum": (1, 1, "Field sum"),
    "fldvar": (1, 1, "Field variance"),
    "fldvar1": (1, 1, ""),
    "for": (0, 1, "--> seq"),
    "fourier": (1, 1, "Fourier transformation"),
    "fourier2grid": (1, 1, ""),
    "ge": (2, 1, "Comparison of two fields"),
    "gec": (1, 1, "Comparison of a field with a constant"),
    "genbic": (1, 1, "Bicubic interpolation"),
    "genbil": (1, 1, "Bilinear interpolation"),
    "gencon": (1, 1, "First order conservative remapping"),
    "gendis": (1, 1, "k-nearest neighbor remapping"),
    "gengrid": (2, 1, ""),
    "genknn": (1, 1, "k-nearest neighbor remapping"),
    "genlaf": (1, 1, "Largest area fraction remapping"),
    "genlevelbounds": (1, 1, "Set z-axis information"),
    "gennn": (1, 1, "k-nearest neighbor remapping"),
    "genycon": (1, 1, "--> gencon"),
    "genycon2test": (1, 1, ""),
    "gh2hl": (1, 1, "Geometric height interpolation"),
    "gh2hlx": (1, 1, ""),
    "gheight": (1, 1, "Derived model parameters"),
    "gheight_full": (1, 1, "--> gheight"),
    "gheight_half": (1, 1, "Derived model parameters"),
    "gheighthalf": (1, 1, "--> gheight_half"),
    "globavg": (1, 1, "--> fldavg"),
    "gmtcells": (1, 0, "GMT output"),
    "gmtxyz": (1, 0, "GMT output"),
    "gp2fc": (1, 1, ""),
    "gp2sp": (1, 1, "Spectral transformation"),
    "gp2spl": (1, 1, ""),
    "gradsdes": (1, 0, "GrADS data descriptor file"),
    "graph": (-1, 1, "Line graph plot"),
    "grfill": (1, 1, "Lon/Lat plot"),
    "grid2fourier": (1, 1, ""),
    "gridarea": (1, 1, "Grid cell quantities"),
    "gridboxavg": (1, 1, "Gridbox average"),
    "gridboxkurt": (1, 1, "Gridbox kurtosis"),
    "gridboxmax": (1, 1, "Gridbox maximum"),
    "gridboxmean": (1, 1, "Gridbox mean"),
    "gridboxmedian": (1, 1, "Gridbox median"),
    "gridboxmin": (1, 1, "Gridbox minimum"),
    "gridboxrange": (1, 1, "Gridbox range"),
    "gridboxskew": (1, 1, "Gridbox skewness"),
    "gridboxstd": (1, 1, "Gridbox standard deviation"),
    "gridboxstd1": (1, 1, "Gridbox standard deviation (n-1)"),
    "gridboxsum": (1, 1, "Gridbox sum"),
    "gridboxvar": (1, 1, "Gridbox variance"),
    "gridboxvar1": (1, 1, "Gridbox variance (n-1)"),
    "gridcellidx": (1, 1, ""),
    "gridcellindex": (1, 0, "Get grid cell index"),
    "griddes": (1, 0, "Dataset description"),
    "griddes2": (1, 0, ""),
    "griddx": (1, 1, ""),
    "griddy": (1, 1, ""),
    "gridmask": (1, 1, ""),
    "gridweights": (1, 1, "Grid cell quantities"),
    "gt": (2, 1, "Comparison of two fields"),
    "gtc": (1, 1, "Comparison of a field with a constant"),
    "harmonic": (1, 1, ""),
    "hi": (3, 1, ""),
    "highpass": (1, 1, "Time series filtering"),
    "histcount": (1, 1, "Histogram"),
    "histfreq": (1, 1, "Histogram"),
    "histmean": (1, 1, "Histogram"),
    "histsum": (1, 1, "Histogram"),
    "houravg": (1, 1, "Hourly statis-"),
    "hourcount": (1, 1, ""),
    "hourmax": (1, 1, "Hourly statis-"),
    "hourmean": (1, 1, "Hourly statis-"),
    "hourmin": (1, 1, "Hourly statis-"),
    "hourpctl": (3, 1, "Hourly percentile"),
    "hourrange": (1, 1, "Hourly statis-"),
    "hourstd": (1, 1, "Hourly statis-"),
    "hourstd1": (1, 1, "Hourly statis-"),
    "hoursum": (1, 1, "Hourly statis-"),
    "hourvar": (1, 1, "Hourly statis-"),
    "hourvar1": (1, 1, "Hourly statis-"),
    "hpdegrade": (1, 1, "Change healpix resolution"),
    "hpupgrade": (1, 1, "Change healpix resolution"),
    "hurr": (1, 1, "Hurricane days index per time period"),
    "ifnotthen": (2, 1, "Conditional selection"),
    "ifnotthenc": (1, 1, "Conditional selection"),
    "ifthen": (2, 1, "Conditional selection"),
    "ifthenc": (1, 1, "Conditional selection"),
    "ifthenelse": (3, 1, "Conditional selection"),
    "im": (1, 1, ""),
    "import_binary": (1, 1, "Import binary data sets"),
    "import_cmsaf": (1, 1, "Import CM-SAF HDF5 files"),
    "import_e5ml": (1, 1, ""),
    "import_fv3grid": (1, 1, ""),
    "import_grads": (1, 1, "--> import_binary"),
    "import_obs": (1, 1, ""),
    "imtocomplex": (1, 1, ""),
    "info": (-1, 0, "Information and simple statistics"),
    "infoc": (-1, 0, ""),
    "infon": (-1, 0, "Information and simple statistics"),
    "infop": (-1, 0, ""),
    "infov": (-1, 0, "--> infon"),
    "input": (0, 1, "Formatted input"),
    "inputext": (0, 1, "Formatted input"),
    "inputsrv": (0, 1, "Formatted input"),
    "int": (1, 1, "Mathematical functions"),
    "intgridbil": (1, 1, ""),
    "intgriddis": (1, 1, ""),
    "intgridknn": (1, 1, ""),
    "intgridnn": (1, 1, ""),
    "intgridtraj": (1, 1, ""),
    "intlevel": (1, 1, "Linear level interpolation"),
    "intlevel3d": (2, 1, "Linear level interpolation from/to 3D vertical coordinates"),
    "intlevelx": (1, 1, ""),
    "intlevelx3d": (2, 1, ""),
    "intntime": (1, 1, "Time interpolation"),
    "inttime": (1, 1, "Time interpolation"),
    "intyear": (2, -1, "Interpolation between two years"),
    "invertlat": (1, 1, "Invert latitudes"),
    "invertlatdata": (1, 1, ""),
    "invertlatdes": (1, 1, ""),
    "invertlev": (1, 1, "Invert levels"),
    "invertlon": (1, 1, ""),
    "invertlondata": (1, 1, ""),
    "invertlondes": (1, 1, ""),
    "isosurface": (1, 1, "Extract surface"),
    "le": (2, 1, "Comparison of two fields"),
    "lec": (1, 1, "Comparison of a field with a constant"),
    "lic": (1, 1, ""),
    "linfo": (1, 0, ""),
    "ln": (1, 1, "Mathematical functions"),
    "log": (1, 1, "--> ln"),
    "log10": (1, 1, "Mathematical functions"),
    "lowpass": (1, 1, "Time series filtering"),
    "lt": (2, 1, "Comparison of two fields"),
    "ltc": (1, 1, "Comparison of a field with a constant"),
    "map": (-1, 0, "Information and simple statistics"),
    "mask": (0, 1, ""),
    "maskcircle": (1, 1, ""),
    "maskindexbox": (1, 1, "Mask a box"),
    "masklonlatbox": (1, 1, "Mask a box"),
    "maskregion": (1, 1, "Mask regions"),
    "mastrfu": (1, 1, "Mass stream function"),
    "max": (2, 1, "Arithmetic on two datasets"),
    "maxc": (1, 1, "Arithmetic with a constant"),
    "meandiff2test": (2, 1, ""),
    "meravg": (1, 1, "Meridional average"),
    "merge": (-1, 1, "Merge datasets"),
    "mergegrid": (2, 1, "Merge grid"),
    "mergetime": (-1, 1, "Merge datasets"),
    "merkurt": (1, 1, "Meridional kurtosis"),
    "mermax": (1, 1, "Meridional maximum"),
    "mermean": (1, 1, "Meridional mean"),
    "mermedian": (1, 1, "Meridional median"),
    "mermin": (1, 1, "Meridional minimum"),
    "merpctl": (1, 1, "Meridional percentile"),
    "merrange": (1, 1, "Meridional range"),
    "merskew": (1, 1, "Meridional skewness"),
    "merstd": (1, 1, "Meridional standard deviation"),
    "merstd1": (1, 1, "Meridional standard deviation (n-1)"),
    "mersum": (1, 1, "Meridional sum"),
    "mervar": (1, 1, "Meridional variance"),
    "mervar1": (1, 1, "Meridional variance (n-1)"),
    "min": (2, 1, "Arithmetic on two datasets"),
    "minc": (1, 1, "Arithmetic with a constant"),
    "ml2hl": (1, 1, ""),
    "ml2hlx": (1, 1, ""),
    "ml2pl": (1, 1, "Model to pressure level interpolation"),
    "ml2plx": (1, 1, ""),
    "mod": (1, 1, ""),
    "monadd": (2, 1, "Monthly arithmetic"),
    "monavg": (1, 1, "Monthly statis-"),
    "moncount": (1, 1, ""),
    "mondiv": (2, 1, "Monthly arithmetic"),
    "monmax": (1, 1, "Monthly statis-"),
    "monmean": (1, 1, "Monthly statis-"),
    "monmin": (1, 1, "Monthly statis-"),
    "monmul": (2, 1, "Monthly arithmetic"),
    "monpctl": (3, 1, "Monthly percentile"),
    "monrange": (1, 1, "Monthly statis-"),
    "monstd": (1, 1, "Monthly statis-"),
    "monstd1": (1, 1, "Monthly statis-"),
    "monsub": (2, 1, "Monthly arithmetic"),
    "monsum": (1, 1, "Monthly statis-"),
    "monvar": (1, 1, "Monthly statis-"),
    "monvar1": (1, 1, "Monthly statis-"),
    "mrotuv": (1, 2, ""),
    "mrotuvb": (2, 1, "Backward rotation of MPIOM data"),
    "mul": (2, 1, "Arithmetic on two datasets"),
    "mulc": (1, 1, "Arithmetic with a constant"),
    "mulcoslat": (1, 1, "Arithmetic with latitude"),
    "muldoy": (1, 1, ""),
    "muldpm": (1, 1, "Arithmetic with days"),
    "muldpy": (1, 1, "Arithmetic with days"),
    "ncode": (1, 0, ""),
    "ncopy": (1, 1, ""),
    "ndate": (1, 0, "Print the number of parameters, levels or times"),
    "ne": (2, 1, "Comparison of two fields"),
    "nec": (1, 1, "Comparison of a field with a constant"),
    "ngridpoints": (1, 0, "Print the number of parameters, levels or times"),
    "ngrids": (1, 0, "Print the number of parameters, levels or times"),
    "nint": (1, 1, "Mathematical functions"),
    "nlevel": (1, 0, "Print the number of parameters, levels or times"),
    "nmon": (1, 0, "Print the number of parameters, levels or times"),
    "not": (1, 1, "Mathematical functions"),
    "npar": (1, 0, "Print the number of parameters, levels or times"),
    "ntime": (1, 0, "Print the number of parameters, levels or times"),
    "nvar": (1, 0, "--> npar"),
    "nyear": (1, 0, "Print the number of parameters, levels or times"),
    "output": (-1, 0, "Formatted output"),
    "outputarr": (-1, 0, ""),
    "outputbounds": (1, 0, "--> gmtcells"),
    "outputboundscpt": (1, 0, ""),
    "outputcenter": (1, 0, "--> gmtxyz"),
    "outputcenter2": (1, 0, ""),
    "outputcentercpt": (1, 0, ""),
    "outputext": (-1, 0, "Formatted output"),
    "outputf": (-1, 0, "Formatted output"),
    "outputfld": (-1, 0, ""),
    "outputint": (-1, 0, "Formatted output"),
    "outputkey": (-1, 0, "--> outputtab"),
    "outputkml": (1, 0, ""),
    "outputsrv": (-1, 0, "Formatted output"),
    "outputtab": (-1, 0, "Table output"),
    "outputtri": (1, 0, ""),
    "outputts": (-1, 0, ""),
    "outputvector": (1, 0, ""),
    "outputvrml": (1, 0, ""),
    "outputxyz": (-1, 0, ""),
    "pack": (1, 1, "Pack data"),
    "pardup": (1, 1, ""),
    "parmul": (1, 1, ""),
    "partab": (1, 0, "Dataset description"),
    "partab2": (1, 0, ""),
    "pinfo": (1, 1, ""),
    "pinfov": (1, 1, ""),
    "pow": (1, 1, "Mathematical functions"),
    "pressure": (1, 1, "Pressure on model levels"),
    "pressure_full": (1, 1, "--> pressure"),
    "pressure_half": (1, 1, "Pressure on model levels"),
    "projuvLatLon": (1, 1, ""),
    "query": (1, 1, ""),
    "rand": (1, 1, ""),
    "random": (0, 1, "Generate a field"),
    "re": (1, 1, ""),
    "reci": (1, 1, "Mathematical functions"),
    "recttocomplex": (2, 1, ""),
    "reducegrid": (1, 1, "Reduce fields to user-defined mask"),
    "regres": (1, 1, "Regression"),
    "remap": (1, 1, "Grid remapping"),
    "remapavg": (1, 1, "Remap average"),
    "remapavgtest": (1, 1, ""),
    "remapbic": (1, 1, "Bicubic interpolation"),
    "remapbil": (1, 1, "Bilinear interpolation"),
    "remapcon": (1, 1, "First order conservative remapping"),
    "remapdis": (1, 1, "k-nearest neighbor remapping"),
    "remapeta": (1, 1, "Remap vertical hybrid levels"),
    "remapeta_s": (1, 1, ""),
    "remapeta_z": (1, 1, ""),
    "remapknn": (1, 1, "k-nearest neighbor remapping"),
    "remapkurt": (1, 1, ""),
    "remaplaf": (1, 1, "Largest area fraction remapping"),
    "remapmax": (1, 1, "Remap maximum"),
    "remapmean": (1, 1, "Remap mean"),
    "remapmedian": (1, 1, ""),
    "remapmin": (1, 1, "Remap minimum"),
    "remapnn": (1, 1, "k-nearest neighbor remapping"),
    "remaprange": (1, 1, "Remap range"),
    "remapskew": (1, 1, ""),
    "remapstd": (1, 1, "Remap standard deviation"),
    "remapstd1": (1, 1, "Remap standard deviation (n-1)"),
    "remapsum": (1, 1, "Remap sum"),
    "remapvar": (1, 1, "Remap variance"),
    "remapvar1": (1, 1, "Remap variance (n-1)"),
    "remapycon": (1, 1, "--> remapcon"),
    "remapycon2test": (1, 1, ""),
    "replace": (2, 1, "Replace variables"),
    "retocomplex": (1, 1, ""),
    "rhopot": (1, 1, "Calculates potential density"),
    "rotuvN": (1, 1, ""),
    "rotuvNorth": (1, 1, ""),
    "rotuvb": (1, 1, "Backward wind rotation"),
    "runavg": (1, 1, "Running statistics"),
    "runmax": (1, 1, "Running statistics"),
    "runmean": (1, 1, "Running statistics"),
    "runmin": (1, 1, "Running statistics"),
    "runpctl": (1, 1, "Running percentile"),
    "runrange": (1, 1, "Running statistics"),
    "runstd": (1, 1, "Running statistics"),
    "runstd1": (1, 1, "Running statistics"),
    "runsum": (1, 1, "Running statistics"),
    "runvar": (1, 1, "Running statistics"),
    "runvar1": (1, 1, "Running statistics"),
    "samplegrid": (1, 1, "Resample grid cells"),
    "samplegridicon": (1, 2, ""),
    "sealevelpressure": (1, 1, "Derived model parameters"),
    "seasavg": (1, 1, "Seasonal statistics"),
    "seascount": (1, 1, ""),
    "seasmax": (1, 1, "Seasonal statistics"),
    "seasmean": (1, 1, "Seasonal statistics"),
    "seasmin": (1, 1, "Seasonal statistics"),
    "seasmonavg": (1, 1, ""),
    "seasmonmean": (1, 1, ""),
    "seaspctl": (3, 1, "Seasonal percentile"),
    "seasrange": (1, 1, "Seasonal statistics"),
    "seasstd": (1, 1, "Seasonal statistics"),
    "seasstd1": (1, 1, "Seasonal statistics"),
    "seassum": (1, 1, "Seasonal statistics"),
    "seasvar": (1, 1, "Seasonal statistics"),
    "seasvar1": (1, 1, "Seasonal statistics"),
    "seinfo": (-1, 0, ""),
    "seinfoc": (-1, 0, ""),
    "seinfon": (-1, 0, ""),
    "seinfop": (-1, 0, ""),
    "selcircle": (1, 1, "Select horizontal regions"),
    "selcode": (1, 1, "Select parameters by code number"),
    "seldate": (1, 1, "Select timesteps"),
    "selday": (1, 1, "Select timesteps"),
    "select": (-1, 1, "Select fields"),
    "selgrid": (1, 1, "Select grids"),
    "selgridcell": (1, 1, "Select grid cells"),
    "selgridname": (1, 1, "--> selgrid"),
    "selhour": (1, 1, "Select timesteps"),
    "selindexbox": (1, 1, "Select a box"),
    "sellevel": (1, 1, "Select levels"),
    "sellevidx": (1, 1, "Select levels by index"),
    "sellonlatbox": (1, 1, "Select a box"),
    "selltype": (1, 1, ""),
    "selmon": (1, 1, "--> selmonth"),
    "selmonth": (1, 1, "Select timesteps"),
    "selmulti": (1, 1, "Select multiple fields via GRIB1 parameters"),
    "selname": (1, 1, "Select parameters by name"),
    "seloperator": (1, 1, ""),
    "selparam": (1, 1, "Select parameters by identifier"),
    "selrec": (1, 1, ""),
    "selregion": (1, 1, "Select horizontal regions"),
    "selseas": (1, 1, "--> selseason"),
    "selseason": (1, 1, "Select timesteps"),
    "selsmon": (1, 1, "Select timesteps"),
    "selstdname": (1, 1, "Select parameters by standard name"),
    "seltabnum": (1, 1, ""),
    "seltime": (1, 1, "Select timesteps"),
    "seltimeidx": (2, 1, "Select timestep by index"),
    "seltimestep": (1, 1, "Select timesteps"),
    "selvar": (1, 1, "--> selname"),
    "selyear": (1, 1, "Select timesteps"),
    "selyearidx": (2, 1, "Select year by index"),
    "selzaxis": (1, 1, ""),
    "selzaxisname": (1, 1, ""),
    "seq": (0, 1, "Generate a field"),
    "setattribute": (1, 1, "Set attributes"),
    "setcalendar": (1, 1, "Set time"),
    "setchunkspec": (1, 1, "Specify chunking"),
    "setcindexbox": (1, 1, "Set a box to constant"),
    "setclonlatbox": (1, 1, "Set a box to constant"),
    "setcode": (1, 1, "Set field info"),
    "setcodetab": (1, 1, "Set field info"),
    "setctomiss": (1, 1, "Set missing value"),
    "setdate": (1, 1, "Set time"),
    "setday": (1, 1, "Set time"),
    "setfilter": (1, 1, "Specify filter"),
    "setgrid": (1, 1, "Set grid information"),
    "setgridarea": (1, 1, "Set grid information"),
    "setgridcell": (1, 1, "Set the value of a grid cell"),
    "setgridmask": (1, 1, "Set grid information"),
    "setgridnumber": (1, 1, ""),
    "setgridtype": (1, 1, "Set grid information"),
    "setgriduri": (1, 1, ""),
    "sethalo": (1, 1, "Set the bounds of a field"),
    "setlevel": (1, 1, "Set field info"),
    "setltype": (1, 1, "Set field info"),
    "setmaxsteps": (1, 1, "Set field info"),
    "setmiss": (2, 1, "Arithmetic on two datasets"),
    "setmisstoc": (1, 1, "Set missing value"),
    "setmisstodis": (1, 1, "Set missing value"),
    "setmisstonn": (1, 1, "Set missing value"),
    "setmissval": (1, 1, "Set missing value"),
    "setmon": (1, 1, "Set time"),
    "setname": (1, 1, "Set field info"),
    "setparam": (1, 1, "Set field info"),
    "setpartab": (1, 1, "--> setcodetab"),
    "setpartabc": (1, 1, ""),
    "setpartabn": (1, 1, "Set parameter table"),
    "setpartabp": (1, 1, "Set parameter table"),
    "setpartabv": (1, 1, "--> setpartabn"),
    "setprojparams": (1, 1, "Set grid information"),
    "setrcaname": (1, 1, ""),
    "setreftime": (1, 1, "Set time"),
    "setrtoc": (1, 1, "Replace data values"),
    "setrtoc2": (1, 1, "Replace data values"),
    "setrtomiss": (1, 1, "Set missing value"),
    "setstdname": (1, 1, "Set field info"),
    "settabnum": (1, 1, ""),
    "settaxis": (1, 1, "Set time"),
    "settbounds": (1, 1, "Set time"),
    "settime": (1, 1, "Set time"),
    "settunits": (1, 1, "Set time"),
    "setunit": (1, 1, "Set field info"),
    "setvals": (1, 1, "Replace data values"),
    "setvar": (1, 1, "--> setname"),
    "setvrange": (1, 1, "Set missing value"),
    "setyear": (1, 1, "Set time"),
    "setzaxis": (1, 1, "Set z-axis information"),
    "shaded": (1, 1, "Lon/Lat plot"),
    "shifttime": (1, 1, "Set time"),
    "shiftx": (1, 1, "Shift field"),
    "shifty": (1, 1, "Shift field"),
    "showattribute": (1, 0, "Show attributes"),
    "showattsvar": (1, 0, ""),
    "showchunkspec": (1, 0, ""),
    "showcode": (1, 0, "Show code numbers"),
    "showdate": (1, 0, "Show date information"),
    "showfilter": (1, 0, ""),
    "showformat": (1, 0, "Show file format"),
    "showgrid": (1, 0, ""),
    "showhistory": (1, 0, ""),
    "showlevel": (1, 0, "Show levels"),
    "showltype": (1, 0, "Show GRIB level types"),
    "showmon": (1, 0, "Show months"),
    "showname": (1, 0, "Show variable names"),
    "showparam": (1, 0, ""),
    "showstdname": (1, 0, "Show standard names"),
    "showtime": (1, 0, "Show time information"),
    "showtimestamp": (1, 0, ""),
    "showunit": (1, 0, ""),
    "showvar": (1, 0, "--> showname"),
    "showyear": (1, 0, "Show years"),
    "sin": (1, 1, "Mathematical functions"),
    "sincos": (0, 1, ""),
    "sinfo": (-1, 0, "Short information"),
    "sinfoc": (-1, 0, ""),
    "sinfon": (-1, 0, "Short information"),
    "sinfop": (-1, 0, ""),
    "sinfov": (-1, 0, "--> sinfon"),
    "smooth": (1, 1, "Smooth grid points"),
    "smooth9": (1, 1, "Smooth grid points"),
    "sortcode": (1, 1, ""),
    "sortlevel": (1, 1, ""),
    "sortname": (1, 1, ""),
    "sortparam": (1, 1, ""),
    "sorttaxis": (-1, 1, ""),
    "sorttimestamp": (-1, 1, ""),
    "sortvar": (1, 1, "--> sortname"),
    "sp2fc": (1, 1, ""),
    "sp2gp": (1, 1, "Spectral transformation"),
    "sp2gpl": (1, 1, ""),
    "sp2sp": (1, 1, "Spectral to spectral"),
    "spartab": (1, 0, ""),
    "spcut": (1, 1, ""),
    "specinfo": (0, 0, ""),
    "spectrum": (1, 1, ""),
    "splitcode": (1, -1, "Split a dataset"),
    "splitdate": (1, -1, "Splits a file into dates"),
    "splitdatetime": (1, -1, ""),
    "splitday": (1, -1, "Split timesteps of a dataset"),
    "splitensemble": (1, -1, "Split a dataset"),
    "splitgrid": (1, -1, "Split a dataset"),
    "splithour": (1, -1, "Split timesteps of a dataset"),
    "splitlevel": (1, -1, "Split a dataset"),
    "splitmon": (1, -1, "Split timesteps of a dataset"),
    "splitname": (1, -1, "Split a dataset"),
    "splitparam": (1, -1, "Split a dataset"),
    "splitrec": (1, -1, ""),
    "splitseas": (1, -1, "Split timesteps of a dataset"),
    "splitsel": (1, -1, "Split selected timesteps"),
    "splittabnum": (1, -1, "Split a dataset"),
    "splitvar": (1, -1, "--> splitname"),
    "splityear": (1, -1, "Split timesteps of a dataset"),
    "splityearmon": (1, -1, "Split timesteps of a dataset"),
    "splitzaxis": (1, -1, "Split a dataset"),
    "sqr": (1, 1, "Mathematical functions"),
    "sqrt": (1, 1, "Mathematical functions"),
    "stdatm": (0, 1, "Generate a field"),
    "strbre": (1, 1, "Strong breeze days index per time period"),
    "stream": (1, 1, ""),
    "strgal": (1, 1, "Strong gale days index per time period"),
    "strwin": (1, 1, "Strong wind days index per time period"),
    "sub": (2, 1, "Arithmetic on two datasets"),
    "subc": (1, 1, "Arithmetic with a constant"),
    "subgrid": (1, 1, ""),
    "subtrend": (3, 1, "Add or subtract a trend"),
    "symmetrize": (1, 1, "Mirrors data at the equator"),
    "szip": (-1, 1, ""),
    "tan": (1, 1, "Mathematical functions"),
    "tee": (1, 1, "Duplicate a data stream and write it to file"),
    "temp": (0, 1, ""),
    "testcellsearch": (0, 0, ""),
    "testfield": (0, 1, ""),
    "testpointsearch": (0, 0, ""),
    "thinout": (1, 1, ""),
    "timavg": (1, 1, "Time average"),
    "timcor": (2, 1, "Correlation over time"),
    "timcount": (1, 1, ""),
    "timcovar": (2, 1, "Covariance over time"),
    "timcumsum": (1, 1, "Cumulative sum over all timesteps"),
    "timederivative": (1, 1, ""),
    "timfillmiss": (1, 1, "Temporal filling of missing values"),
    "timmax": (1, 1, "Time maximum"),
    "timmaxidx": (1, 1, "Index of time maximum"),
    "timmean": (1, 1, "Time mean"),
    "timmin": (1, 1, "Time minimum"),
    "timminidx": (1, 1, "Index of time minimum"),
    "timpctl": (3, 1, "Temporal percentile"),
    "timrange": (1, 1, "Time range"),
    "timrmsd": (2, 1, ""),
    "timselavg": (1, 1, "Time selection average"),
    "timselmax": (1, 1, "Time selection maximum"),
    "timselmean": (1, 1, "Time selection mean"),
    "timselmin": (1, 1, "Time selection minimum"),
    "timselpctl": (3, 1, "Time range percentile"),
    "timselrange": (1, 1, "Time selection range"),
    "timselstd": (1, 1, ""),
    "timselstd1": (1, 1, ""),
    "timselsum": (1, 1, "Time selection sum"),
    "timselvar": (1, 1, "Time selection variance"),
    "timselvar1": (1, 1, ""),
    "timsort": (1, 1, "Temporal sorting"),
    "timstd": (1, 1, "Time standard deviation"),
    "timstd1": (1, 1, "Time standard deviation (n-1)"),
    "timsum": (1, 1, "Time sum"),
    "timvar": (1, 1, "Time variance"),
    "timvar1": (1, 1, "Time variance (n-1)"),
    "tinfo": (1, 0, ""),
    "topo": (0, 1, "Generate a field"),
    "topvalue": (1, 1, "Extract surface"),
    "tpnhalo": (1, 1, ""),
    "transxy": (1, 1, ""),
    "trend": (1, 2, "Trend of time series"),
    "tstepcount": (1, 1, ""),
    "unpack": (1, 1, "Unpack data"),
    "unsetgridmask": (1, 1, ""),
    "usegridnumber": (1, 1, ""),
    "uv2dv": (1, 1, "Wind transformation"),
    "uv2dv_cfd": (1, 1, "Wind transformation"),
    "uv2dvl": (1, 1, ""),
    "uv2vr_cfd": (1, 1, "Wind transformation"),
    "uvDestag": (1, 1, ""),
    "vardes": (1, 0, "--> codetab"),
    "varquot2test": (2, 1, ""),
    "varrms": (2, 1, ""),
    "varsavg": (1, 1, "Variables average"),
    "varskurt": (1, 1, ""),
    "varsmax": (1, 1, "Variables maximum"),
    "varsmean": (1, 1, "Variables mean"),
    "varsmedian": (1, 1, ""),
    "varsmin": (1, 1, "Variables minimum"),
    "varspctl": (1, 1, ""),
    "varsrange": (1, 1, "Variables range"),
    "varsskew": (1, 1, ""),
    "varsstd": (1, 1, "Variables standard deviation"),
    "varsstd1": (1, 1, "Variables standard deviation (n-1)"),
    "varssum": (1, 1, "Variables sum"),
    "varsvar": (1, 1, "Variables variance"),
    "varsvar1": (1, 1, "Variables variance (n-1)"),
    "vct": (1, 0, "Dataset description"),
    "vct2": (1, 0, ""),
    "vector": (1, 1, "Lon/Lat vector plot"),
    "verifygrid": (1, 0, "Verify grid coordinates"),
    "verifyweights": (0, 0, ""),
    "vertavg": (1, 1, "Vertical statistics"),
    "vertcum": (1, 1, ""),
    "vertcumhl": (1, 1, ""),
    "vertfillmiss": (1, 1, "Vertical filling of missing values"),
    "vertint": (1, 1, ""),
    "vertmax": (1, 1, "Vertical statistics"),
    "vertmean": (1, 1, "Vertical statistics"),
    "vertmin": (1, 1, "Vertical statistics"),
    "vertrange": (1, 1, "Vertical statistics"),
    "vertstd": (1, 1, "Vertical statistics"),
    "vertstd1": (1, 1, "Vertical statistics"),
    "vertsum": (1, 1, "Vertical statistics"),
    "vertvar": (1, 1, "Vertical statistics"),
    "vertvar1": (1, 1, "Vertical statistics"),
    "vertwind": (1, 1, ""),
    "vinfo": (-1, 0, ""),
    "vlist": (1, 0, ""),
    "wct": (2, 1, "Windchill temperature"),
    "writegrid": (1, 1, ""),
    "writerandom": (1, 1, ""),
    "writeremapscrip": (0, 0, ""),
    "xsinfo": (-1, 0, "Extra short information"),
    "xsinfoc": (-1, 0, ""),
    "xsinfon": (-1, 0, ""),
    "xsinfop": (-1, 0, "Extra short information"),
    "ydayadd": (2, 1, "Multi-year daily arithmetic"),
    "ydayavg": (1, 1, "Multi-year"),
    "ydaydiv": (2, 1, "Multi-year daily arithmetic"),
    "ydaymax": (1, 1, "Multi-year"),
    "ydaymean": (1, 1, "Multi-year"),
    "ydaymin": (1, 1, "Multi-year"),
    "ydaymul": (2, 1, "Multi-year daily arithmetic"),
    "ydaypctl": (3, 1, "Multi-year daily percentile"),
    "ydayrange": (1, 1, "Multi-year"),
    "ydaystd": (1, 1, "Multi-year"),
    "ydaystd1": (1, 1, "Multi-year"),
    "ydaysub": (2, 1, "Multi-year daily arithmetic"),
    "ydaysum": (1, 1, "Multi-year"),
    "ydayvar": (1, 1, "Multi-year"),
    "ydayvar1": (1, 1, "Multi-year"),
    "ydrunavg": (1, 1, "Multi-year"),
    "ydrunmax": (1, 1, "Multi-year"),
    "ydrunmean": (1, 1, "Multi-year"),
    "ydrunmin": (1, 1, "Multi-year"),
    "ydrunpctl": (3, 1, "Multi-year daily running percentile"),
    "ydrunstd": (1, 1, "Multi-year"),
    "ydrunstd1": (1, 1, "Multi-year"),
    "ydrunsum": (1, 1, "Multi-year"),
    "ydrunvar": (1, 1, "Multi-year"),
    "ydrunvar1": (1, 1, "Multi-year"),
    "yearadd": (2, 1, "Yearly arithmetic"),
    "yearavg": (1, 1, ""),
    "yearcount": (1, 1, ""),
    "yeardiv": (2, 1, "Yearly arithmetic"),
    "yearmax": (1, 1, "Yearly maximum"),
    "yearmaxidx": (1, 1, "Index of yearly maximum"),
    "yearmean": (1, 1, "Yearly mean"),
    "yearmin": (1, 1, "Yearly minimum"),
    "yearminidx": (1, 1, "Index of yearly minimum"),
    "yearmonavg": (1, 1, ""),
    "yearmonmean": (1, 1, "Yearly mean from monthly data"),
    "yearmul": (2, 1, "Yearly arithmetic"),
    "yearpctl": (3, 1, "Yearly percentile"),
    "yearrange": (1, 1, "Yearly range"),
    "yearstd": (1, 1, ""),
    "yearstd1": (1, 1, ""),
    "yearsub": (2, 1, "Yearly arithmetic"),
    "yearsum": (1, 1, "Yearly sum"),
    "yearvar": (1, 1, ""),
    "yearvar1": (1, 1, ""),
    "yhouradd": (2, 1, "Multi-year hourly arithmetic"),
    "yhouravg": (1, 1, "Multi-year hourly average"),
    "yhourdiv": (2, 1, "Multi-year hourly arithmetic"),
    "yhourmax": (1, 1, "Multi-year hourly maximum"),
    "yhourmean": (1, 1, "Multi-year hourly mean"),
    "yhourmin": (1, 1, "Multi-year hourly minimum"),
    "yhourmul": (2, 1, "Multi-year hourly arithmetic"),
    "yhourrange": (1, 1, "Multi-year hourly range"),
    "yhourstd": (1, 1, ""),
    "yhourstd1": (1, 1, ""),
    "yhoursub": (2, 1, "Multi-year hourly arithmetic"),
    "yhoursum": (1, 1, "Multi-year hourly sum"),
    "yhourvar": (1, 1, ""),
    "yhourvar1": (1, 1, ""),
    "ymonadd": (2, 1, "Multi-year monthly arithmetic"),
    "ymonavg": (1, 1, "Multi-year monthly average"),
    "ymondiv": (2, 1, "Multi-year monthly arithmetic"),
    "ymoneq": (2, 1, "Multi-year monthly comparison"),
    "ymonge": (2, 1, "Multi-year monthly comparison"),
    "ymongt": (2, 1, "Multi-year monthly comparison"),
    "ymonle": (2, 1, "Multi-year monthly comparison"),
    "ymonlt": (2, 1, "Multi-year monthly comparison"),
    "ymonmax": (1, 1, "Multi-year monthly maximum"),
    "ymonmean": (1, 1, "Multi-year monthly mean"),
    "ymonmin": (1, 1, "Multi-year monthly minimum"),
    "ymonmul": (2, 1, "Multi-year monthly arithmetic"),
    "ymonne": (2, 1, "Multi-year monthly comparison"),
    "ymonpctl": (3, 1, "Multi-year monthly percentile"),
    "ymonrange": (1, 1, "Multi-year monthly range"),
    "ymonstd": (1, 1, "Multi-year monthly standard deviation"),
    "ymonstd1": (1, 1, "Multi-year monthly standard deviation (n-1)"),
    "ymonsub": (2, 1, "Multi-year monthly arithmetic"),
    "ymonsum": (1, 1, "Multi-year monthly sum"),
    "ymonvar": (1, 1, "Multi-year monthly variance"),
    "ymonvar1": (1, 1, "Multi-year monthly variance (n-1)"),
    "yseasadd": (2, 1, "Multi-year seasonal arithmetic"),
    "yseasavg": (1, 1, "Multi-"),
    "yseasdiv": (2, 1, "Multi-year seasonal arithmetic"),
    "yseaseq": (2, 1, "Multi-year seasonal comparison"),
    "yseasge": (2, 1, "Multi-year seasonal comparison"),
    "yseasgt": (2, 1, "Multi-year seasonal comparison"),
    "yseasle": (2, 1, "Multi-year seasonal comparison"),
    "yseaslt": (2, 1, "Multi-year seasonal comparison"),
    "yseasmax": (1, 1, "Multi-"),
    "yseasmean": (1, 1, "Multi-"),
    "yseasmin": (1, 1, "Multi-"),
    "yseasmul": (2, 1, "Multi-year seasonal arithmetic"),
    "yseasne": (2, 1, "Multi-year seasonal comparison"),
    "yseaspctl": (3, 1, "Multi-year seasonal percentile"),
    "yseasrange": (1, 1, "Multi-"),
    "yseasstd": (1, 1, "Multi-"),
    "yseasstd1": (1, 1, "Multi-"),
    "yseassub": (2, 1, "Multi-year seasonal arithmetic"),
    "yseassum": (1, 1, "Multi-"),
    "yseasvar": (1, 1, "Multi-"),
    "yseasvar1": (1, 1, "Multi-"),
    "zaxisdes": (1, 0, "Dataset description"),
    "zonavg": (1, 1, "Zonal average"),
    "zonkurt": (1, 1, "Zonal kurtosis"),
    "zonmax": (1, 1, "Zonal maximum"),
    "zonmean": (1, 1, "Zonal mean"),
    "zonmedian": (1, 1, "Zonal median"),
    "zonmin": (1, 1, "Zonal minimum"),
    "zonpctl": (1, 1, "Zonal percentile"),
    "zonrange": (1, 1, "Zonal range"),
    "zonskew": (1, 1, "Zonal skewness"),
    "zonstd": (1, 1, "Zonal standard deviation"),
    "zonstd1": (1, 1, "Zonal standard deviation (n-1)"),
    "zonsum": (1, 1, "Zonal sum"),
    "zonvar": (1, 1, "Zonal variance"),
    "zonvar1": (1, 1, "Zonal variance (n-1)"),
    "zs2zl": (1, 1, ""),
    "zs2zlx": (1, 1, ""),
    "zsdepth": (1, 1, ""),
}
