# Copyright (c) 2026 Manish Shivach
# SPDX-License-Identifier: MIT
"""Auto-generated CDO 2.6.3 operator catalog with descriptions.

Signatures come from ``cdo --operators``.
Descriptions merged from the CDO User Guide PDF (cdo.pdf, Release 2.6.0):
  1. "Name" section headings (``op1, op2, ... - description``)
  2. Per-operator entries inside "Operators" blocks
  3. Fallback to the short description from ``cdo --operators``

``CDO_OPERATOR_MODULES`` below is regenerated from the installed binary by
``generate_operator_modules.py`` and is current for 2.6.3.

``CDO_OPERATORS`` is not regenerable by a committed script — its descriptions
were merged out of the 2.6.0 User Guide PDF, and there is no 2.6.3 PDF here — so
the 2.6.0 → 2.6.3 upgrade was reconciled against ``cdo --operators`` by hand, in
the four places the two disagreed:

  * ``timyearavg`` and ``timyearmean`` are new in 2.6.3 and were added. Their
    descriptions follow the same fallback the header describes: ``--operators``
    gives ``timyearmean`` a short description and ``timyearavg`` none, so
    ``timyearavg`` carries "" exactly as the other undescribed operators do.
  * ``hi`` and ``query`` are gone from 2.6.3 and were removed. Both carried an
    empty description and neither resolved to a module, so nothing referred to
    them.

Everything else is untouched: the descriptions the PDF supplied are still the
best text available for the operators that survived, and rewriting 939 of them
from ``--operators`` one-liners would lose information rather than refresh it.
"""

from __future__ import annotations

CDO_OPERATORS: dict[str, tuple[int, int, str]] = {
    "abs": (1, 1, "Absolute value"),
    "acos": (1, 1, "Arc cosine"),
    "add": (2, 1, "Arithmetic on two datasets"),
    "addc": (1, 1, "Arithmetic with a constant"),
    "addtrend": (3, 1, "Add a linear trend back to a dataset"),
    "adipot": (1, 1, "Potential temperature to in-situ temperature and vice versa"),
    "adisit": (1, 1, "Potential temperature to in-situ temperature and vice versa"),
    "aexpr": (1, 1, "Evaluate expressions and append results"),
    "aexprf": (1, 1, "Evaluate expression script and append results"),
    "after": (-1, 1, "ECHAM standard post processor"),
    "afterburner": (-1, 1, "--> after"),
    "air_density": (1, 1, "Derived model parameters"),
    "anomaly": (2, 1, "--> ymonsub"),
    "ap2hl": (1, 1, ""),
    "ap2hlx": (1, 1, ""),
    "ap2pl": (1, 1, "Vertical pressure interpolation"),
    "ap2plx": (1, 1, ""),
    "arg": (1, 1, ""),
    "asin": (1, 1, "Arc sine"),
    "atan": (1, 1, "Arc tangent"),
    "atan2": (2, 1, "Arithmetic on two datasets"),
    "bandpass": (1, 1, "Time series filtering"),
    "bitrounding": (1, 1, "Bit rounding"),
    "bottomvalue": (1, 1, "Extract surface"),
    "boxavg": (1, 1, ""),
    "cat": (-1, 1, "Concatenate datasets in time"),
    "cdiread": (1, 0, ""),
    "cdiwrite": (0, 1, ""),
    "changemulti": (1, 1, "Select multiple fields via GRIB1 parameters"),
    "chcode": (1, 1, "Change code number"),
    "chlevel": (1, 1, "Change level"),
    "chlevelc": (1, 1, "Change level of one code"),
    "chlevelv": (1, 1, "Change level of one variable"),
    "chltype": (1, 1, ""),
    "chname": (1, 1, "Change variable or coordinate name"),
    "chparam": (1, 1, "Change parameter identifier"),
    "chtabnum": (1, 1, ""),
    "chunit": (1, 1, "Change variable unit"),
    "chvar": (1, 1, "--> chname"),
    "cinfo": (-1, 0, "Information and simple statistics"),
    "clone": (-1, 1, "Clone datasets without decoding/decompressing GRIB records"),
    "cloudlayer": (1, 1, ""),
    "cmor": (1, 0, "Climate Model Output Rewriting to produce CMIP-compliant data"),
    "cmorlite": (1, 1, "CMOR lite"),
    "codetab": (1, 0, "Dataset description"),
    "collgrid": (-1, 1, "Collect horizontal grid"),
    "complextopol": (1, 2, ""),
    "complextorect": (1, 2, ""),
    "conj": (1, 1, ""),
    "consecsum": (1, 1, "Consecute timestep periods"),
    "consects": (1, 1, "Consecute timestep periods"),
    "const": (0, 1, "Generate a field"),
    "contour": (1, 1, "Lon/Lat plot"),
    "conv_cmor_table": (0, 0, ""),
    "copy": (-1, 1, "Copy datasets to a new file"),
    "cos": (1, 1, "Cosine"),
    "coshill": (0, 1, ""),
    "dayadd": (2, 1, "Daily arithmetic"),
    "dayavg": (1, 1, "Daily average"),
    "daycount": (1, 1, ""),
    "daydiv": (2, 1, "Daily arithmetic"),
    "daymax": (1, 1, "Daily maximum"),
    "daymean": (1, 1, "Daily mean"),
    "daymin": (1, 1, "Daily minimum"),
    "daymul": (2, 1, "Daily arithmetic"),
    "daypctl": (3, 1, "Daily percentile"),
    "dayrange": (1, 1, "Daily range"),
    "daystd": (1, 1, "Daily standard deviation"),
    "daystd1": (1, 1, "Daily standard deviation (n-1)"),
    "daysub": (2, 1, "Daily arithmetic"),
    "daysum": (1, 1, "Daily sum"),
    "dayvar": (1, 1, "Daily variance"),
    "dayvar1": (1, 1, "Daily variance (n-1)"),
    "dcw": (0, 0, ""),
    "del29feb": (1, 1, ""),
    "delattribute": (1, 1, "Set attributes"),
    "delcode": (1, 1, "Delete parameters by code number"),
    "delday": (1, 1, ""),
    "delete": (-1, 1, "Select fields"),
    "delgridcell": (1, 1, "Select grid cells"),
    "delmulti": (1, 1, "Select multiple fields via GRIB1 parameters"),
    "delname": (1, 1, "Delete parameters by name"),
    "delparam": (1, 1, "Delete parameters by identifier"),
    "delta_pressure": (1, 1, "Pressure on model levels"),
    "deltat": (1, 1, "Difference between timesteps"),
    "delvar": (1, 1, "--> delname"),
    "detrend": (1, 1, "Detrend time series"),
    "dhouravg": (1, 1, "Multi-day hourly average"),
    "dhourmax": (1, 1, "Multi-day hourly maximum"),
    "dhourmean": (1, 1, "Multi-day hourly mean"),
    "dhourmin": (1, 1, "Multi-day hourly minimum"),
    "dhourrange": (1, 1, "Multi-day hourly range"),
    "dhourstd": (1, 1, ""),
    "dhourstd1": (1, 1, ""),
    "dhoursum": (1, 1, "Multi-day hourly sum"),
    "dhourvar": (1, 1, ""),
    "dhourvar1": (1, 1, ""),
    "diff": (2, 0, "Compare two datasets field by field"),
    "diffc": (2, 0, ""),
    "diffn": (2, 0, "Compare two datasets field by field"),
    "diffp": (2, 0, ""),
    "difftest": (2, 0, ""),
    "diffv": (2, 0, "--> diffn"),
    "distgrid": (1, -1, "Distribute horizontal grid"),
    "div": (2, 1, "Arithmetic on two datasets"),
    "divc": (1, 1, "Arithmetic with a constant"),
    "divcoslat": (1, 1, "Arithmetic with latitude"),
    "divdpm": (1, 1, "Arithmetic with days"),
    "divdpy": (1, 1, "Arithmetic with days"),
    "dminuteavg": (1, 1, "Multi-day by the minute average"),
    "dminutemax": (1, 1, "Multi-day by the minute maximum"),
    "dminutemean": (1, 1, "Multi-day by the minute mean"),
    "dminutemin": (1, 1, "Multi-day by the minute minimum"),
    "dminuterange": (1, 1, "Multi-day by the minute range"),
    "dminutestd": (1, 1, ""),
    "dminutestd1": (1, 1, ""),
    "dminutesum": (1, 1, "Multi-day by the minute sum"),
    "dminutevar": (1, 1, ""),
    "dminutevar1": (1, 1, ""),
    "dump_cmor_table": (0, 0, ""),
    "dumpmap": (1, 0, ""),
    "duplicate": (1, 1, "Duplicates a dataset"),
    # The one description in this table that lost half of itself to a sentence
    # split: "vel. potential" reads as an end-of-sentence to the merge that
    # built this file, so everything after it was dropped. ``cdo --operators``
    # on 2.6.3 gives the whole line — "D and V to vel. potential and stream
    # function" — and it is restored here because the truncated form reached
    # the toolbar as "D and V to vel.", which names nothing. Checked against
    # the other 942 entries: this is the only one affected.
    "dv2ps": (1, 1, "D and V to velocity potential and stream function"),
    "dv2uv": (1, 1, "Divergence and vorticity to U and V wind"),
    "dv2uvl": (1, 1, ""),
    "eca_cdd": (1, 1, "Consecutive dry days index per time period"),
    "eca_cfd": (1, 1, "Consecutive frost days index per time period"),
    "eca_csu": (1, 1, "Consecutive summer days index per time period"),
    "eca_cwd": (1, 1, "Consecutive wet days index per time period"),
    "eca_cwdi": (2, 1, "Cold wave duration index wrt mean of reference period"),
    "eca_cwfi": (2, 1, "Cold-spell days index wrt 10th percentile of reference period"),
    "eca_etr": (2, 1, "Intra-period extreme temperature range"),
    "eca_fd": (1, 1, "Frost days index per time period"),
    "eca_gsl": (2, 1, "Thermal Growing season length index"),
    "eca_hd": (1, 1, "Heating degree days per time period"),
    "eca_hwdi": (2, 1, "Heat wave duration index wrt mean of reference period"),
    "eca_hwfi": (2, 1, "Warm spell days index wrt 90th percentile of reference period"),
    "eca_id": (1, 1, "Ice days index per time period"),
    "eca_pd": (1, 1, "Precipitation days index per time period"),
    "eca_r10mm": (1, 1, "Heavy precipitation days index per time period"),
    "eca_r1mm": (1, 1, "--> eca_rr1"),
    "eca_r20mm": (1, 1, "Very heavy precipitation days index per time period"),
    "eca_r75p": (2, 1, "Moderate wet days wrt 75th percentile of reference period"),
    "eca_r75ptot": (2, 1, "Precipitation percent due to R75p days"),
    "eca_r90p": (2, 1, "Wet days wrt 90th percentile of reference period"),
    "eca_r90ptot": (2, 1, "Precipitation percent due to R90p days"),
    "eca_r95p": (2, 1, "Very wet days wrt 95th percentile of reference period"),
    "eca_r95ptot": (2, 1, "Precipitation percent due to R95p days"),
    "eca_r99p": (2, 1, "Extremely wet days wrt 99th percentile of reference period"),
    "eca_r99ptot": (2, 1, "Precipitation percent due to R99p days"),
    "eca_rr1": (1, 1, "Wet days index per time period"),
    "eca_rx1day": (1, 1, "Highest one day precipitation amount per time period"),
    "eca_rx5day": (1, 1, "Highest five-day precipitation amount per time period"),
    "eca_sdii": (1, 1, "Simple daily intensity index per time period"),
    "eca_su": (1, 1, "Summer days index per time period"),
    "eca_tg10p": (2, 1, "Cold days percent wrt 10th percentile of reference period"),
    "eca_tg90p": (2, 1, "Warm days percent wrt 90th percentile of reference period"),
    "eca_tn10p": (2, 1, "Cold nights percent wrt 10th percentile of reference period"),
    "eca_tn90p": (2, 1, "Warm nights percent wrt 90th percentile of reference period"),
    "eca_tr": (1, 1, "Tropical nights index per time period"),
    "eca_tx10p": (2, 1, "Very cold days percent wrt 10th percentile of reference period"),
    "eca_tx90p": (2, 1, "Very warm days percent wrt 90th percentile of reference period"),
    "enlarge": (1, 1, "Enlarge fields"),
    "ensavg": (-1, 1, "Ensemble average"),
    "ensbrs": (-1, -1, "Ensemble validation tools"),
    "enscrps": (-1, -1, "Ensemble validation tools"),
    "enskurt": (-1, 1, ""),
    "ensmax": (-1, 1, "Ensemble maximum"),
    "ensmean": (-1, 1, "Ensemble mean"),
    "ensmedian": (-1, 1, ""),
    "ensmin": (-1, 1, "Ensemble minimum"),
    "enspctl": (-1, 1, "Ensemble percentile values"),
    "ensrange": (-1, 1, "Ensemble range"),
    "ensrkhistspace": (-1, 1, "Statistical values over an ensemble"),
    "ensrkhisttime": (-1, 1, "Statistical values over an ensemble"),
    "ensroc": (-1, 1, "Statistical values over an ensemble"),
    "ensskew": (-1, 1, ""),
    "ensstd": (-1, 1, "Ensemble standard deviation"),
    "ensstd1": (-1, 1, "Ensemble standard deviation (n-1)"),
    "enssum": (-1, 1, "Ensemble sum"),
    "ensvar": (-1, 1, "Ensemble variance"),
    "ensvar1": (-1, 1, ""),
    "eof": (1, 2, "Empirical Orthogonal Functions"),
    "eof3d": (1, 2, "Empirical Orthogonal Functions"),
    "eof3dspatial": (1, 2, ""),
    "eof3dtime": (1, 2, ""),
    "eofcoeff": (2, -1, "Principal coefficients of EOFs"),
    "eofcoeff3d": (2, -1, ""),
    "eofspatial": (1, 2, "Empirical Orthogonal Functions"),
    "eoftime": (1, 2, "Empirical Orthogonal Functions"),
    "eq": (2, 1, "Equal"),
    "eqc": (1, 1, "Equal constant"),
    "etccdi": (3, 1, ""),
    "etccdi_cdd": (1, 1, "Consecutive dry days index per time period"),
    "etccdi_csdi": (2, 1, "Cold-spell days index wrt 10th percentile of reference period"),
    "etccdi_cwd": (1, 1, "Consecutive wet days index per time period"),
    "etccdi_fd": (1, 1, "Frost days index per time period"),
    "etccdi_gsl": (2, 1, ""),
    "etccdi_hd": (1, 1, ""),
    "etccdi_id": (1, 1, "Ice days index per time period"),
    "etccdi_r10mm": (1, 1, ""),
    "etccdi_r1mm": (1, 1, "Precipitation days index per time period"),
    "etccdi_r20mm": (1, 1, ""),
    "etccdi_r95p": (3, 1, "ETCCDI conform index for a"),
    "etccdi_r99p": (3, 1, "ETCCDI conform index for a"),
    "etccdi_rx1day": (1, 1, "Highest one day precipitation amount per time period"),
    "etccdi_rx1daymon": (1, 1, ""),
    "etccdi_rx5day": (1, 1, "Highest five-day precipitation amount per time period"),
    "etccdi_rx5daymon": (1, 1, ""),
    "etccdi_sdii": (1, 1, ""),
    "etccdi_su": (1, 1, "Summer days index per time period"),
    "etccdi_tn10p": (3, 1, "ETCCDI conform index for a"),
    "etccdi_tn90p": (3, 1, "ETCCDI conform index for a"),
    "etccdi_tr": (1, 1, "Tropical nights index per time period"),
    "etccdi_tx10p": (3, 1, "ETCCDI conform index for a"),
    "etccdi_tx90p": (3, 1, "ETCCDI conform index for a"),
    "etccdi_wsdi": (2, 1, "Warm Spell Duration Index"),
    "exp": (1, 1, "Exponential"),
    "export_e5ml": (1, 1, ""),
    "expr": (1, 1, "Evaluate expressions"),
    "exprf": (1, 1, "Evaluate expressions script"),
    "fc2gp": (1, 1, ""),
    "fc2sp": (1, 1, ""),
    "fdns": (2, 1, "Frost days where no snow index per time period"),
    "filedes": (1, 0, ""),
    "fillmiss": (1, 1, ""),
    "fillmiss2": (1, 1, ""),
    "fldavg": (1, 1, "Field average"),
    "fldcor": (2, 1, "Correlation in grid space"),
    "fldcount": (1, 1, ""),
    "fldcovar": (2, 1, "Covariance in grid space"),
    "fldint": (1, 1, "Field integral"),
    "fldkurt": (1, 1, ""),
    "fldmax": (1, 1, "Field maximum"),
    "fldmean": (1, 1, "Field mean"),
    "fldmedian": (1, 1, ""),
    "fldmin": (1, 1, "Field minimum"),
    "fldpctl": (1, 1, ""),
    "fldrange": (1, 1, "Field range"),
    "fldrms": (2, 1, ""),
    "fldskew": (1, 1, ""),
    "fldstd": (1, 1, "Field standard deviation"),
    "fldstd1": (1, 1, ""),
    "fldsum": (1, 1, "Field sum"),
    "fldvar": (1, 1, "Field variance"),
    "fldvar1": (1, 1, ""),
    "for": (0, 1, "--> seq"),
    "fourier": (1, 1, "Fourier transformation"),
    "fourier2grid": (1, 1, ""),
    "ge": (2, 1, "Greater equal"),
    "gec": (1, 1, "Greater equal constant"),
    "genbic": (1, 1, "Generate bicubic interpolation weights"),
    "genbil": (1, 1, "Generate bilinear interpolation weights"),
    "gencon": (1, 1, "Generate 1st order conservative remap weights"),
    "gendis": (1, 1, "Generate distance weighted average remap weights"),
    "gengrid": (2, 1, ""),
    "genknn": (1, 1, "k-nearest neighbor remapping"),
    "genlaf": (1, 1, "Largest area fraction remapping"),
    "genlevelbounds": (1, 1, "Generate level bounds"),
    "gennn": (1, 1, "k-nearest neighbor remapping"),
    "genycon": (1, 1, "--> gencon"),
    "genycon2test": (1, 1, ""),
    "gh2hl": (1, 1, "Geometric height interpolation"),
    "gh2hlx": (1, 1, ""),
    "gheight": (1, 1, "Derived model parameters"),
    "gheight_full": (1, 1, "--> gheight"),
    "gheight_half": (1, 1, "Derived model parameters"),
    "gheighthalf": (1, 1, "--> gheight_half"),
    "globavg": (1, 1, "--> fldavg"),
    "gmtcells": (1, 0, "GMT output"),
    "gmtxyz": (1, 0, "GMT output"),
    "gp2fc": (1, 1, ""),
    "gp2sp": (1, 1, "Spectral transformation"),
    "gp2spl": (1, 1, ""),
    "gradsdes": (1, 0, "GrADS data descriptor file"),
    "graph": (-1, 1, "Line graph plot"),
    "grfill": (1, 1, "Lon/Lat plot"),
    "grid2fourier": (1, 1, ""),
    "gridarea": (1, 1, "Grid cell quantities"),
    "gridboxavg": (1, 1, "Gridbox average"),
    "gridboxkurt": (1, 1, "Gridbox kurtosis"),
    "gridboxmax": (1, 1, "Gridbox maximum"),
    "gridboxmean": (1, 1, "Gridbox mean"),
    "gridboxmedian": (1, 1, "Gridbox median"),
    "gridboxmin": (1, 1, "Gridbox minimum"),
    "gridboxrange": (1, 1, "Gridbox range"),
    "gridboxskew": (1, 1, "Gridbox skewness"),
    "gridboxstd": (1, 1, "Gridbox standard deviation"),
    "gridboxstd1": (1, 1, "Gridbox standard deviation (n-1)"),
    "gridboxsum": (1, 1, "Gridbox sum"),
    "gridboxvar": (1, 1, "Gridbox variance"),
    "gridboxvar1": (1, 1, "Gridbox variance (n-1)"),
    "gridcellidx": (1, 1, ""),
    "gridcellindex": (1, 0, "Get grid cell index"),
    "griddes": (1, 0, "Dataset description"),
    "griddes2": (1, 0, ""),
    "griddx": (1, 1, ""),
    "griddy": (1, 1, ""),
    "gridmask": (1, 1, ""),
    "gridweights": (1, 1, "Grid cell quantities"),
    "gt": (2, 1, "Greater than"),
    "gtc": (1, 1, "Greater than constant"),
    "harmonic": (1, 1, ""),
    "highpass": (1, 1, "Time series filtering"),
    "histcount": (1, 1, "Histogram"),
    "histfreq": (1, 1, "Histogram"),
    "histmean": (1, 1, "Histogram"),
    "histsum": (1, 1, "Histogram"),
    "houravg": (1, 1, "Hourly average"),
    "hourcount": (1, 1, ""),
    "hourmax": (1, 1, "Hourly maximum"),
    "hourmean": (1, 1, "Hourly mean"),
    "hourmin": (1, 1, "Hourly minimum"),
    "hourpctl": (3, 1, "Hourly percentile"),
    "hourrange": (1, 1, "Hourly range"),
    "hourstd": (1, 1, "Hourly standard deviation"),
    "hourstd1": (1, 1, "Hourly standard deviation (n-1)"),
    "hoursum": (1, 1, "Hourly sum"),
    "hourvar": (1, 1, "Hourly variance"),
    "hourvar1": (1, 1, "Hourly variance (n-1)"),
    "hpdegrade": (1, 1, "Change healpix resolution"),
    "hpupgrade": (1, 1, "Change healpix resolution"),
    "hurr": (1, 1, "Hurricane days index per time period"),
    "ifnotthen": (2, 1, "If not then"),
    "ifnotthenc": (1, 1, "If not then constant"),
    "ifthen": (2, 1, "If then"),
    "ifthenc": (1, 1, "If then constant"),
    "ifthenelse": (3, 1, "Conditional selection"),
    "im": (1, 1, ""),
    "import_binary": (1, 1, "Import binary data sets"),
    "import_cmsaf": (1, 1, "Import CM-SAF HDF5 files"),
    "import_e5ml": (1, 1, ""),
    "import_fv3grid": (1, 1, ""),
    "import_grads": (1, 1, "--> import_binary"),
    "import_obs": (1, 1, ""),
    "imtocomplex": (1, 1, ""),
    "info": (-1, 0, "Information and simple statistics"),
    "infoc": (-1, 0, ""),
    "infon": (-1, 0, "Information and simple statistics"),
    "infop": (-1, 0, ""),
    "infov": (-1, 0, "--> infon"),
    "input": (0, 1, "ASCII input"),
    "inputext": (0, 1, "EXTRA ASCII input"),
    "inputsrv": (0, 1, "SERVICE ASCII input"),
    "int": (1, 1, "Integer value"),
    "intgridbil": (1, 1, ""),
    "intgriddis": (1, 1, ""),
    "intgridknn": (1, 1, ""),
    "intgridnn": (1, 1, ""),
    "intgridtraj": (1, 1, ""),
    "intlevel": (1, 1, "Linear level interpolation"),
    "intlevel3d": (2, 1, "Linear level interpolation from/to 3D vertical coordinates"),
    "intlevelx": (1, 1, ""),
    "intlevelx3d": (2, 1, ""),
    "intntime": (1, 1, "Interpolation between timesteps"),
    "inttime": (1, 1, "Interpolation between timesteps"),
    "intyear": (2, -1, "Interpolation between two years"),
    "invertlat": (1, 1, "Invert latitudes"),
    "invertlatdata": (1, 1, ""),
    "invertlatdes": (1, 1, ""),
    "invertlev": (1, 1, "Invert levels"),
    "invertlon": (1, 1, ""),
    "invertlondata": (1, 1, ""),
    "invertlondes": (1, 1, ""),
    "isosurface": (1, 1, "Extract surface"),
    "le": (2, 1, "Less equal"),
    "lec": (1, 1, "Less equal constant"),
    "lic": (1, 1, ""),
    "linfo": (1, 0, ""),
    "ln": (1, 1, "Natural logarithm"),
    "log": (1, 1, "--> ln"),
    "log10": (1, 1, "Base 10 logarithm"),
    "lowpass": (1, 1, "Time series filtering"),
    "lt": (2, 1, "Less than"),
    "ltc": (1, 1, "Less than constant"),
    "map": (-1, 0, "Information and simple statistics"),
    "mask": (0, 1, ""),
    "maskcircle": (1, 1, ""),
    "maskindexbox": (1, 1, "Mask an index box"),
    "masklonlatbox": (1, 1, "Mask a longitude/latitude box"),
    "maskregion": (1, 1, "Mask regions"),
    "mastrfu": (1, 1, "Mass stream function"),
    "max": (2, 1, "Arithmetic on two datasets"),
    "maxc": (1, 1, "Arithmetic with a constant"),
    "meandiff2test": (2, 1, ""),
    "meravg": (1, 1, "Meridional average"),
    "merge": (-1, 1, "Merge datasets with different fields"),
    "mergegrid": (2, 1, "Merge grid"),
    "mergetime": (-1, 1, "Merge datasets sorted by date and time"),
    "merkurt": (1, 1, "Meridional kurtosis"),
    "mermax": (1, 1, "Meridional maximum"),
    "mermean": (1, 1, "Meridional mean"),
    "mermedian": (1, 1, "Meridional median"),
    "mermin": (1, 1, "Meridional minimum"),
    "merpctl": (1, 1, "Meridional percentile"),
    "merrange": (1, 1, "Meridional range"),
    "merskew": (1, 1, "Meridional skewness"),
    "merstd": (1, 1, "Meridional standard deviation"),
    "merstd1": (1, 1, "Meridional standard deviation (n-1)"),
    "mersum": (1, 1, "Meridional sum"),
    "mervar": (1, 1, "Meridional variance"),
    "mervar1": (1, 1, "Meridional variance (n-1)"),
    "min": (2, 1, "Arithmetic on two datasets"),
    "minc": (1, 1, "Arithmetic with a constant"),
    "ml2hl": (1, 1, ""),
    "ml2hlx": (1, 1, ""),
    "ml2pl": (1, 1, "Model to pressure level interpolation"),
    "ml2plx": (1, 1, ""),
    "mod": (1, 1, ""),
    "monadd": (2, 1, "Monthly arithmetic"),
    "monavg": (1, 1, "Monthly average"),
    "moncount": (1, 1, ""),
    "mondiv": (2, 1, "Monthly arithmetic"),
    "monmax": (1, 1, "Monthly maximum"),
    "monmean": (1, 1, "Monthly mean"),
    "monmin": (1, 1, "Monthly minimum"),
    "monmul": (2, 1, "Monthly arithmetic"),
    "monpctl": (3, 1, "Monthly percentile"),
    "monrange": (1, 1, "Monthly range"),
    "monstd": (1, 1, "Monthly standard deviation"),
    "monstd1": (1, 1, "Monthly standard deviation (n-1)"),
    "monsub": (2, 1, "Monthly arithmetic"),
    "monsum": (1, 1, "Monthly sum"),
    "monvar": (1, 1, "Monthly variance"),
    "monvar1": (1, 1, "Monthly variance (n-1)"),
    "mrotuv": (1, 2, ""),
    "mrotuvb": (2, 1, "Backward rotation of MPIOM data"),
    "mul": (2, 1, "Arithmetic on two datasets"),
    "mulc": (1, 1, "Arithmetic with a constant"),
    "mulcoslat": (1, 1, "Arithmetic with latitude"),
    "muldoy": (1, 1, ""),
    "muldpm": (1, 1, "Arithmetic with days"),
    "muldpy": (1, 1, "Arithmetic with days"),
    "ncode": (1, 0, ""),
    "ncopy": (1, 1, ""),
    "ndate": (1, 0, "Print the number of parameters, levels or times"),
    "ne": (2, 1, "Not equal"),
    "nec": (1, 1, "Not equal constant"),
    "ngridpoints": (1, 0, "Print the number of parameters, levels or times"),
    "ngrids": (1, 0, "Print the number of parameters, levels or times"),
    "nint": (1, 1, "Nearest integer value"),
    "nlevel": (1, 0, "Print the number of parameters, levels or times"),
    "nmon": (1, 0, "Print the number of parameters, levels or times"),
    "not": (1, 1, "Logical NOT"),
    "npar": (1, 0, "Print the number of parameters, levels or times"),
    "ntime": (1, 0, "Print the number of parameters, levels or times"),
    "nvar": (1, 0, "--> npar"),
    "nyear": (1, 0, "Print the number of parameters, levels or times"),
    "output": (-1, 0, "ASCII output"),
    "outputarr": (-1, 0, ""),
    "outputbounds": (1, 0, "--> gmtcells"),
    "outputboundscpt": (1, 0, ""),
    "outputcenter": (1, 0, "--> gmtxyz"),
    "outputcenter2": (1, 0, ""),
    "outputcentercpt": (1, 0, ""),
    "outputext": (-1, 0, "EXTRA ASCII output"),
    "outputf": (-1, 0, "Formatted output"),
    "outputfld": (-1, 0, ""),
    "outputint": (-1, 0, "Integer output"),
    "outputkey": (-1, 0, "--> outputtab"),
    "outputkml": (1, 0, ""),
    "outputsrv": (-1, 0, "SERVICE ASCII output"),
    "outputtab": (-1, 0, "Table output"),
    "outputtri": (1, 0, ""),
    "outputts": (-1, 0, ""),
    "outputvector": (1, 0, ""),
    "outputvrml": (1, 0, ""),
    "outputxyz": (-1, 0, ""),
    "pack": (1, 1, "Pack data"),
    "pardup": (1, 1, ""),
    "parmul": (1, 1, ""),
    "partab": (1, 0, "Dataset description"),
    "partab2": (1, 0, ""),
    "pinfo": (1, 1, ""),
    "pinfov": (1, 1, ""),
    "pow": (1, 1, "Power"),
    "pressure": (1, 1, "Pressure on model levels"),
    "pressure_full": (1, 1, "--> pressure"),
    "pressure_half": (1, 1, "Pressure on model levels"),
    "projuvLatLon": (1, 1, ""),
    "rand": (1, 1, ""),
    "random": (0, 1, "Generate a field"),
    "re": (1, 1, ""),
    "reci": (1, 1, "Reciprocal value"),
    "recttocomplex": (2, 1, ""),
    "reducegrid": (1, 1, "Reduce fields to user-defined mask"),
    "regres": (1, 1, "Regression"),
    "remap": (1, 1, "Grid remapping"),
    "remapavg": (1, 1, "Remap average"),
    "remapavgtest": (1, 1, ""),
    "remapbic": (1, 1, "Bicubic interpolation"),
    "remapbil": (1, 1, "Bilinear interpolation"),
    "remapcon": (1, 1, "First order conservative remapping"),
    "remapdis": (1, 1, "Distance weighted average remapping"),
    "remapeta": (1, 1, "Remap vertical hybrid levels"),
    "remapeta_s": (1, 1, ""),
    "remapeta_z": (1, 1, ""),
    "remapknn": (1, 1, "k-nearest neighbor remapping"),
    "remapkurt": (1, 1, ""),
    "remaplaf": (1, 1, "Largest area fraction remapping"),
    "remapmax": (1, 1, "Remap maximum"),
    "remapmean": (1, 1, "Remap mean"),
    "remapmedian": (1, 1, ""),
    "remapmin": (1, 1, "Remap minimum"),
    "remapnn": (1, 1, "k-nearest neighbor remapping"),
    "remaprange": (1, 1, "Remap range"),
    "remapskew": (1, 1, ""),
    "remapstd": (1, 1, "Remap standard deviation"),
    "remapstd1": (1, 1, "Remap standard deviation (n-1)"),
    "remapsum": (1, 1, "Remap sum"),
    "remapvar": (1, 1, "Remap variance"),
    "remapvar1": (1, 1, "Remap variance (n-1)"),
    "remapycon": (1, 1, "--> remapcon"),
    "remapycon2test": (1, 1, ""),
    "replace": (2, 1, "Replace variables"),
    "retocomplex": (1, 1, ""),
    "rhopot": (1, 1, "Calculates potential density"),
    "rotuvN": (1, 1, ""),
    "rotuvNorth": (1, 1, ""),
    "rotuvb": (1, 1, "Backward wind rotation"),
    "runavg": (1, 1, "Running average"),
    "runmax": (1, 1, "Running maximum"),
    "runmean": (1, 1, "Running mean"),
    "runmin": (1, 1, "Running minimum"),
    "runpctl": (1, 1, "Running percentile"),
    "runrange": (1, 1, "Running range"),
    "runstd": (1, 1, "Running standard deviation"),
    "runstd1": (1, 1, "Running standard deviation (n-1)"),
    "runsum": (1, 1, "Running sum"),
    "runvar": (1, 1, "Running variance"),
    "runvar1": (1, 1, "Running variance (n-1)"),
    "samplegrid": (1, 1, "Resample grid cells"),
    "samplegridicon": (1, 2, ""),
    "sealevelpressure": (1, 1, "Derived model parameters"),
    "seasavg": (1, 1, "Seasonal average"),
    "seascount": (1, 1, ""),
    "seasmax": (1, 1, "Seasonal maximum"),
    "seasmean": (1, 1, "Seasonal mean"),
    "seasmin": (1, 1, "Seasonal minimum"),
    "seasmonavg": (1, 1, ""),
    "seasmonmean": (1, 1, ""),
    "seaspctl": (3, 1, "Seasonal percentile"),
    "seasrange": (1, 1, "Seasonal range"),
    "seasstd": (1, 1, "Seasonal standard deviation"),
    "seasstd1": (1, 1, "Seasonal standard deviation (n-1)"),
    "seassum": (1, 1, "Seasonal sum"),
    "seasvar": (1, 1, "Seasonal variance"),
    "seasvar1": (1, 1, "Seasonal variance (n-1)"),
    "seinfo": (-1, 0, ""),
    "seinfoc": (-1, 0, ""),
    "seinfon": (-1, 0, ""),
    "seinfop": (-1, 0, ""),
    "selcircle": (1, 1, "Select horizontal regions"),
    "selcode": (1, 1, "Select parameters by code number"),
    "seldate": (1, 1, "Select dates"),
    "selday": (1, 1, "Select days"),
    "select": (-1, 1, "Select fields"),
    "selgrid": (1, 1, "Select grids"),
    "selgridcell": (1, 1, "Select grid cells"),
    "selgridname": (1, 1, "--> selgrid"),
    "selhour": (1, 1, "Select hours"),
    "selindexbox": (1, 1, "Select an index box"),
    "sellevel": (1, 1, "Select levels"),
    "sellevidx": (1, 1, "Select levels by index"),
    "sellonlatbox": (1, 1, "Select a longitude/latitude box"),
    "selltype": (1, 1, "Select GRIB level types"),
    "selmon": (1, 1, "--> selmonth"),
    "selmonth": (1, 1, "Select months"),
    "selmulti": (1, 1, "Select multiple fields via GRIB1 parameters"),
    "selname": (1, 1, "Select parameters by name"),
    "seloperator": (1, 1, ""),
    "selparam": (1, 1, "Select parameters by identifier"),
    "selrec": (1, 1, ""),
    "selregion": (1, 1, "Select horizontal regions"),
    "selseas": (1, 1, "--> selseason"),
    "selseason": (1, 1, "Select seasons"),
    "selsmon": (1, 1, "Select single month"),
    "selstdname": (1, 1, "Select parameters by standard name"),
    "seltabnum": (1, 1, "Select parameter table numbers"),
    "seltime": (1, 1, "Select times"),
    "seltimeidx": (2, 1, "Select timestep by index"),
    "seltimestep": (1, 1, "Select timesteps"),
    "selvar": (1, 1, "--> selname"),
    "selyear": (1, 1, "Select years"),
    "selyearidx": (2, 1, "Select year by index"),
    "selzaxis": (1, 1, "Select z-axes"),
    "selzaxisname": (1, 1, "Select z-axes by name"),
    "seq": (0, 1, "Generate a field"),
    "setattribute": (1, 1, "Set attributes"),
    "setcalendar": (1, 1, "Set calendar"),
    "setchunkspec": (1, 1, "Specify chunking"),
    "setcindexbox": (1, 1, "Set an index box to constant"),
    "setclonlatbox": (1, 1, "Set a longitude/latitude box to constant"),
    "setcode": (1, 1, "Set code number"),
    "setcodetab": (1, 1, "Set parameter code table"),
    "setctomiss": (1, 1, "Set constant to missing value"),
    "setdate": (1, 1, "Set date"),
    "setday": (1, 1, "Set day - Sets the day in every timestep to the same given value"),
    "setfilter": (1, 1, "Specify filter"),
    "setgrid": (1, 1, "Set grid"),
    "setgridarea": (1, 1, "Set grid cell area"),
    "setgridcell": (1, 1, "Set the value of a grid cell"),
    "setgridmask": (1, 1, "Set grid mask"),
    "setgridnumber": (1, 1, ""),
    "setgridtype": (1, 1, "Set grid type"),
    "setgriduri": (1, 1, ""),
    "sethalo": (1, 1, "Set the bounds of a field"),
    "setlevel": (1, 1, "Set level"),
    "setltype": (1, 1, "Set GRIB level type"),
    "setmaxsteps": (1, 1, "Set max timesteps"),
    "setmiss": (2, 1, "Arithmetic on two datasets"),
    "setmisstoc": (1, 1, "Set missing value to constant"),
    "setmisstodis": (1, 1, "Set missing value to distance-weighted average"),
    "setmisstonn": (1, 1, "Set missing value to nearest neighbor"),
    "setmissval": (1, 1, "Set a new missing value"),
    "setmon": (1, 1, "Set month"),
    "setname": (1, 1, "Set variable name"),
    "setparam": (1, 1, "Set parameter identifier"),
    "setpartab": (1, 1, "--> setcodetab"),
    "setpartabc": (1, 1, ""),
    "setpartabn": (1, 1, "Set parameter table"),
    "setpartabp": (1, 1, "Set parameter table"),
    "setpartabv": (1, 1, "--> setpartabn"),
    "setprojparams": (1, 1, "Set proj params"),
    "setrcaname": (1, 1, ""),
    "setreftime": (1, 1, "Set reference time"),
    "setrtoc": (1, 1, "Replace data values"),
    "setrtoc2": (1, 1, "Replace data values"),
    "setrtomiss": (1, 1, "Set range to missing value"),
    "setstdname": (1, 1, "Set standard name"),
    "settabnum": (1, 1, ""),
    "settaxis": (1, 1, "Set time axis"),
    "settbounds": (1, 1, "Set time bounds"),
    "settime": (1, 1, "Set time of the day"),
    "settunits": (1, 1, "Set time units"),
    "setunit": (1, 1, "Set variable unit"),
    "setvals": (1, 1, "Replace data values"),
    "setvar": (1, 1, "--> setname"),
    "setvrange": (1, 1, "Set valid range"),
    "setyear": (1, 1, "Set year"),
    "setzaxis": (1, 1, "Set z-axis"),
    "shaded": (1, 1, "Lon/Lat plot"),
    "shifttime": (1, 1, "Shift timesteps"),
    "shiftx": (1, 1, "Shift field"),
    "shifty": (1, 1, "Shift field"),
    "showattribute": (1, 0, "Show attributes"),
    "showattsvar": (1, 0, ""),
    "showchunkspec": (1, 0, ""),
    "showcode": (1, 0, "Show code numbers"),
    "showdate": (1, 0, "Show date information"),
    "showfilter": (1, 0, ""),
    "showformat": (1, 0, "Show file format"),
    "showgrid": (1, 0, ""),
    "showhistory": (1, 0, ""),
    "showlevel": (1, 0, "Show levels"),
    "showltype": (1, 0, "Show GRIB level types"),
    "showmon": (1, 0, "Show months"),
    "showname": (1, 0, "Show variable names"),
    "showparam": (1, 0, ""),
    "showstdname": (1, 0, "Show standard names"),
    "showtime": (1, 0, "Show time information"),
    "showtimestamp": (1, 0, ""),
    "showunit": (1, 0, ""),
    "showvar": (1, 0, "--> showname"),
    "showyear": (1, 0, "Show years"),
    "sin": (1, 1, "Sine"),
    "sincos": (0, 1, ""),
    "sinfo": (-1, 0, "Short information"),
    "sinfoc": (-1, 0, ""),
    "sinfon": (-1, 0, "Short information"),
    "sinfop": (-1, 0, ""),
    "sinfov": (-1, 0, "--> sinfon"),
    "smooth": (1, 1, "Smooth grid points"),
    "smooth9": (1, 1, "Smooth grid points"),
    "sortcode": (1, 1, ""),
    "sortlevel": (1, 1, ""),
    "sortname": (1, 1, ""),
    "sortparam": (1, 1, ""),
    "sorttaxis": (-1, 1, ""),
    "sorttimestamp": (-1, 1, ""),
    "sortvar": (1, 1, "--> sortname"),
    "sp2fc": (1, 1, ""),
    "sp2gp": (1, 1, "Spectral transformation"),
    "sp2gpl": (1, 1, ""),
    "sp2sp": (1, 1, "Spectral to spectral"),
    "spartab": (1, 0, ""),
    "spcut": (1, 1, ""),
    "specinfo": (0, 0, ""),
    "spectrum": (1, 1, ""),
    "splitcode": (1, -1, "Split code numbers"),
    "splitdate": (1, -1, "Splits a file into dates"),
    "splitdatetime": (1, -1, ""),
    "splitday": (1, -1, "Split days"),
    "splitensemble": (1, -1, "Split ensembles"),
    "splitgrid": (1, -1, "Split grids"),
    "splithour": (1, -1, "Split hours"),
    "splitlevel": (1, -1, "Split levels"),
    "splitmon": (1, -1, "Split months"),
    "splitname": (1, -1, "Split variable names"),
    "splitparam": (1, -1, "Split parameter identifiers"),
    "splitrec": (1, -1, ""),
    "splitseas": (1, -1, "Split seasons"),
    "splitsel": (1, -1, "Split selected timesteps"),
    "splittabnum": (1, -1, "Split parameter table numbers"),
    "splitvar": (1, -1, "--> splitname"),
    "splityear": (1, -1, "Split years"),
    "splityearmon": (1, -1, "Split in years and months"),
    "splitzaxis": (1, -1, "Split z-axes"),
    "sqr": (1, 1, "Square"),
    "sqrt": (1, 1, "Square root"),
    "stdatm": (0, 1, "Generate a field"),
    "strbre": (1, 1, "Strong breeze days index per time period"),
    "stream": (1, 1, ""),
    "strgal": (1, 1, "Strong gale days index per time period"),
    "strwin": (1, 1, "Strong wind days index per time period"),
    "sub": (2, 1, "Arithmetic on two datasets"),
    "subc": (1, 1, "Arithmetic with a constant"),
    "subgrid": (1, 1, ""),
    "subtrend": (3, 1, "Subtract a linear trend from a dataset"),
    "symmetrize": (1, 1, "Mirrors data at the equator"),
    "szip": (-1, 1, ""),
    "tan": (1, 1, "Tangent"),
    "tee": (1, 1, "Duplicate a data stream and write it to file"),
    "temp": (0, 1, ""),
    "testcellsearch": (0, 0, ""),
    "testfield": (0, 1, ""),
    "testpointsearch": (0, 0, ""),
    "thinout": (1, 1, ""),
    "timavg": (1, 1, "Time average"),
    "timcor": (2, 1, "Correlation over time"),
    "timcount": (1, 1, ""),
    "timcovar": (2, 1, "Covariance over time"),
    "timcumsum": (1, 1, "Cumulative sum over all timesteps"),
    "timederivative": (1, 1, ""),
    "timfillmiss": (1, 1, "Temporal filling of missing values"),
    "timmax": (1, 1, "Time maximum"),
    "timmaxidx": (1, 1, "Index of time maximum"),
    "timmean": (1, 1, "Time mean"),
    "timmin": (1, 1, "Time minimum"),
    "timminidx": (1, 1, "Index of time minimum"),
    "timpctl": (3, 1, "Temporal percentile"),
    "timrange": (1, 1, "Time range"),
    "timrmsd": (2, 1, ""),
    "timselavg": (1, 1, "Time selection average"),
    "timselmax": (1, 1, "Time selection maximum"),
    "timselmean": (1, 1, "Time selection mean"),
    "timselmin": (1, 1, "Time selection minimum"),
    "timselpctl": (3, 1, "Time range percentile"),
    "timselrange": (1, 1, "Time selection range"),
    "timselstd": (1, 1, "Time selection standard deviation"),
    "timselstd1": (1, 1, "Time selection standard deviation (n-1)"),
    "timselsum": (1, 1, "Time selection sum"),
    "timselvar": (1, 1, "Time selection variance"),
    "timselvar1": (1, 1, "Time selection variance (n-1)"),
    "timsort": (1, 1, "Temporal sorting"),
    "timstd": (1, 1, "Time standard deviation"),
    "timstd1": (1, 1, "Time standard deviation (n-1)"),
    "timsum": (1, 1, "Time sum"),
    "timvar": (1, 1, "Time variance"),
    "timvar1": (1, 1, "Time variance (n-1)"),
    "timyearavg": (1, 1, ""),
    "timyearmean": (1, 1, "Weighted temporal mean from yearly data"),
    "tinfo": (1, 0, ""),
    "topo": (0, 1, "Generate a field"),
    "topvalue": (1, 1, "Extract surface"),
    "tpnhalo": (1, 1, ""),
    "transxy": (1, 1, ""),
    "trend": (1, 2, "Trend of time series"),
    "tstepcount": (1, 1, ""),
    "unpack": (1, 1, "Unpack data"),
    "unsetgridmask": (1, 1, ""),
    "usegridnumber": (1, 1, ""),
    "uv2dv": (1, 1, "U and V wind to divergence and vorticity"),
    "uv2dv_cfd": (1, 1, "Wind transformation"),
    "uv2dvl": (1, 1, ""),
    "uv2vr_cfd": (1, 1, "Wind transformation"),
    "uvDestag": (1, 1, ""),
    "vardes": (1, 0, "--> codetab"),
    "varquot2test": (2, 1, ""),
    "varrms": (2, 1, ""),
    "varsavg": (1, 1, "Variables average"),
    "varskurt": (1, 1, ""),
    "varsmax": (1, 1, "Variables maximum"),
    "varsmean": (1, 1, "Variables mean"),
    "varsmedian": (1, 1, ""),
    "varsmin": (1, 1, "Variables minimum"),
    "varspctl": (1, 1, ""),
    "varsrange": (1, 1, "Variables range"),
    "varsskew": (1, 1, ""),
    "varsstd": (1, 1, "Variables standard deviation"),
    "varsstd1": (1, 1, "Variables standard deviation (n-1)"),
    "varssum": (1, 1, "Variables sum"),
    "varsvar": (1, 1, "Variables variance"),
    "varsvar1": (1, 1, "Variables variance (n-1)"),
    "vct": (1, 0, "Dataset description"),
    "vct2": (1, 0, ""),
    "vector": (1, 1, "Lon/Lat vector plot"),
    "verifygrid": (1, 0, "Verify grid coordinates"),
    "verifyweights": (0, 0, ""),
    "vertavg": (1, 1, "Vertical average"),
    "vertcum": (1, 1, ""),
    "vertcumhl": (1, 1, ""),
    "vertfillmiss": (1, 1, "Vertical filling of missing values"),
    "vertint": (1, 1, ""),
    "vertmax": (1, 1, "Vertical maximum"),
    "vertmean": (1, 1, "Vertical mean"),
    "vertmin": (1, 1, "Vertical minimum"),
    "vertrange": (1, 1, "Vertical range"),
    "vertstd": (1, 1, "Vertical standard deviation"),
    "vertstd1": (1, 1, "Vertical standard deviation (n-1)"),
    "vertsum": (1, 1, "Vertical sum"),
    "vertvar": (1, 1, "Vertical variance"),
    "vertvar1": (1, 1, "Vertical variance (n-1)"),
    "vertwind": (1, 1, ""),
    "vinfo": (-1, 0, ""),
    "vlist": (1, 0, ""),
    "wct": (2, 1, "Windchill temperature"),
    "writegrid": (1, 1, ""),
    "writerandom": (1, 1, ""),
    "writeremapscrip": (0, 0, ""),
    "xsinfo": (-1, 0, "Extra short information"),
    "xsinfoc": (-1, 0, ""),
    "xsinfon": (-1, 0, ""),
    "xsinfop": (-1, 0, "Extra short information"),
    "ydayadd": (2, 1, "Multi-year daily arithmetic"),
    "ydayavg": (1, 1, "Multi-year daily average"),
    "ydaydiv": (2, 1, "Multi-year daily arithmetic"),
    "ydaymax": (1, 1, "Multi-year daily maximum"),
    "ydaymean": (1, 1, "Multi-year daily mean"),
    "ydaymin": (1, 1, "Multi-year daily minimum"),
    "ydaymul": (2, 1, "Multi-year daily arithmetic"),
    "ydaypctl": (3, 1, "Multi-year daily percentile"),
    "ydayrange": (1, 1, "Multi-year daily range"),
    "ydaystd": (1, 1, "Multi-year daily standard deviation"),
    "ydaystd1": (1, 1, "Multi-year daily standard deviation (n-1)"),
    "ydaysub": (2, 1, "Multi-year daily arithmetic"),
    "ydaysum": (1, 1, "Multi-year daily sum"),
    "ydayvar": (1, 1, "Multi-year daily variance"),
    "ydayvar1": (1, 1, "Multi-year daily variance (n-1)"),
    "ydrunavg": (1, 1, "Multi-year daily running average"),
    "ydrunmax": (1, 1, "Multi-year daily running maximum"),
    "ydrunmean": (1, 1, "Multi-year daily running mean"),
    "ydrunmin": (1, 1, "Multi-year daily running minimum"),
    "ydrunpctl": (3, 1, "Multi-year daily running percentile"),
    "ydrunstd": (1, 1, "Multi-year daily running standard deviation"),
    "ydrunstd1": (1, 1, "Multi-year daily running standard deviation (n-1)"),
    "ydrunsum": (1, 1, "Multi-year daily running sum"),
    "ydrunvar": (1, 1, "Multi-year daily running variance"),
    "ydrunvar1": (1, 1, "Multi-year daily running variance (n-1)"),
    "yearadd": (2, 1, "Yearly arithmetic"),
    "yearavg": (1, 1, "Yearly average"),
    "yearcount": (1, 1, ""),
    "yeardiv": (2, 1, "Yearly arithmetic"),
    "yearmax": (1, 1, "Yearly maximum"),
    "yearmaxidx": (1, 1, "Index of yearly maximum"),
    "yearmean": (1, 1, "Yearly mean"),
    "yearmin": (1, 1, "Yearly minimum"),
    "yearminidx": (1, 1, "Index of yearly minimum"),
    "yearmonavg": (1, 1, ""),
    "yearmonmean": (1, 1, "Yearly mean from monthly data"),
    "yearmul": (2, 1, "Yearly arithmetic"),
    "yearpctl": (3, 1, "Yearly percentile"),
    "yearrange": (1, 1, "Yearly range"),
    "yearstd": (1, 1, "Yearly standard deviation"),
    "yearstd1": (1, 1, "Yearly standard deviation (n-1)"),
    "yearsub": (2, 1, "Yearly arithmetic"),
    "yearsum": (1, 1, "Yearly sum"),
    "yearvar": (1, 1, "Yearly variance"),
    "yearvar1": (1, 1, "Yearly variance (n-1)"),
    "yhouradd": (2, 1, "Multi-year hourly arithmetic"),
    "yhouravg": (1, 1, "Multi-year hourly average"),
    "yhourdiv": (2, 1, "Multi-year hourly arithmetic"),
    "yhourmax": (1, 1, "Multi-year hourly maximum"),
    "yhourmean": (1, 1, "Multi-year hourly mean"),
    "yhourmin": (1, 1, "Multi-year hourly minimum"),
    "yhourmul": (2, 1, "Multi-year hourly arithmetic"),
    "yhourrange": (1, 1, "Multi-year hourly range"),
    "yhourstd": (1, 1, ""),
    "yhourstd1": (1, 1, ""),
    "yhoursub": (2, 1, "Multi-year hourly arithmetic"),
    "yhoursum": (1, 1, "Multi-year hourly sum"),
    "yhourvar": (1, 1, ""),
    "yhourvar1": (1, 1, ""),
    "ymonadd": (2, 1, "Multi-year monthly arithmetic"),
    "ymonavg": (1, 1, "Multi-year monthly average"),
    "ymondiv": (2, 1, "Multi-year monthly arithmetic"),
    "ymoneq": (2, 1, "Multi-year monthly comparison"),
    "ymonge": (2, 1, "Multi-year monthly comparison"),
    "ymongt": (2, 1, "Multi-year monthly comparison"),
    "ymonle": (2, 1, "Multi-year monthly comparison"),
    "ymonlt": (2, 1, "Multi-year monthly comparison"),
    "ymonmax": (1, 1, "Multi-year monthly maximum"),
    "ymonmean": (1, 1, "Multi-year monthly mean"),
    "ymonmin": (1, 1, "Multi-year monthly minimum"),
    "ymonmul": (2, 1, "Multi-year monthly arithmetic"),
    "ymonne": (2, 1, "Multi-year monthly comparison"),
    "ymonpctl": (3, 1, "Multi-year monthly percentile"),
    "ymonrange": (1, 1, "Multi-year monthly range"),
    "ymonstd": (1, 1, "Multi-year monthly standard deviation"),
    "ymonstd1": (1, 1, "Multi-year monthly standard deviation (n-1)"),
    "ymonsub": (2, 1, "Multi-year monthly arithmetic"),
    "ymonsum": (1, 1, "Multi-year monthly sum"),
    "ymonvar": (1, 1, "Multi-year monthly variance"),
    "ymonvar1": (1, 1, "Multi-year monthly variance (n-1)"),
    "yseasadd": (2, 1, "Multi-year seasonal arithmetic"),
    "yseasavg": (1, 1, "Multi-year seasonal average"),
    "yseasdiv": (2, 1, "Multi-year seasonal arithmetic"),
    "yseaseq": (2, 1, "Multi-year seasonal comparison"),
    "yseasge": (2, 1, "Multi-year seasonal comparison"),
    "yseasgt": (2, 1, "Multi-year seasonal comparison"),
    "yseasle": (2, 1, "Multi-year seasonal comparison"),
    "yseaslt": (2, 1, "Multi-year seasonal comparison"),
    "yseasmax": (1, 1, "Multi-year seasonal maximum"),
    "yseasmean": (1, 1, "Multi-year seasonal mean"),
    "yseasmin": (1, 1, "Multi-year seasonal minimum"),
    "yseasmul": (2, 1, "Multi-year seasonal arithmetic"),
    "yseasne": (2, 1, "Multi-year seasonal comparison"),
    "yseaspctl": (3, 1, "Multi-year seasonal percentile"),
    "yseasrange": (1, 1, "Multi-year seasonal range"),
    "yseasstd": (1, 1, "Multi-year seasonal standard deviation"),
    "yseasstd1": (1, 1, "Multi-year seasonal standard deviation (n-1)"),
    "yseassub": (2, 1, "Multi-year seasonal arithmetic"),
    "yseassum": (1, 1, "Multi-year seasonal sum"),
    "yseasvar": (1, 1, "Multi-year seasonal variance"),
    "yseasvar1": (1, 1, "Multi-year seasonal variance (n-1)"),
    "zaxisdes": (1, 0, "Dataset description"),
    "zonavg": (1, 1, "Zonal average"),
    "zonkurt": (1, 1, "Zonal kurtosis"),
    "zonmax": (1, 1, "Zonal maximum"),
    "zonmean": (1, 1, "Zonal mean"),
    "zonmedian": (1, 1, "Zonal median"),
    "zonmin": (1, 1, "Zonal minimum"),
    "zonpctl": (1, 1, "Zonal percentile"),
    "zonrange": (1, 1, "Zonal range"),
    "zonskew": (1, 1, "Zonal skewness"),
    "zonstd": (1, 1, "Zonal standard deviation"),
    "zonstd1": (1, 1, "Zonal standard deviation (n-1)"),
    "zonsum": (1, 1, "Zonal sum"),
    "zonvar": (1, 1, "Zonal variance"),
    "zonvar1": (1, 1, "Zonal variance (n-1)"),
    "zs2zl": (1, 1, ""),
    "zs2zlx": (1, 1, ""),
    "zsdepth": (1, 1, ""),
}

#: ``operator -> CDO module``, probed from the installed binary by
#: ``generate_operator_modules.py``. The module is what decides an
#: operator's category; see ``categories._MODULE_CATEGORY``.
CDO_OPERATOR_MODULES: dict[str, str] = {
    "abs":               "Mathematical functions",
    "acos":              "Mathematical functions",
    "add":               "Arithmetic on two datasets",
    "addc":              "Arithmetic with a constant",
    "addtrend":          "Add or subtract a trend",
    "adipot":            "Potential temperature to in-situ temperature and vice versa",
    "adisit":            "Potential temperature to in-situ temperature and vice versa",
    "aexpr":             "Evaluate expressions",
    "aexprf":            "Evaluate expressions",
    "after":             "ECHAM standard post processor",
    "afterburner":       "ECHAM standard post processor",
    "air_density":       "Derived model parameters",
    "anomaly":           "Multi-year monthly arithmetic",
    "ap2pl":             "Vertical pressure interpolation",
    "arg":               "Mathematical functions",
    "asin":              "Mathematical functions",
    "atan":              "Mathematical functions",
    "atan2":             "Arithmetic on two datasets",
    "bandpass":          "Time series filtering",
    "bitrounding":       "Bit rounding",
    "bottomvalue":       "Extract surface",
    "cat":               "Copy datasets",
    "changemulti":       "Select multiple fields via GRIB1 parameters",
    "chcode":            "Change field header",
    "chlevel":           "Change field header",
    "chlevelc":          "Change field header",
    "chlevelv":          "Change field header",
    "chltype":           "Change field header",
    "chname":            "Change field header",
    "chparam":           "Change field header",
    "chtabnum":          "Change field header",
    "chunit":            "Change field header",
    "chvar":             "Change field header",
    "cinfo":             "Information and simple statistics",
    "clone":             "Copy datasets",
    "cmor":              "Climate Model Output Rewriting to produce CMIP-compliant data",
    "cmorlite":          "CMOR lite",
    "codetab":           "Dataset description",
    "collgrid":          "Collect horizontal grid",
    "conj":              "Mathematical functions",
    "consecsum":         "Consecute timestep periods",
    "consects":          "Consecute timestep periods",
    "const":             "Generate a field",
    "contour":           "Lon/Lat plot",
    "copy":              "Copy datasets",
    "cos":               "Mathematical functions",
    "coshill":           "Generate a field",
    "dayadd":            "Daily arithmetic",
    "dayavg":            "Daily statistics",
    "daydiv":            "Daily arithmetic",
    "daymax":            "Daily statistics",
    "daymean":           "Daily statistics",
    "daymin":            "Daily statistics",
    "daymul":            "Daily arithmetic",
    "daypctl":           "Daily percentile",
    "dayrange":          "Daily statistics",
    "daystd":            "Daily statistics",
    "daystd1":           "Daily statistics",
    "daysub":            "Daily arithmetic",
    "daysum":            "Daily statistics",
    "dayvar":            "Daily statistics",
    "dayvar1":           "Daily statistics",
    "delattribute":      "Set attributes",
    "delcode":           "Select fields",
    "delete":            "Select fields",
    "delgridcell":       "Select grid cells",
    "delmulti":          "Select multiple fields via GRIB1 parameters",
    "delname":           "Select fields",
    "delparam":          "Select fields",
    "delta_pressure":    "Pressure on model levels",
    "deltat":            "Difference between timesteps",
    "delvar":            "Select fields",
    "detrend":           "Detrend time series",
    "dhouravg":          "Multi-day hourly statistics",
    "dhourmax":          "Multi-day hourly statistics",
    "dhourmean":         "Multi-day hourly statistics",
    "dhourmin":          "Multi-day hourly statistics",
    "dhourrange":        "Multi-day hourly statistics",
    "dhourstd":          "Multi-day hourly statistics",
    "dhourstd1":         "Multi-day hourly statistics",
    "dhoursum":          "Multi-day hourly statistics",
    "dhourvar":          "Multi-day hourly statistics",
    "dhourvar1":         "Multi-day hourly statistics",
    "diff":              "Compare two datasets field by field",
    "diffc":             "Compare two datasets field by field",
    "diffn":             "Compare two datasets field by field",
    "diffp":             "Compare two datasets field by field",
    "difftest":          "Compare two datasets field by field",
    "diffv":             "Compare two datasets field by field",
    "distgrid":          "Distribute horizontal grid",
    "div":               "Arithmetic on two datasets",
    "divc":              "Arithmetic with a constant",
    "divcoslat":         "Arithmetic with latitude",
    "divdpm":            "Arithmetic with days",
    "divdpy":            "Arithmetic with days",
    "dminuteavg":        "Multi-day by the minute statistics",
    "dminutemax":        "Multi-day by the minute statistics",
    "dminutemean":       "Multi-day by the minute statistics",
    "dminutemin":        "Multi-day by the minute statistics",
    "dminuterange":      "Multi-day by the minute statistics",
    "dminutestd":        "Multi-day by the minute statistics",
    "dminutestd1":       "Multi-day by the minute statistics",
    "dminutesum":        "Multi-day by the minute statistics",
    "dminutevar":        "Multi-day by the minute statistics",
    "dminutevar1":       "Multi-day by the minute statistics",
    "dumpmap":           "GrADS data descriptor file",
    "duplicate":         "Duplicates a dataset",
    "dv2ps":             "D and V to vel. potential and stream function",
    "dv2uv":             "Wind transformation",
    "dv2uvl":            "Wind transformation",
    "eca_cdd":           "Consecutive dry days index per time period",
    "eca_cfd":           "Consecutive frost days index per time period",
    "eca_csu":           "Consecutive summer days index per time period",
    "eca_cwd":           "Consecutive wet days index per time period",
    "eca_cwdi":          "Cold wave duration index wrt mean of reference period",
    "eca_cwfi":          "Cold-spell days index wrt 10th percentile of reference period",
    "eca_etr":           "Intra-period extreme temperature range",
    "eca_fd":            "Frost days index per time period",
    "eca_gsl":           "Thermal Growing season length index",
    "eca_hd":            "Heating degree days per time period",
    "eca_hwdi":          "Heat wave duration index wrt mean of reference period",
    "eca_hwfi":          "Warm spell index",
    "eca_id":            "Ice days index per time period",
    "eca_pd":            "Precipitation days index per time period",
    "eca_r10mm":         "Precipitation days index per time period",
    "eca_r1mm":          "Wet days index per time period",
    "eca_r20mm":         "Precipitation days index per time period",
    "eca_r75p":          "Moderate wet days wrt 75th percentile of reference period",
    "eca_r75ptot":       "Precipitation percent due to R75p days",
    "eca_r90p":          "Wet days wrt 90th percentile of reference period",
    "eca_r90ptot":       "Precipitation percent due to R90p days",
    "eca_r95p":          "Very wet days wrt 95th percentile of reference period",
    "eca_r95ptot":       "Precipitation percent due to R95p days",
    "eca_r99p":          "Extremely wet days wrt 99th percentile of reference period",
    "eca_r99ptot":       "Precipitation percent due to R99p days",
    "eca_rr1":           "Wet days index per time period",
    "eca_rx1day":        "Highest one day precipitation amount per time period",
    "eca_rx5day":        "Highest five-day precipitation amount per time period",
    "eca_sdii":          "Simple daily intensity index per time period",
    "eca_su":            "Summer days index per time period",
    "eca_tg10p":         "Cold days percent wrt 10th percentile of reference period",
    "eca_tg90p":         "Warm days percent wrt 90th percentile of reference period",
    "eca_tn10p":         "Cold nights percent wrt 10th percentile of reference period",
    "eca_tn90p":         "Warm nights percent wrt 90th percentile of reference period",
    "eca_tr":            "Tropical nights index per time period",
    "eca_tx10p":         "Very cold days percent wrt 10th percentile of reference period",
    "eca_tx90p":         "Very warm days percent wrt 90th percentile of reference period",
    "enlarge":           "Enlarge fields",
    "ensavg":            "Ensemble statistics",
    "ensbrs":            "Ensemble validation tools",
    "enscrps":           "Ensemble validation tools",
    "enskurt":           "Ensemble statistics",
    "ensmax":            "Ensemble statistics",
    "ensmean":           "Ensemble statistics",
    "ensmedian":         "Ensemble statistics",
    "ensmin":            "Ensemble statistics",
    "enspctl":           "Ensemble statistics",
    "ensrange":          "Ensemble statistics",
    "ensrkhistspace":    "Statistical values over an ensemble",
    "ensrkhisttime":     "Statistical values over an ensemble",
    "ensroc":            "Statistical values over an ensemble",
    "ensskew":           "Ensemble statistics",
    "ensstd":            "Ensemble statistics",
    "ensstd1":           "Ensemble statistics",
    "enssum":            "Ensemble statistics",
    "ensvar":            "Ensemble statistics",
    "ensvar1":           "Ensemble statistics",
    "eof":               "Empirical Orthogonal Functions",
    "eof3d":             "Empirical Orthogonal Functions",
    "eof3dspatial":      "Empirical Orthogonal Functions",
    "eof3dtime":         "Empirical Orthogonal Functions",
    "eofcoeff":          "Principal coefficients of EOFs",
    "eofcoeff3d":        "Principal coefficients of EOFs",
    "eofspatial":        "Empirical Orthogonal Functions",
    "eoftime":           "Empirical Orthogonal Functions",
    "eq":                "Comparison of two fields",
    "eqc":               "Comparison of a field with a constant",
    "etccdi":            "ETCCDI conform index for a reference periode calculated with bootstrapping",
    "etccdi_cdd":        "Consecutive dry days index per time period",
    "etccdi_csdi":       "Cold-spell days index wrt 10th percentile of reference period",
    "etccdi_cwd":        "Consecutive wet days index per time period",
    "etccdi_fd":         "Frost days index per time period",
    "etccdi_gsl":        "Thermal Growing season length index",
    "etccdi_hd":         "Heating degree days per time period",
    "etccdi_id":         "Ice days index per time period",
    "etccdi_r10mm":      "Precipitation days index per time period",
    "etccdi_r1mm":       "Precipitation days index per time period",
    "etccdi_r20mm":      "Precipitation days index per time period",
    "etccdi_r95p":       "ETCCDI conform index for a reference periode calculated with bootstrapping",
    "etccdi_r99p":       "ETCCDI conform index for a reference periode calculated with bootstrapping",
    "etccdi_rx1day":     "Highest one day precipitation amount per time period",
    "etccdi_rx1daymon":  "Highest one day precipitation amount per time period",
    "etccdi_rx5day":     "Highest five-day precipitation amount per time period",
    "etccdi_rx5daymon":  "Highest five-day precipitation amount per time period",
    "etccdi_sdii":       "Simple daily intensity index per time period",
    "etccdi_su":         "Summer days index per time period",
    "etccdi_tn10p":      "ETCCDI conform index for a reference periode calculated with bootstrapping",
    "etccdi_tn90p":      "ETCCDI conform index for a reference periode calculated with bootstrapping",
    "etccdi_tr":         "Tropical nights index per time period",
    "etccdi_tx10p":      "ETCCDI conform index for a reference periode calculated with bootstrapping",
    "etccdi_tx90p":      "ETCCDI conform index for a reference periode calculated with bootstrapping",
    "etccdi_wsdi":       "Warm spell index",
    "exp":               "Mathematical functions",
    "expr":              "Evaluate expressions",
    "exprf":             "Evaluate expressions",
    "fdns":              "Frost days where no snow index per time period",
    "filedes":           "Dataset description",
    "fldavg":            "Statistical values over a field",
    "fldcor":            "Correlation in grid space",
    "fldcount":          "Statistical values over a field",
    "fldcovar":          "Covariance in grid space",
    "fldint":            "Statistical values over a field",
    "fldkurt":           "Statistical values over a field",
    "fldmax":            "Statistical values over a field",
    "fldmean":           "Statistical values over a field",
    "fldmedian":         "Statistical values over a field",
    "fldmin":            "Statistical values over a field",
    "fldpctl":           "Statistical values over a field",
    "fldrange":          "Statistical values over a field",
    "fldskew":           "Statistical values over a field",
    "fldstd":            "Statistical values over a field",
    "fldstd1":           "Statistical values over a field",
    "fldsum":            "Statistical values over a field",
    "fldvar":            "Statistical values over a field",
    "fldvar1":           "Statistical values over a field",
    "for":               "Generate a field",
    "fourier":           "Fourier transformation",
    "ge":                "Comparison of two fields",
    "gec":               "Comparison of a field with a constant",
    "genbic":            "Bicubic interpolation",
    "genbil":            "Bilinear interpolation",
    "gencon":            "First order conservative remapping",
    "gendis":            "k-nearest neighbor remapping",
    "genknn":            "k-nearest neighbor remapping",
    "genlaf":            "Largest area fraction remapping",
    "genlevelbounds":    "Set z-axis information",
    "gennn":             "k-nearest neighbor remapping",
    "genycon":           "Bilinear interpolation",
    "gh2hl":             "Geometric height interpolation",
    "gh2hlx":            "Geometric height interpolation",
    "gheight":           "Derived model parameters",
    "gheight_full":      "Derived model parameters",
    "gheight_half":      "Derived model parameters",
    "gheighthalf":       "Derived model parameters",
    "globavg":           "Statistical values over a field",
    "gmtcells":          "GMT output",
    "gmtxyz":            "GMT output",
    "gp2sp":             "Spectral transformation",
    "gp2spl":            "Spectral transformation",
    "gradsdes":          "GrADS data descriptor file",
    "graph":             "Line graph plot",
    "grfill":            "Lon/Lat plot",
    "gridarea":          "Grid cell quantities",
    "gridboxavg":        "Statistical values over grid boxes",
    "gridboxkurt":       "Statistical values over grid boxes",
    "gridboxmax":        "Statistical values over grid boxes",
    "gridboxmean":       "Statistical values over grid boxes",
    "gridboxmedian":     "Statistical values over grid boxes",
    "gridboxmin":        "Statistical values over grid boxes",
    "gridboxrange":      "Statistical values over grid boxes",
    "gridboxskew":       "Statistical values over grid boxes",
    "gridboxstd":        "Statistical values over grid boxes",
    "gridboxstd1":       "Statistical values over grid boxes",
    "gridboxsum":        "Statistical values over grid boxes",
    "gridboxvar":        "Statistical values over grid boxes",
    "gridboxvar1":       "Statistical values over grid boxes",
    "gridcellidx":       "Grid cell quantities",
    "gridcellindex":     "Get grid cell index",
    "griddes":           "Dataset description",
    "griddes2":          "Dataset description",
    "griddx":            "Grid cell quantities",
    "griddy":            "Grid cell quantities",
    "gridmask":          "Grid cell quantities",
    "gridweights":       "Grid cell quantities",
    "gt":                "Comparison of two fields",
    "gtc":               "Comparison of a field with a constant",
    "highpass":          "Time series filtering",
    "histcount":         "Histogram",
    "histfreq":          "Histogram",
    "histmean":          "Histogram",
    "histsum":           "Histogram",
    "houravg":           "Hourly statistics",
    "hourmax":           "Hourly statistics",
    "hourmean":          "Hourly statistics",
    "hourmin":           "Hourly statistics",
    "hourpctl":          "Hourly percentile",
    "hourrange":         "Hourly statistics",
    "hourstd":           "Hourly statistics",
    "hourstd1":          "Hourly statistics",
    "hoursum":           "Hourly statistics",
    "hourvar":           "Hourly statistics",
    "hourvar1":          "Hourly statistics",
    "hpdegrade":         "Change healpix resolution",
    "hpupgrade":         "Change healpix resolution",
    "hurr":              "Hurricane days index per time period",
    "ifnotthen":         "Conditional selection",
    "ifnotthenc":        "Conditional selection",
    "ifthen":            "Conditional selection",
    "ifthenc":           "Conditional selection",
    "ifthenelse":        "Conditional selection",
    "im":                "Mathematical functions",
    "import_binary":     "Import binary data sets",
    "import_cmsaf":      "Import CM-SAF HDF5 files",
    "import_grads":      "Import binary data sets",
    "info":              "Information and simple statistics",
    "infoc":             "Information and simple statistics",
    "infon":             "Information and simple statistics",
    "infop":             "Information and simple statistics",
    "infov":             "Short information",
    "input":             "Formatted input",
    "inputext":          "Formatted input",
    "inputsrv":          "Formatted input",
    "int":               "Mathematical functions",
    "intlevel":          "Linear level interpolation",
    "intlevel3d":        "Linear level interpolation from/to 3D vertical coordinates",
    "intlevelx":         "Linear level interpolation",
    "intlevelx3d":       "Linear level interpolation from/to 3D vertical coordinates",
    "intntime":          "Time interpolation",
    "inttime":           "Time interpolation",
    "intyear":           "Interpolation between two years",
    "invertlat":         "Invert latitudes",
    "invertlatdata":     "Invert latitudes",
    "invertlatdes":      "Invert latitudes",
    "invertlev":         "Invert levels",
    "invertlon":         "Invert latitudes",
    "invertlondata":     "Invert latitudes",
    "invertlondes":      "Invert latitudes",
    "isosurface":        "Extract surface",
    "le":                "Comparison of two fields",
    "lec":               "Comparison of a field with a constant",
    "ln":                "Mathematical functions",
    "log":               "Mathematical functions",
    "log10":             "Mathematical functions",
    "lowpass":           "Time series filtering",
    "lt":                "Comparison of two fields",
    "ltc":               "Comparison of a field with a constant",
    "map":               "Information and simple statistics",
    "mask":              "Generate a field",
    "maskcircle":        "Mask regions",
    "maskindexbox":      "Mask a box",
    "masklonlatbox":     "Mask a box",
    "maskregion":        "Mask regions",
    "mastrfu":           "Mass stream function",
    "max":               "Arithmetic on two datasets",
    "maxc":              "Arithmetic with a constant",
    "meravg":            "Meridional statistics",
    "merge":             "Merge datasets",
    "mergegrid":         "Merge grid",
    "mergetime":         "Merge datasets",
    "merkurt":           "Meridional statistics",
    "mermax":            "Meridional statistics",
    "mermean":           "Meridional statistics",
    "mermedian":         "Meridional statistics",
    "mermin":            "Meridional statistics",
    "merpctl":           "Meridional statistics",
    "merrange":          "Meridional statistics",
    "merskew":           "Meridional statistics",
    "merstd":            "Meridional statistics",
    "merstd1":           "Meridional statistics",
    "mersum":            "Meridional statistics",
    "mervar":            "Meridional statistics",
    "mervar1":           "Meridional statistics",
    "min":               "Arithmetic on two datasets",
    "minc":              "Arithmetic with a constant",
    "ml2pl":             "Model to pressure level interpolation",
    "ml2plx":            "Model to pressure level interpolation",
    "mod":               "Arithmetic with a constant",
    "monadd":            "Monthly arithmetic",
    "monavg":            "Monthly statistics",
    "mondiv":            "Monthly arithmetic",
    "monmax":            "Monthly statistics",
    "monmean":           "Monthly statistics",
    "monmin":            "Monthly statistics",
    "monmul":            "Monthly arithmetic",
    "monpctl":           "Monthly percentile",
    "monrange":          "Monthly statistics",
    "monstd":            "Monthly statistics",
    "monstd1":           "Monthly statistics",
    "monsub":            "Monthly arithmetic",
    "monsum":            "Monthly statistics",
    "monvar":            "Monthly statistics",
    "monvar1":           "Monthly statistics",
    "mrotuvb":           "Backward rotation of MPIOM data",
    "mul":               "Arithmetic on two datasets",
    "mulc":              "Arithmetic with a constant",
    "mulcoslat":         "Arithmetic with latitude",
    "muldoy":            "Arithmetic with days",
    "muldpm":            "Arithmetic with days",
    "muldpy":            "Arithmetic with days",
    "ncode":             "Print the number of parameters, levels or times",
    "ndate":             "Print the number of parameters, levels or times",
    "ne":                "Comparison of two fields",
    "nec":               "Comparison of a field with a constant",
    "ngridpoints":       "Print the number of parameters, levels or times",
    "ngrids":            "Print the number of parameters, levels or times",
    "nint":              "Mathematical functions",
    "nlevel":            "Print the number of parameters, levels or times",
    "nmon":              "Print the number of parameters, levels or times",
    "not":               "Mathematical functions",
    "npar":              "Print the number of parameters, levels or times",
    "ntime":             "Print the number of parameters, levels or times",
    "nvar":              "Print the number of parameters, levels or times",
    "nyear":             "Print the number of parameters, levels or times",
    "output":            "Formatted output",
    "outputarr":         "Formatted output",
    "outputbounds":      "GMT output",
    "outputboundscpt":   "GMT output",
    "outputcenter":      "GMT output",
    "outputcenter2":     "GMT output",
    "outputcentercpt":   "GMT output",
    "outputext":         "Formatted output",
    "outputf":           "Formatted output",
    "outputfld":         "Formatted output",
    "outputint":         "Formatted output",
    "outputkey":         "Formatted output",
    "outputkml":         "GMT output",
    "outputsrv":         "Formatted output",
    "outputtab":         "Table output",
    "outputtri":         "GMT output",
    "outputts":          "Formatted output",
    "outputvector":      "GMT output",
    "outputvrml":        "GMT output",
    "outputxyz":         "Formatted output",
    "pack":              "Pack data",
    "partab":            "Dataset description",
    "partab2":           "Dataset description",
    "pow":               "Mathematical functions",
    "pressure":          "Pressure on model levels",
    "pressure_full":     "Pressure on model levels",
    "pressure_half":     "Pressure on model levels",
    "projuvLatLon":      "Wind transformation",
    "rand":              "Mathematical functions",
    "random":            "Generate a field",
    "re":                "Mathematical functions",
    "reci":              "Mathematical functions",
    "reducegrid":        "Reduce fields to user-defined mask",
    "regres":            "Regression",
    "remap":             "Grid remapping",
    "remapavg":          "Remaps source points to target cells",
    "remapbic":          "Bicubic interpolation",
    "remapbil":          "Bilinear interpolation",
    "remapcon":          "First order conservative remapping",
    "remapdis":          "k-nearest neighbor remapping",
    "remapeta":          "Remap vertical hybrid levels",
    "remapeta_s":        "Remap vertical hybrid levels",
    "remapeta_z":        "Remap vertical hybrid levels",
    "remapknn":          "k-nearest neighbor remapping",
    "remapkurt":         "Remaps source points to target cells",
    "remaplaf":          "Largest area fraction remapping",
    "remapmax":          "Remaps source points to target cells",
    "remapmean":         "Remaps source points to target cells",
    "remapmedian":       "Remaps source points to target cells",
    "remapmin":          "Remaps source points to target cells",
    "remapnn":           "k-nearest neighbor remapping",
    "remaprange":        "Remaps source points to target cells",
    "remapskew":         "Remaps source points to target cells",
    "remapstd":          "Remaps source points to target cells",
    "remapstd1":         "Remaps source points to target cells",
    "remapsum":          "Remaps source points to target cells",
    "remapvar":          "Remaps source points to target cells",
    "remapvar1":         "Remaps source points to target cells",
    "remapycon":         "Grid remapping",
    "replace":           "Replace variables",
    "rhopot":            "Calculates potential density",
    "rotuvN":            "Wind transformation",
    "rotuvNorth":        "Wind transformation",
    "rotuvb":            "Backward wind rotation",
    "runavg":            "Running statistics",
    "runmax":            "Running statistics",
    "runmean":           "Running statistics",
    "runmin":            "Running statistics",
    "runpctl":           "Running percentile",
    "runrange":          "Running statistics",
    "runstd":            "Running statistics",
    "runstd1":           "Running statistics",
    "runsum":            "Running statistics",
    "runvar":            "Running statistics",
    "runvar1":           "Running statistics",
    "samplegrid":        "Resample grid cells",
    "sealevelpressure":  "Derived model parameters",
    "seasavg":           "Seasonal statistics",
    "seasmax":           "Seasonal statistics",
    "seasmean":          "Seasonal statistics",
    "seasmin":           "Seasonal statistics",
    "seaspctl":          "Seasonal percentile",
    "seasrange":         "Seasonal statistics",
    "seasstd":           "Seasonal statistics",
    "seasstd1":          "Seasonal statistics",
    "seassum":           "Seasonal statistics",
    "seasvar":           "Seasonal statistics",
    "seasvar1":          "Seasonal statistics",
    "seinfo":            "Short information",
    "seinfoc":           "Short information",
    "seinfon":           "Short information",
    "seinfop":           "Short information",
    "selcircle":         "Select horizontal regions",
    "selcode":           "Select fields",
    "seldate":           "Select timesteps",
    "selday":            "Select timesteps",
    "select":            "Select fields",
    "selgrid":           "Select fields",
    "selgridcell":       "Select grid cells",
    "selgridname":       "Select fields",
    "selhour":           "Select timesteps",
    "selindexbox":       "Select a box",
    "sellevel":          "Select fields",
    "sellevidx":         "Select fields",
    "sellonlatbox":      "Select a box",
    "selltype":          "Select fields",
    "selmon":            "Select timesteps",
    "selmonth":          "Select timesteps",
    "selmulti":          "Select multiple fields via GRIB1 parameters",
    "selname":           "Select fields",
    "selparam":          "Select fields",
    "selrec":            "Select fields",
    "selregion":         "Select horizontal regions",
    "selseas":           "Select timesteps",
    "selseason":         "Select timesteps",
    "selsmon":           "Select timesteps",
    "selstdname":        "Select fields",
    "seltabnum":         "Select fields",
    "seltime":           "Select timesteps",
    "seltimeidx":        "Select timestep by index",
    "seltimestep":       "Select timesteps",
    "selvar":            "Select fields",
    "selyear":           "Select timesteps",
    "selyearidx":        "Select year by index",
    "selzaxis":          "Select fields",
    "selzaxisname":      "Select fields",
    "seq":               "Generate a field",
    "setattribute":      "Set attributes",
    "setcalendar":       "Set time",
    "setchunkspec":      "Specify chunking",
    "setcindexbox":      "Set a box to constant",
    "setclonlatbox":     "Set a box to constant",
    "setcode":           "Set field info",
    "setcodetab":        "Set field info",
    "setctomiss":        "Set missing value",
    "setdate":           "Set time",
    "setday":            "Set time",
    "setfilter":         "Specify filter",
    "setgrid":           "Set grid information",
    "setgridarea":       "Set grid information",
    "setgridcell":       "Set the value of a grid cell",
    "setgridmask":       "Set grid information",
    "setgridnumber":     "Set grid information",
    "setgridtype":       "Set grid information",
    "setgriduri":        "Set grid information",
    "sethalo":           "Set the bounds of a field",
    "setlevel":          "Set field info",
    "setltype":          "Set field info",
    "setmaxsteps":       "Set field info",
    "setmiss":           "Arithmetic on two datasets",
    "setmisstoc":        "Set missing value",
    "setmisstodis":      "Set missing value",
    "setmisstonn":       "Set missing value",
    "setmissval":        "Set missing value",
    "setmon":            "Set time",
    "setname":           "Set field info",
    "setparam":          "Set field info",
    "setpartab":         "Set field info",
    "setpartabc":        "Set parameter table",
    "setpartabn":        "Set parameter table",
    "setpartabp":        "Set parameter table",
    "setpartabv":        "Set field info",
    "setprojparams":     "Set grid information",
    "setreftime":        "Set time",
    "setrtoc":           "Replace data values",
    "setrtoc2":          "Replace data values",
    "setrtomiss":        "Set missing value",
    "setstdname":        "Set field info",
    "settabnum":         "Set field info",
    "settaxis":          "Set time",
    "settbounds":        "Set time",
    "settime":           "Set time",
    "settunits":         "Set time",
    "setunit":           "Set field info",
    "setvals":           "Replace data values",
    "setvar":            "Set field info",
    "setvrange":         "Set missing value",
    "setyear":           "Set time",
    "setzaxis":          "Set z-axis information",
    "shaded":            "Lon/Lat plot",
    "shifttime":         "Set time",
    "shiftx":            "Shift field",
    "shifty":            "Shift field",
    "showattribute":     "Show attributes",
    "showattsvar":       "Show attributes",
    "showchunkspec":     "Show variable information",
    "showcode":          "Show variable information",
    "showdate":          "Show variable information",
    "showfilter":        "Show variable information",
    "showformat":        "Show variable information",
    "showgrid":          "Show variable information",
    "showlevel":         "Show variable information",
    "showltype":         "Show variable information",
    "showmon":           "Show variable information",
    "showname":          "Show variable information",
    "showparam":         "Show variable information",
    "showstdname":       "Show variable information",
    "showtime":          "Show variable information",
    "showtimestamp":     "Show variable information",
    "showunit":          "Show variable information",
    "showvar":           "Show variable information",
    "showyear":          "Show variable information",
    "sin":               "Mathematical functions",
    "sincos":            "Generate a field",
    "sinfo":             "Short information",
    "sinfoc":            "Short information",
    "sinfon":            "Short information",
    "sinfop":            "Short information",
    "sinfov":            "Short information",
    "smooth":            "Smooth grid points",
    "smooth9":           "Smooth grid points",
    "sortvar":           "Sort",
    "sp2gp":             "Spectral transformation",
    "sp2gpl":            "Spectral transformation",
    "sp2sp":             "Spectral to spectral",
    "spartab":           "Dataset description",
    "spcut":             "Spectral to spectral",
    "splitcode":         "Split a dataset",
    "splitdate":         "Splits a file into dates",
    "splitdatetime":     "Splits a file into dates",
    "splitday":          "Split timesteps of a dataset",
    "splitensemble":     "Split a dataset",
    "splitgrid":         "Split a dataset",
    "splithour":         "Split timesteps of a dataset",
    "splitlevel":        "Split a dataset",
    "splitmon":          "Split timesteps of a dataset",
    "splitname":         "Split a dataset",
    "splitparam":        "Split a dataset",
    "splitrec":          "Split a dataset",
    "splitseas":         "Split timesteps of a dataset",
    "splitsel":          "Split selected timesteps",
    "splittabnum":       "Split a dataset",
    "splitvar":          "Split a dataset",
    "splityear":         "Split timesteps of a dataset",
    "splityearmon":      "Split timesteps of a dataset",
    "splitzaxis":        "Split a dataset",
    "sqr":               "Mathematical functions",
    "sqrt":              "Mathematical functions",
    "stdatm":            "Generate a field",
    "strbre":            "Strong breeze days index per time period",
    "stream":            "Lon/Lat vector plot",
    "strgal":            "Strong gale days index per time period",
    "strwin":            "Strong wind days index per time period",
    "sub":               "Arithmetic on two datasets",
    "subc":              "Arithmetic with a constant",
    "subgrid":           "Resample grid cells",
    "subtrend":          "Add or subtract a trend",
    "symmetrize":        "Mirrors data at the equator",
    "szip":              "Copy datasets",
    "tan":               "Mathematical functions",
    "tee":               "Duplicate a data stream and write it to file",
    "temp":              "Generate a field",
    "testfield":         "Generate a field",
    "timavg":            "Statistical values over all timesteps",
    "timcor":            "Correlation over time",
    "timcovar":          "Covariance over time",
    "timcumsum":         "Cumulative sum over all timesteps",
    "timederivative":    "Difference between timesteps",
    "timfillmiss":       "Temporal filling of missing values",
    "timmax":            "Statistical values over all timesteps",
    "timmaxidx":         "Statistical values over all timesteps",
    "timmean":           "Statistical values over all timesteps",
    "timmin":            "Statistical values over all timesteps",
    "timminidx":         "Statistical values over all timesteps",
    "timpctl":           "Temporal percentile",
    "timrange":          "Statistical values over all timesteps",
    "timselavg":         "Time range statistics",
    "timselmax":         "Time range statistics",
    "timselmean":        "Time range statistics",
    "timselmin":         "Time range statistics",
    "timselpctl":        "Time range percentile",
    "timselrange":       "Time range statistics",
    "timselstd":         "Time range statistics",
    "timselstd1":        "Time range statistics",
    "timselsum":         "Time range statistics",
    "timselvar":         "Time range statistics",
    "timselvar1":        "Time range statistics",
    "timsort":           "Temporal sorting",
    "timstd":            "Statistical values over all timesteps",
    "timstd1":           "Statistical values over all timesteps",
    "timsum":            "Statistical values over all timesteps",
    "timvar":            "Statistical values over all timesteps",
    "timvar1":           "Statistical values over all timesteps",
    "timyearavg":        "Weighted temporal mean from yearly data",
    "timyearmean":       "Weighted temporal mean from yearly data",
    "topo":              "Generate a field",
    "topvalue":          "Extract surface",
    "tpnhalo":           "Set the bounds of a field",
    "trend":             "Trend of time series",
    "unpack":            "Unpack data",
    "unsetgridmask":     "Set grid information",
    "usegridnumber":     "Set grid information",
    "uv2dv":             "Wind transformation",
    "uv2dv_cfd":         "Wind transformation",
    "uv2dvl":            "Wind transformation",
    "uv2vr_cfd":         "Wind transformation",
    "uvDestag":          "Wind transformation",
    "vardes":            "Dataset description",
    "varsavg":           "Statistical values over all variables",
    "varskurt":          "Statistical values over all variables",
    "varsmax":           "Statistical values over all variables",
    "varsmean":          "Statistical values over all variables",
    "varsmedian":        "Statistical values over all variables",
    "varsmin":           "Statistical values over all variables",
    "varspctl":          "Statistical values over all variables",
    "varsrange":         "Statistical values over all variables",
    "varsskew":          "Statistical values over all variables",
    "varsstd":           "Statistical values over all variables",
    "varsstd1":          "Statistical values over all variables",
    "varssum":           "Statistical values over all variables",
    "varsvar":           "Statistical values over all variables",
    "varsvar1":          "Statistical values over all variables",
    "vct":               "Dataset description",
    "vct2":              "Dataset description",
    "vector":            "Lon/Lat vector plot",
    "verifygrid":        "Verify grid coordinates",
    "vertavg":           "Vertical statistics",
    "vertfillmiss":      "Vertical filling of missing values",
    "vertint":           "Vertical statistics",
    "vertmax":           "Vertical statistics",
    "vertmean":          "Vertical statistics",
    "vertmin":           "Vertical statistics",
    "vertrange":         "Vertical statistics",
    "vertstd":           "Vertical statistics",
    "vertstd1":          "Vertical statistics",
    "vertsum":           "Vertical statistics",
    "vertvar":           "Vertical statistics",
    "vertvar1":          "Vertical statistics",
    "vinfo":             "Information and simple statistics",
    "vlist":             "Dataset description",
    "wct":               "Windchill temperature",
    "xsinfo":            "Extra short information",
    "xsinfoc":           "Extra short information",
    "xsinfon":           "Extra short information",
    "xsinfop":           "Extra short information",
    "ydayadd":           "Multi-year daily arithmetic",
    "ydayavg":           "Multi-year daily statistics",
    "ydaydiv":           "Multi-year daily arithmetic",
    "ydaymax":           "Multi-year daily statistics",
    "ydaymean":          "Multi-year daily statistics",
    "ydaymin":           "Multi-year daily statistics",
    "ydaymul":           "Multi-year daily arithmetic",
    "ydaypctl":          "Multi-year daily percentile",
    "ydayrange":         "Multi-year daily statistics",
    "ydaystd":           "Multi-year daily statistics",
    "ydaystd1":          "Multi-year daily statistics",
    "ydaysub":           "Multi-year daily arithmetic",
    "ydaysum":           "Multi-year daily statistics",
    "ydayvar":           "Multi-year daily statistics",
    "ydayvar1":          "Multi-year daily statistics",
    "ydrunavg":          "Multi-year daily running statistics",
    "ydrunmax":          "Multi-year daily running statistics",
    "ydrunmean":         "Multi-year daily running statistics",
    "ydrunmin":          "Multi-year daily running statistics",
    "ydrunpctl":         "Multi-year daily running percentile",
    "ydrunstd":          "Multi-year daily running statistics",
    "ydrunstd1":         "Multi-year daily running statistics",
    "ydrunsum":          "Multi-year daily running statistics",
    "ydrunvar":          "Multi-year daily running statistics",
    "ydrunvar1":         "Multi-year daily running statistics",
    "yearadd":           "Yearly arithmetic",
    "yearavg":           "Yearly statistics",
    "yeardiv":           "Yearly arithmetic",
    "yearmax":           "Yearly statistics",
    "yearmaxidx":        "Yearly statistics",
    "yearmean":          "Yearly statistics",
    "yearmin":           "Yearly statistics",
    "yearminidx":        "Yearly statistics",
    "yearmonavg":        "Weighted yearly mean from monthly data",
    "yearmonmean":       "Weighted yearly mean from monthly data",
    "yearmul":           "Yearly arithmetic",
    "yearpctl":          "Yearly percentile",
    "yearrange":         "Yearly statistics",
    "yearstd":           "Yearly statistics",
    "yearstd1":          "Yearly statistics",
    "yearsub":           "Yearly arithmetic",
    "yearsum":           "Yearly statistics",
    "yearvar":           "Yearly statistics",
    "yearvar1":          "Yearly statistics",
    "yhouradd":          "Multi-year hourly arithmetic",
    "yhouravg":          "Multi-year hourly statistics",
    "yhourdiv":          "Multi-year hourly arithmetic",
    "yhourmax":          "Multi-year hourly statistics",
    "yhourmean":         "Multi-year hourly statistics",
    "yhourmin":          "Multi-year hourly statistics",
    "yhourmul":          "Multi-year hourly arithmetic",
    "yhourrange":        "Multi-year hourly statistics",
    "yhourstd":          "Multi-year hourly statistics",
    "yhourstd1":         "Multi-year hourly statistics",
    "yhoursub":          "Multi-year hourly arithmetic",
    "yhoursum":          "Multi-year hourly statistics",
    "yhourvar":          "Multi-year hourly statistics",
    "yhourvar1":         "Multi-year hourly statistics",
    "ymonadd":           "Multi-year monthly arithmetic",
    "ymonavg":           "Multi-year monthly statistics",
    "ymondiv":           "Multi-year monthly arithmetic",
    "ymoneq":            "Multi-year monthly comparison",
    "ymonge":            "Multi-year monthly comparison",
    "ymongt":            "Multi-year monthly comparison",
    "ymonle":            "Multi-year monthly comparison",
    "ymonlt":            "Multi-year monthly comparison",
    "ymonmax":           "Multi-year monthly statistics",
    "ymonmean":          "Multi-year monthly statistics",
    "ymonmin":           "Multi-year monthly statistics",
    "ymonmul":           "Multi-year monthly arithmetic",
    "ymonne":            "Multi-year monthly comparison",
    "ymonpctl":          "Multi-year monthly percentile",
    "ymonrange":         "Multi-year monthly statistics",
    "ymonstd":           "Multi-year monthly statistics",
    "ymonstd1":          "Multi-year monthly statistics",
    "ymonsub":           "Multi-year monthly arithmetic",
    "ymonsum":           "Multi-year monthly statistics",
    "ymonvar":           "Multi-year monthly statistics",
    "ymonvar1":          "Multi-year monthly statistics",
    "yseasadd":          "Multi-year seasonal arithmetic",
    "yseasavg":          "Multi-year seasonal statistics",
    "yseasdiv":          "Multi-year seasonal arithmetic",
    "yseaseq":           "Multi-year seasonal comparison",
    "yseasge":           "Multi-year seasonal comparison",
    "yseasgt":           "Multi-year seasonal comparison",
    "yseasle":           "Multi-year seasonal comparison",
    "yseaslt":           "Multi-year seasonal comparison",
    "yseasmax":          "Multi-year seasonal statistics",
    "yseasmean":         "Multi-year seasonal statistics",
    "yseasmin":          "Multi-year seasonal statistics",
    "yseasmul":          "Multi-year seasonal arithmetic",
    "yseasne":           "Multi-year seasonal comparison",
    "yseaspctl":         "Multi-year seasonal percentile",
    "yseasrange":        "Multi-year seasonal statistics",
    "yseasstd":          "Multi-year seasonal statistics",
    "yseasstd1":         "Multi-year seasonal statistics",
    "yseassub":          "Multi-year seasonal arithmetic",
    "yseassum":          "Multi-year seasonal statistics",
    "yseasvar":          "Multi-year seasonal statistics",
    "yseasvar1":         "Multi-year seasonal statistics",
    "zaxisdes":          "Dataset description",
    "zonavg":            "Zonal statistics",
    "zonkurt":           "Zonal statistics",
    "zonmax":            "Zonal statistics",
    "zonmean":           "Zonal statistics",
    "zonmedian":         "Zonal statistics",
    "zonmin":            "Zonal statistics",
    "zonpctl":           "Zonal statistics",
    "zonrange":          "Zonal statistics",
    "zonskew":           "Zonal statistics",
    "zonstd":            "Zonal statistics",
    "zonstd1":           "Zonal statistics",
    "zonsum":            "Zonal statistics",
    "zonvar":            "Zonal statistics",
    "zonvar1":           "Zonal statistics",
}
